[package]
name = "fabelgeist-rig"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/adventure-simulator-group/fabelgeist"
license = "GPL-3.0"

[features]
fbx = ["dep:fabelgeist-fbx"]

[dependencies]
serde = { version = "1", features = ["derive"] }
fabelgeist-fbx = { optional = true, path = "../fabelgeist-fbx" }

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
