//! Authored sampling weights and period display forms; see `../person_names.md`.
use super::NameFamily;

// Family weights are estimates. Variants divide, rather than multiply, them.
pub(super) const MALE: &[NameFamily] = &[
    NameFamily::new(200, &["Hans", "Johann"]),
    NameFamily::new(100, &["Heinrich", "Hinrik"]),
    NameFamily::new(70, &["Konrad", "Cord"]),
    NameFamily::new(60, &["Nikolaus", "Claus"]),
    NameFamily::new(60, &["Hermann", "Hermen"]),
    NameFamily::new(50, &["Caspar", "Jasper"]),
    NameFamily::new(50, &["Peter"]),
    NameFamily::new(45, &["Georg", "Jurgen"]),
    NameFamily::new(40, &["Jacob"]),
    NameFamily::new(40, &["Dietrich", "Diderick"]),
    NameFamily::new(35, &["Martin"]),
    NameFamily::new(30, &["Gerd"]),
    NameFamily::new(30, &["Valentin"]),
    NameFamily::new(25, &["Moritz"]),
    NameFamily::new(25, &["Michael"]),
    NameFamily::new(25, &["Franz"]),
    NameFamily::new(20, &["Bernd"]),
    NameFamily::new(20, &["Joachim", "Jochim"]),
    NameFamily::new(20, &["Andreas"]),
    NameFamily::new(20, &["Matthias", "Mathies"]),
    NameFamily::new(15, &["Paul", "Pawel"]),
    NameFamily::new(15, &["Otto", "Otte"]),
    NameFamily::new(15, &["Albert"]),
    NameFamily::new(15, &["Christoph"]),
    NameFamily::new(10, &["Arndt"]),
    NameFamily::new(10, &["Evert"]),
    NameFamily::new(10, &["Werner"]),
    NameFamily::new(10, &["Willem"]),
    NameFamily::new(10, &["Bartholomeus", "Barthel"]),
    NameFamily::new(10, &["Sebastian"]),
    NameFamily::new(10, &["Melchior"]),
    NameFamily::new(5, &["Simon"]),
];

pub(super) const FEMALE: &[NameFamily] = &[
    NameFamily::new(175, &["Margaretha", "Greteke"]),
    NameFamily::new(146, &["Anna", "Anneke"]),
    NameFamily::new(125, &["Elisabeth", "Ilsebe"]),
    NameFamily::new(93, &["Katharina"]),
    NameFamily::new(76, &["Ursula"]),
    NameFamily::new(40, &["Adelheid"]),
    NameFamily::new(35, &["Metke"]),
    NameFamily::new(39, &["Ottilia"]),
    NameFamily::new(37, &["Dorothea"]),
    NameFamily::new(33, &["Barbara"]),
    NameFamily::new(20, &["Gertrud"]),
    NameFamily::new(18, &["Emilia"]),
    NameFamily::new(15, &["Agnes"]),
    NameFamily::new(13, &["Christina"]),
    NameFamily::new(12, &["Maria"]),
    NameFamily::new(10, &["Magdalene"]),
    NameFamily::new(8, &["Osanna"]),
    NameFamily::new(5, &["Eva"]),
    NameFamily::new(5, &["Juliana"]),
    NameFamily::new(3, &["Kunneke"]),
];

// No regional surname counts are available: one ticket per selected surname.
pub(super) const SURNAMES: &[NameFamily] = &[
    NameFamily::new(1, &["Bodeker"]),
    NameFamily::new(1, &["Brand"]),
    NameFamily::new(1, &["Bremer"]),
    NameFamily::new(1, &["Broderman"]),
    NameFamily::new(1, &["Garwer"]),
    NameFamily::new(1, &["Gerdes"]),
    NameFamily::new(1, &["Hartman"]),
    NameFamily::new(1, &["Hildebrand"]),
    NameFamily::new(1, &["Holthusen"]),
    NameFamily::new(1, &["Junghe"]),
    NameFamily::new(1, &["Koke"]),
    NameFamily::new(1, &["Korner"]),
    NameFamily::new(1, &["Krantz"]),
    NameFamily::new(1, &["Kremer"]),
    NameFamily::new(1, &["Kroger"]),
    NameFamily::new(1, &["Kruse"]),
    NameFamily::new(1, &["Lange"]),
    NameFamily::new(1, &["Lesemann"]),
    NameFamily::new(1, &["Meiger"]),
    NameFamily::new(1, &["Moller"]),
    NameFamily::new(1, &["Nyebur"]),
    NameFamily::new(1, &["Schomaker"]),
    NameFamily::new(1, &["Schroder"]),
    NameFamily::new(1, &["Schulten"]),
    NameFamily::new(1, &["Smydt"]),
    NameFamily::new(1, &["Thode"]),
    NameFamily::new(1, &["Vaget"]),
    NameFamily::new(1, &["Werkmester"]),
    NameFamily::new(1, &["Wessels"]),
    NameFamily::new(1, &["Westvael"]),
    NameFamily::new(1, &["Witte"]),
    NameFamily::new(1, &["Wreden"]),
    NameFamily::new(1, &["Heller"]),
    NameFamily::new(1, &["Weihrauch"]),
    NameFamily::new(1, &["Weih"]),
    NameFamily::new(1, &["Siebert"]),
    NameFamily::new(1, &["Sittig"]),
    NameFamily::new(1, &["Zeis"]),
    NameFamily::new(1, &["Heimel"]),
];
