//! Authored given-name weights; historical sources and adaptations: `../person_names.md`.
use super::NameFamily;

// Variants share the family weight; no variant receives an independent frequency.
pub(super) const MALE: &[NameFamily] = &[
    NameFamily::new(200, &["Hans", "Johann", "Johannes", "Henne"]),
    NameFamily::new(100, &["Heinrich", "Hinrik", "Heintz", "Hinricus"]),
    NameFamily::new(70, &["Konrad", "Cord", "Conrad", "Contze"]),
    NameFamily::new(60, &["Nikolaus", "Claus", "Nicolaus", "Clawes"]),
    NameFamily::new(60, &["Hermann", "Hermen"]),
    NameFamily::new(50, &["Caspar", "Jasper", "Kaspar"]),
    NameFamily::new(50, &["Peter"]),
    NameFamily::new(45, &["Georg", "Jurgen", "Jörg"]),
    NameFamily::new(40, &["Jacob", "Jakob"]),
    NameFamily::new(40, &["Dietrich", "Diderick", "Dirck"]),
    NameFamily::new(35, &["Martin", "Merten"]),
    NameFamily::new(30, &["Gerd", "Gerhard"]),
    NameFamily::new(30, &["Valentin"]),
    NameFamily::new(25, &["Moritz"]),
    NameFamily::new(25, &["Michael"]),
    NameFamily::new(25, &["Franz", "Frantz"]),
    NameFamily::new(20, &["Bernd", "Bernhard"]),
    NameFamily::new(20, &["Joachim", "Jochim"]),
    NameFamily::new(20, &["Andreas", "Endres"]),
    NameFamily::new(20, &["Matthias", "Mathies", "Mathis"]),
    NameFamily::new(15, &["Paul", "Pawel", "Paulus"]),
    NameFamily::new(15, &["Otto", "Otte"]),
    NameFamily::new(15, &["Albert", "Albrecht"]),
    NameFamily::new(15, &["Christoph", "Stoffel"]),
    NameFamily::new(10, &["Arndt", "Arnold"]),
    NameFamily::new(10, &["Evert", "Eberhard"]),
    NameFamily::new(10, &["Werner", "Wernher"]),
    NameFamily::new(10, &["Willem", "Wilhelm", "Wilhelmus"]),
    NameFamily::new(10, &["Bartholomeus", "Barthel"]),
    NameFamily::new(10, &["Sebastian", "Bastian"]),
    NameFamily::new(10, &["Melchior"]),
    NameFamily::new(5, &["Simon", "Symon"]),
    NameFamily::new(25, &["Friedrich", "Fritz", "Friderich"]),
    NameFamily::new(20, &["Ulrich"]),
    NameFamily::new(20, &["Lorenz", "Laurens"]),
    NameFamily::new(15, &["Leonhard", "Linhart"]),
    NameFamily::new(20, &["Jobst", "Jost"]),
    NameFamily::new(15, &["Wolfgang", "Wolff"]),
    NameFamily::new(15, &["Ludwig", "Ludewig"]),
    NameFamily::new(15, &["Philipp", "Philips"]),
    NameFamily::new(15, &["Stefan", "Steffen"]),
    NameFamily::new(15, &["Thomas"]),
    NameFamily::new(10, &["Adam"]),
    NameFamily::new(10, &["Balthasar"]),
    NameFamily::new(10, &["Benedikt", "Beneken"]),
    NameFamily::new(10, &["Christian", "Karsten", "Kersten"]),
    NameFamily::new(5, &["Augustin"]),
    NameFamily::new(5, &["Gregor"]),
    NameFamily::new(5, &["Hieronymus", "Jeronimus"]),
    NameFamily::new(10, &["Markus", "Marx"]),
    NameFamily::new(5, &["Veit"]),
    NameFamily::new(3, &["Vinzenz"]),
    NameFamily::new(3, &["Wenzel"]),
    NameFamily::new(5, &["Erasmus"]),
    NameFamily::new(3, &["Blasius"]),
    NameFamily::new(3, &["Kilian"]),
    NameFamily::new(3, &["Urban"]),
    NameFamily::new(10, &["Anton", "Antonius"]),
    NameFamily::new(5, &["Bertram"]),
    NameFamily::new(5, &["Hartmann"]),
    NameFamily::new(3, &["Detleff"]),
    NameFamily::new(3, &["Eggert"]),
    NameFamily::new(3, &["Marquard"]),
    NameFamily::new(3, &["Reymer"]),
    NameFamily::new(3, &["Reyneke"]),
    NameFamily::new(5, &["Rudolf", "Rudolff", "Roleff"]),
    NameFamily::new(5, &["Gottfried", "Gotfrid"]),
    NameFamily::new(3, &["Gerlach"]),
    NameFamily::new(3, &["Günther"]),
    NameFamily::new(3, &["Oswald"]),
    NameFamily::new(3, &["Sigmund"]),
    NameFamily::new(3, &["Hildebrand"]),
    NameFamily::new(3, &["Lampert"]),
    NameFamily::new(3, &["Sebald"]),
    NameFamily::new(3, &["Alexander"]),
    NameFamily::new(3, &["Ambrosius"]),
    NameFamily::new(3, &["Clemens"]),
    NameFamily::new(3, &["Dominik"]),
    NameFamily::new(3, &["Fabian"]),
    NameFamily::new(3, &["Gallus"]),
    NameFamily::new(5, &["Lukas"]),
    NameFamily::new(3, &["Sixtus"]),
    NameFamily::new(3, &["Tobias"]),
    NameFamily::new(5, &["Tilmann", "Tile"]),
];

pub(super) const FEMALE: &[NameFamily] = &[
    NameFamily::new(175, &["Margaretha", "Greteke", "Margarete", "Grede"]),
    NameFamily::new(146, &["Anna", "Anneke", "Anne"]),
    NameFamily::new(125, &["Elisabeth", "Ilsebe", "Elsebeth", "Else"]),
    NameFamily::new(93, &["Katharina", "Katherine"]),
    NameFamily::new(76, &["Ursula"]),
    NameFamily::new(40, &["Adelheid", "Alke"]),
    NameFamily::new(35, &["Metke", "Metteke"]),
    NameFamily::new(39, &["Ottilia"]),
    NameFamily::new(37, &["Dorothea"]),
    NameFamily::new(33, &["Barbara"]),
    NameFamily::new(20, &["Gertrud", "Gertraud"]),
    NameFamily::new(18, &["Emilia"]),
    NameFamily::new(15, &["Agnes", "Niesenn"]),
    NameFamily::new(13, &["Christina", "Cristyne"]),
    NameFamily::new(12, &["Maria", "Marie"]),
    NameFamily::new(10, &["Magdalene", "Magdalena"]),
    NameFamily::new(8, &["Osanna"]),
    NameFamily::new(5, &["Eva"]),
    NameFamily::new(5, &["Juliana"]),
    NameFamily::new(3, &["Kunneke", "Kunigunde", "Kungund"]),
    NameFamily::new(10, &["Apollonia"]),
    NameFamily::new(10, &["Klara", "Clare"]),
    NameFamily::new(5, &["Agatha"]),
    NameFamily::new(3, &["Afra"]),
    NameFamily::new(5, &["Cecilia"]),
    NameFamily::new(5, &["Brigitta"]),
    NameFamily::new(5, &["Walburga"]),
    NameFamily::new(5, &["Helena"]),
    NameFamily::new(3, &["Veronica"]),
    NameFamily::new(3, &["Beatrix"]),
    NameFamily::new(3, &["Ida"]),
    NameFamily::new(3, &["Lucia"]),
    NameFamily::new(5, &["Martha"]),
    NameFamily::new(5, &["Mechthild"]),
    NameFamily::new(3, &["Susanna"]),
    NameFamily::new(2, &["Hildegund"]),
    NameFamily::new(5, &["Engel"]),
    NameFamily::new(3, &["Gude"]),
    NameFamily::new(1, &["Gerburg"]),
    NameFamily::new(1, &["Demuth"]),
    NameFamily::new(1, &["Albrade"]),
    NameFamily::new(1, &["Emeludt"]),
    NameFamily::new(1, &["Liepmayt"]),
    NameFamily::new(1, &["Beken"]),
    NameFamily::new(1, &["Geken"]),
    NameFamily::new(2, &["Geseken"]),
    NameFamily::new(2, &["Hille"]),
    NameFamily::new(1, &["Sileken"]),
    NameFamily::new(1, &["Tibbeken"]),
    NameFamily::new(1, &["Wibeke"]),
    NameFamily::new(1, &["Wobbeke"]),
    NameFamily::new(1, &["Wommelken"]),
    NameFamily::new(2, &["Irmele"]),
    NameFamily::new(1, &["Fye"]),
    NameFamily::new(1, &["Meckil"]),
    NameFamily::new(1, &["Bechte"]),
    NameFamily::new(1, &["Gele"]),
    NameFamily::new(1, &["Lype"]),
    NameFamily::new(1, &["Ayla"]),
    NameFamily::new(1, &["Bytzel"]),
    NameFamily::new(1, &["Hette"]),
    NameFamily::new(1, &["Contzel"]),
    NameFamily::new(1, &["Syele"]),
];
