[package]
name = "fabelgeist-cloth"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"
repository = "https://github.com/adventure-simulator-group/fabelgeist"

[dependencies]
fabelgeist-shell = { "path" = "../fabelgeist-shell" }
fabelgeist-gpu = { "default-features" = false, "path" = "../fabelgeist-gpu" }
fabelgeist-compute = { "path" = "../fabelgeist-compute" }
fabelgeist-math = { "default-features" = false, "path" = "../fabelgeist-math" }
anyhow = { "version" = "1.0" }

[dev-dependencies]
fabelgeist-xpbd = { "path" = "../fabelgeist-xpbd" }
fabelgeist-physics = { "path" = "../fabelgeist-physics" }
tokio = { "version" = "1", "features" = ["full"] }

[lints]
workspace = true
