//! Authored 1544 Central German building catchments and siting preferences.
//!
//! Historical typology and evidence boundaries are recorded in
//! research/city-building-variety-1544.md. Its sources support the inventory and
//! siting rules; the capacity ranges remain gameplay tuning, not census values.
use super::CapacityRange;
use crate::{SettlementService, StockCategory};
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Ord, PartialOrd, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BuildingUse {
    Dwelling,
    ParishChurch,
    Inn,
    GeneralShop,
    MarketHall,
    Smithy,
    Weaponsmith,
    Armorer,
    Tailor,
    Herbalist,
    Bookshop,
    Bakehouse,
    Brewery,
    Malthouse,
    Butcher,
    Stable,
    Barn,
    Granary,
    HorseMill,
    Cooper,
    Carpenter,
    Wheelwright,
    Cobbler,
    Weaver,
    Tannery,
    Dyer,
    Ropemaker,
    Chandler,
    Potter,
    Stonecutter,
    TimberYard,
    Warehouse,
    WoadStore,
    Fishmonger,
    TownHall,
    WeighHouse,
    Guildhall,
    Hospital,
    Bathhouse,
    School,
    Apothecary,
    PrintingHouse,
    Guardhouse,
    Prison,
    Rectory,
    WaterMill,
    FullingMill,
    PaperMill,
    Sawmill,
    Windmill,
    Cathedral,
    Monastery,
    University,
    Mint,
    CustomsHouse,
    Synagogue,
    Chapel,
    Manor,
    Castle,
    Arsenal,
    SaltWorks,
    Smelter,
    AssayHouse,
    Brickworks,
    Glassworks,
    ExecutionerHouse,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BuildingDistrict {
    Market,
    Neighbourhood,
    Craft,
    Edge,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BuildingEligibility {
    EverySettlement,
    Service(SettlementService),
    Specialization(StockCategory),
    /// Requires dated local evidence, or a surveyed power/water site.
    HistoricalEvidence,
}

#[derive(Clone, Copy, Debug)]
pub struct BuildingDefinition {
    pub label: &'static str,
    pub minimum_population: u32,
    pub capacity: CapacityRange,
    pub eligibility: BuildingEligibility,
    pub district: BuildingDistrict,
    pub singleton: bool,
}

impl BuildingUse {
    pub const ALL: [Self; 66] = [
        Self::Dwelling,
        Self::ParishChurch,
        Self::Inn,
        Self::GeneralShop,
        Self::MarketHall,
        Self::Smithy,
        Self::Weaponsmith,
        Self::Armorer,
        Self::Tailor,
        Self::Herbalist,
        Self::Bookshop,
        Self::Bakehouse,
        Self::Brewery,
        Self::Malthouse,
        Self::Butcher,
        Self::Stable,
        Self::Barn,
        Self::Granary,
        Self::HorseMill,
        Self::Cooper,
        Self::Carpenter,
        Self::Wheelwright,
        Self::Cobbler,
        Self::Weaver,
        Self::Tannery,
        Self::Dyer,
        Self::Ropemaker,
        Self::Chandler,
        Self::Potter,
        Self::Stonecutter,
        Self::TimberYard,
        Self::Warehouse,
        Self::WoadStore,
        Self::Fishmonger,
        Self::TownHall,
        Self::WeighHouse,
        Self::Guildhall,
        Self::Hospital,
        Self::Bathhouse,
        Self::School,
        Self::Apothecary,
        Self::PrintingHouse,
        Self::Guardhouse,
        Self::Prison,
        Self::Rectory,
        Self::WaterMill,
        Self::FullingMill,
        Self::PaperMill,
        Self::Sawmill,
        Self::Windmill,
        Self::Cathedral,
        Self::Monastery,
        Self::University,
        Self::Mint,
        Self::CustomsHouse,
        Self::Synagogue,
        Self::Chapel,
        Self::Manor,
        Self::Castle,
        Self::Arsenal,
        Self::SaltWorks,
        Self::Smelter,
        Self::AssayHouse,
        Self::Brickworks,
        Self::Glassworks,
        Self::ExecutionerHouse,
    ];

    pub const fn definition(self) -> BuildingDefinition {
        use BuildingDistrict::*;
        use BuildingEligibility::*;
        use SettlementService as Service;
        use StockCategory as Stock;
        let (label, minimum_population, minimum, maximum, eligibility, district, singleton) =
            match self {
                Self::Dwelling => (
                    "Dwelling",
                    1,
                    6,
                    30,
                    HistoricalEvidence,
                    Neighbourhood,
                    false,
                ),
                Self::ParishChurch => (
                    "Parish church",
                    250,
                    100,
                    500,
                    Service(Service::Temple),
                    Neighbourhood,
                    false,
                ),
                Self::Inn => ("Inn", 1, 300, 900, Service(Service::Inn), Market, false),
                Self::GeneralShop => (
                    "General shop",
                    1,
                    250,
                    600,
                    Service(Service::GeneralStore),
                    Market,
                    false,
                ),
                Self::MarketHall => (
                    "Market hall",
                    800,
                    3000,
                    6000,
                    Service(Service::Market),
                    Market,
                    false,
                ),
                Self::Smithy => (
                    "General smithy",
                    1,
                    600,
                    1200,
                    Service(Service::GeneralBlacksmith),
                    Edge,
                    false,
                ),
                Self::Weaponsmith => (
                    "Weaponsmith",
                    1,
                    1800,
                    4000,
                    Service(Service::Weaponsmith),
                    Craft,
                    false,
                ),
                Self::Armorer => (
                    "Armorer",
                    1,
                    2000,
                    4500,
                    Service(Service::Armorer),
                    Craft,
                    false,
                ),
                Self::Tailor => (
                    "Tailor",
                    1,
                    400,
                    900,
                    Service(Service::Tailor),
                    Craft,
                    false,
                ),
                Self::Herbalist => (
                    "Herbalist",
                    1,
                    1200,
                    2500,
                    Service(Service::Herbalist),
                    Neighbourhood,
                    false,
                ),
                Self::Bookshop => (
                    "Bookshop and binder",
                    1,
                    3000,
                    7000,
                    Service(Service::Bookstore),
                    Market,
                    false,
                ),
                Self::Bakehouse => (
                    "Bakehouse",
                    120,
                    250,
                    600,
                    EverySettlement,
                    Neighbourhood,
                    false,
                ),
                Self::Brewery => ("Brew house", 300, 700, 1600, EverySettlement, Craft, false),
                Self::Malthouse => ("Malt house", 800, 2000, 4000, EverySettlement, Edge, false),
                Self::Butcher => ("Butcher", 400, 600, 1300, EverySettlement, Market, false),
                Self::Stable => (
                    "Stable and cart shed",
                    80,
                    400,
                    1000,
                    EverySettlement,
                    Edge,
                    false,
                ),
                Self::Barn => (
                    "Barn and threshing floor",
                    1,
                    250,
                    700,
                    EverySettlement,
                    Edge,
                    false,
                ),
                Self::Granary => ("Grain store", 120, 800, 2000, EverySettlement, Edge, false),
                Self::HorseMill => (
                    "Horse-powered grain mill",
                    150,
                    800,
                    1800,
                    EverySettlement,
                    Edge,
                    false,
                ),
                Self::Cooper => ("Cooper", 400, 1000, 2200, EverySettlement, Craft, false),
                Self::Carpenter => (
                    "Carpenter and joiner",
                    200,
                    600,
                    1500,
                    EverySettlement,
                    Craft,
                    false,
                ),
                Self::Wheelwright => ("Wheelwright", 350, 1000, 2500, EverySettlement, Edge, false),
                Self::Cobbler => (
                    "Shoemaker and cobbler",
                    250,
                    500,
                    1100,
                    EverySettlement,
                    Craft,
                    false,
                ),
                Self::Weaver => (
                    "Weaver",
                    250,
                    500,
                    1300,
                    Specialization(Stock::Cloth),
                    Craft,
                    false,
                ),
                Self::Tannery => (
                    "Tannery",
                    500,
                    1500,
                    3500,
                    Specialization(Stock::Hides),
                    Edge,
                    false,
                ),
                Self::Dyer => (
                    "Dye house",
                    800,
                    2000,
                    4500,
                    Specialization(Stock::Cloth),
                    Edge,
                    false,
                ),
                Self::Ropemaker => ("Ropemaker", 600, 1800, 4000, EverySettlement, Edge, false),
                Self::Chandler => ("Chandler", 600, 1500, 3000, EverySettlement, Craft, false),
                Self::Potter => (
                    "Potter and kiln house",
                    200,
                    1200,
                    2800,
                    Specialization(Stock::Pottery),
                    Edge,
                    false,
                ),
                Self::Stonecutter => (
                    "Stonemason lodge",
                    500,
                    2000,
                    5000,
                    Specialization(Stock::Stone),
                    Edge,
                    false,
                ),
                Self::TimberYard => (
                    "Timber yard and saw shed",
                    150,
                    1800,
                    4000,
                    Specialization(Stock::Timber),
                    Edge,
                    false,
                ),
                Self::Warehouse => (
                    "Merchant warehouse",
                    700,
                    1800,
                    4000,
                    Service(Service::Market),
                    Market,
                    false,
                ),
                Self::WoadStore => (
                    "Woad drying and storage house",
                    600,
                    2500,
                    6000,
                    HistoricalEvidence,
                    Craft,
                    false,
                ),
                Self::Fishmonger => (
                    "Fishmonger",
                    300,
                    900,
                    2200,
                    Specialization(Stock::Fish),
                    Market,
                    false,
                ),
                Self::TownHall => (
                    "Town hall",
                    1500,
                    1000,
                    1000,
                    Service(Service::Market),
                    Market,
                    true,
                ),
                Self::WeighHouse => (
                    "Weigh house",
                    2000,
                    1000,
                    1000,
                    Service(Service::Market),
                    Market,
                    true,
                ),
                Self::Guildhall => (
                    "Guildhall",
                    2500,
                    3000,
                    7000,
                    Service(Service::Market),
                    Craft,
                    false,
                ),
                Self::Hospital => (
                    "Hospital and almshouse",
                    1500,
                    3000,
                    7000,
                    EverySettlement,
                    Neighbourhood,
                    false,
                ),
                Self::Bathhouse => (
                    "Bathhouse",
                    1000,
                    1800,
                    4000,
                    EverySettlement,
                    Neighbourhood,
                    false,
                ),
                Self::School => (
                    "Parish school",
                    800,
                    1200,
                    2800,
                    Service(Service::Temple),
                    Neighbourhood,
                    false,
                ),
                Self::Apothecary => (
                    "Apothecary",
                    2500,
                    4000,
                    9000,
                    Service(Service::Herbalist),
                    Market,
                    false,
                ),
                Self::PrintingHouse => (
                    "Printing house",
                    3000,
                    5000,
                    12000,
                    Service(Service::Bookstore),
                    Craft,
                    false,
                ),
                Self::Guardhouse => (
                    "Watch house",
                    1200,
                    2000,
                    4500,
                    EverySettlement,
                    Market,
                    false,
                ),
                Self::Prison => (
                    "Town prison",
                    2000,
                    1000,
                    1000,
                    Service(Service::Market),
                    Market,
                    true,
                ),
                Self::Rectory => (
                    "Rectory",
                    250,
                    800,
                    1800,
                    Service(Service::Temple),
                    Neighbourhood,
                    false,
                ),
                Self::WaterMill => (
                    "Water-powered grain mill",
                    1,
                    800,
                    2000,
                    HistoricalEvidence,
                    Edge,
                    false,
                ),
                Self::FullingMill => (
                    "Fulling mill",
                    1,
                    2000,
                    5000,
                    HistoricalEvidence,
                    Edge,
                    false,
                ),
                Self::PaperMill => (
                    "Paper mill",
                    1,
                    5000,
                    12000,
                    HistoricalEvidence,
                    Edge,
                    false,
                ),
                Self::Sawmill => (
                    "Water-powered sawmill",
                    1,
                    2500,
                    6000,
                    HistoricalEvidence,
                    Edge,
                    false,
                ),
                Self::Windmill => (
                    "Post windmill",
                    1,
                    800,
                    2000,
                    HistoricalEvidence,
                    Edge,
                    false,
                ),
                Self::Cathedral => (
                    "Cathedral or collegiate church",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Neighbourhood,
                    true,
                ),
                Self::Monastery => (
                    "Monastery or convent range",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Neighbourhood,
                    true,
                ),
                Self::University => (
                    "University college",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Neighbourhood,
                    true,
                ),
                Self::Mint => ("Mint", 1, 1000, 1000, HistoricalEvidence, Market, true),
                Self::CustomsHouse => (
                    "Customs house",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Market,
                    true,
                ),
                Self::Synagogue => (
                    "Synagogue",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Neighbourhood,
                    true,
                ),
                Self::Chapel => (
                    "Chapel",
                    1,
                    100,
                    300,
                    HistoricalEvidence,
                    Neighbourhood,
                    false,
                ),
                Self::Manor => (
                    "Manor house",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Neighbourhood,
                    true,
                ),
                Self::Castle => (
                    "Castle or keep",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Edge,
                    true,
                ),
                Self::Arsenal => ("Arsenal", 1, 1000, 1000, HistoricalEvidence, Edge, true),
                Self::SaltWorks => (
                    "Salt boiling house",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Edge,
                    true,
                ),
                Self::Smelter => (
                    "Ore smelting house",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Edge,
                    true,
                ),
                Self::AssayHouse => (
                    "Assay house",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Market,
                    true,
                ),
                Self::Brickworks => (
                    "Brick and tile kiln house",
                    1,
                    1500,
                    4000,
                    HistoricalEvidence,
                    Edge,
                    false,
                ),
                Self::Glassworks => ("Glass house", 1, 1000, 1000, HistoricalEvidence, Edge, true),
                Self::ExecutionerHouse => (
                    "Executioner and knacker dwelling",
                    1,
                    1000,
                    1000,
                    HistoricalEvidence,
                    Edge,
                    true,
                ),
            };
        BuildingDefinition {
            label,
            minimum_population,
            capacity: CapacityRange::new(minimum, maximum),
            eligibility,
            district,
            singleton,
        }
    }
}
