//! Authored 1544 Central German building catchments and siting preferences.
use super::{BuildingDemandPolicy, CapacityRange};
use crate::{SettlementService, StockCategory};
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Ord, PartialOrd, Serialize, Deserialize)]
#[cfg_attr(feature = "spacetimedb", derive(spacetimedb::SpacetimeType))]
#[serde(rename_all = "snake_case")]
pub enum BuildingUse {
    Dwelling,
    ParishChurch,
    Inn,
    GeneralShop,
    MarketHall,
    Smithy,
    Weaponsmith,
    Armorer,
    Tailor,
    Herbalist,
    Bookshop,
    Bakehouse,
    Brewery,
    Malthouse,
    Butcher,
    Stable,
    Barn,
    Granary,
    HorseMill,
    Cooper,
    Carpenter,
    Wheelwright,
    Cobbler,
    Weaver,
    Tannery,
    Dyer,
    Ropemaker,
    Chandler,
    Potter,
    Stonecutter,
    TimberYard,
    Warehouse,
    WoadStore,
    Fishmonger,
    TownHall,
    WeighHouse,
    Guildhall,
    Hospital,
    Bathhouse,
    School,
    Apothecary,
    PrintingHouse,
    Guardhouse,
    Prison,
    Rectory,
    WaterMill,
    FullingMill,
    PaperMill,
    Sawmill,
    Windmill,
    Cathedral,
    Monastery,
    University,
    Mint,
    CustomsHouse,
    Synagogue,
    Chapel,
    Manor,
    Castle,
    Arsenal,
    SaltWorks,
    Smelter,
    AssayHouse,
    Brickworks,
    Glassworks,
    ExecutionerHouse,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BuildingDistrict {
    Market,
    Neighbourhood,
    Craft,
    Edge,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BuildingEligibility {
    EverySettlement,
    Service(SettlementService),
    Specialization(StockCategory),
    /// Requires dated local evidence, or a surveyed power/water site.
    HistoricalEvidence,
}

#[derive(Clone, Copy, Debug)]
pub struct BuildingDefinition {
    pub label: &'static str,
    pub minimum_population: u32,
    pub demand: BuildingDemandPolicy,
    pub eligibility: BuildingEligibility,
    pub district: BuildingDistrict,
}

impl BuildingUse {
    pub const ALL: [Self; 66] = [
        Self::Dwelling,
        Self::ParishChurch,
        Self::Inn,
        Self::GeneralShop,
        Self::MarketHall,
        Self::Smithy,
        Self::Weaponsmith,
        Self::Armorer,
        Self::Tailor,
        Self::Herbalist,
        Self::Bookshop,
        Self::Bakehouse,
        Self::Brewery,
        Self::Malthouse,
        Self::Butcher,
        Self::Stable,
        Self::Barn,
        Self::Granary,
        Self::HorseMill,
        Self::Cooper,
        Self::Carpenter,
        Self::Wheelwright,
        Self::Cobbler,
        Self::Weaver,
        Self::Tannery,
        Self::Dyer,
        Self::Ropemaker,
        Self::Chandler,
        Self::Potter,
        Self::Stonecutter,
        Self::TimberYard,
        Self::Warehouse,
        Self::WoadStore,
        Self::Fishmonger,
        Self::TownHall,
        Self::WeighHouse,
        Self::Guildhall,
        Self::Hospital,
        Self::Bathhouse,
        Self::School,
        Self::Apothecary,
        Self::PrintingHouse,
        Self::Guardhouse,
        Self::Prison,
        Self::Rectory,
        Self::WaterMill,
        Self::FullingMill,
        Self::PaperMill,
        Self::Sawmill,
        Self::Windmill,
        Self::Cathedral,
        Self::Monastery,
        Self::University,
        Self::Mint,
        Self::CustomsHouse,
        Self::Synagogue,
        Self::Chapel,
        Self::Manor,
        Self::Castle,
        Self::Arsenal,
        Self::SaltWorks,
        Self::Smelter,
        Self::AssayHouse,
        Self::Brickworks,
        Self::Glassworks,
        Self::ExecutionerHouse,
    ];

    pub const fn definition(self) -> BuildingDefinition {
        use BuildingDistrict::*;
        use BuildingEligibility::*;
        use SettlementService as Service;
        use StockCategory as Stock;
        let (label, minimum_population, demand, eligibility, district) = match self {
            Self::Dwelling => (
                "Dwelling",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Neighbourhood,
            ),
            Self::ParishChurch => (
                "Parish church",
                250,
                BuildingDemandPolicy::ParishChurch,
                Service(Service::Temple),
                Neighbourhood,
            ),
            Self::Inn => (
                "Inn",
                1,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(300, 900)),
                Service(Service::Inn),
                Market,
            ),
            Self::GeneralShop => (
                "General shop",
                1,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(250, 600)),
                Service(Service::GeneralStore),
                Market,
            ),
            Self::MarketHall => (
                "Market hall",
                800,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(3000, 6000)),
                Service(Service::Market),
                Market,
            ),
            Self::Smithy => (
                "General smithy",
                1,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(600, 1200)),
                Service(Service::GeneralBlacksmith),
                Edge,
            ),
            Self::Weaponsmith => (
                "Weaponsmith",
                1,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1800, 4000)),
                Service(Service::Weaponsmith),
                Craft,
            ),
            Self::Armorer => (
                "Armorer",
                1,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(2000, 4500)),
                Service(Service::Armorer),
                Craft,
            ),
            Self::Tailor => (
                "Tailor",
                1,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(400, 900)),
                Service(Service::Tailor),
                Craft,
            ),
            Self::Herbalist => (
                "Herbalist",
                1,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1200, 2500)),
                Service(Service::Herbalist),
                Neighbourhood,
            ),
            Self::Bookshop => (
                "Bookshop and binder",
                1,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(3000, 7000)),
                Service(Service::Bookstore),
                Market,
            ),
            Self::Bakehouse => (
                "Bakehouse",
                120,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(250, 600)),
                EverySettlement,
                Neighbourhood,
            ),
            Self::Brewery => (
                "Brew house",
                300,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(700, 1600)),
                EverySettlement,
                Craft,
            ),
            Self::Malthouse => (
                "Malt house",
                800,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(2000, 4000)),
                EverySettlement,
                Edge,
            ),
            Self::Butcher => (
                "Butcher",
                400,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(600, 1300)),
                EverySettlement,
                Market,
            ),
            Self::Stable => (
                "Stable and cart shed",
                80,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(400, 1000)),
                EverySettlement,
                Edge,
            ),
            Self::Barn => (
                "Barn and threshing floor",
                1,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(250, 700)),
                EverySettlement,
                Edge,
            ),
            Self::Granary => (
                "Grain store",
                120,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(800, 2000)),
                EverySettlement,
                Edge,
            ),
            Self::HorseMill => (
                "Horse-powered grain mill",
                150,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(800, 1800)),
                EverySettlement,
                Edge,
            ),
            Self::Cooper => (
                "Cooper",
                400,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1000, 2200)),
                EverySettlement,
                Craft,
            ),
            Self::Carpenter => (
                "Carpenter and joiner",
                200,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(600, 1500)),
                EverySettlement,
                Craft,
            ),
            Self::Wheelwright => (
                "Wheelwright",
                350,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1000, 2500)),
                EverySettlement,
                Edge,
            ),
            Self::Cobbler => (
                "Shoemaker and cobbler",
                250,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(500, 1100)),
                EverySettlement,
                Craft,
            ),
            Self::Weaver => (
                "Weaver",
                250,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(500, 1300)),
                Specialization(Stock::Cloth),
                Craft,
            ),
            Self::Tannery => (
                "Tannery",
                500,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1500, 3500)),
                Specialization(Stock::Hides),
                Edge,
            ),
            Self::Dyer => (
                "Dye house",
                800,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(2000, 4500)),
                Specialization(Stock::Cloth),
                Edge,
            ),
            Self::Ropemaker => (
                "Ropemaker",
                600,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1800, 4000)),
                EverySettlement,
                Edge,
            ),
            Self::Chandler => (
                "Chandler",
                600,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1500, 3000)),
                EverySettlement,
                Craft,
            ),
            Self::Potter => (
                "Potter and kiln house",
                200,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1200, 2800)),
                Specialization(Stock::Pottery),
                Edge,
            ),
            Self::Stonecutter => (
                "Stonemason lodge",
                500,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(2000, 5000)),
                Specialization(Stock::Stone),
                Edge,
            ),
            Self::TimberYard => (
                "Timber yard and saw shed",
                150,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1800, 4000)),
                Specialization(Stock::Timber),
                Edge,
            ),
            Self::Warehouse => (
                "Merchant warehouse",
                700,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1800, 4000)),
                Service(Service::Market),
                Market,
            ),
            Self::WoadStore => (
                "Woad drying and storage house",
                600,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Craft,
            ),
            Self::Fishmonger => (
                "Fishmonger",
                300,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(900, 2200)),
                Specialization(Stock::Fish),
                Market,
            ),
            Self::TownHall => (
                "Town hall",
                1500,
                BuildingDemandPolicy::SettlementInstitution(super::CivicInstitution::TownHall),
                Service(Service::Market),
                Market,
            ),
            Self::WeighHouse => (
                "Weigh house",
                2000,
                BuildingDemandPolicy::SettlementInstitution(super::CivicInstitution::WeighHouse),
                Service(Service::Market),
                Market,
            ),
            Self::Guildhall => (
                "Guildhall",
                2500,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(3000, 7000)),
                Service(Service::Market),
                Craft,
            ),
            Self::Hospital => (
                "Hospital and almshouse",
                1500,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(3000, 7000)),
                EverySettlement,
                Neighbourhood,
            ),
            Self::Bathhouse => (
                "Bathhouse",
                1000,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(1800, 4000)),
                EverySettlement,
                Neighbourhood,
            ),
            Self::School => (
                "Town school",
                800,
                BuildingDemandPolicy::ParishSchool,
                Service(Service::Temple),
                Neighbourhood,
            ),
            Self::Apothecary => (
                "Apothecary",
                2500,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(4000, 9000)),
                Service(Service::Herbalist),
                Market,
            ),
            Self::PrintingHouse => (
                "Printing house",
                3000,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(5000, 12000)),
                Service(Service::Bookstore),
                Craft,
            ),
            Self::Guardhouse => (
                "Watch house",
                1200,
                BuildingDemandPolicy::ServiceCatchment(CapacityRange::new(2000, 4500)),
                EverySettlement,
                Market,
            ),
            Self::Prison => (
                "Town prison",
                2000,
                BuildingDemandPolicy::SettlementInstitution(super::CivicInstitution::Prison),
                Service(Service::Market),
                Market,
            ),
            Self::Rectory => (
                "Rectory",
                250,
                BuildingDemandPolicy::ParishResidence,
                Service(Service::Temple),
                Neighbourhood,
            ),
            Self::WaterMill => (
                "Water-powered grain mill",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::FullingMill => (
                "Fulling mill",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::PaperMill => (
                "Paper mill",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::Sawmill => (
                "Water-powered sawmill",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::Windmill => (
                "Post windmill",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::Cathedral => (
                "Cathedral or collegiate church",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Neighbourhood,
            ),
            Self::Monastery => (
                "Monastery or convent range",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Neighbourhood,
            ),
            Self::University => (
                "University college",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Neighbourhood,
            ),
            Self::Mint => (
                "Mint",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Market,
            ),
            Self::CustomsHouse => (
                "Customs house",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Market,
            ),
            Self::Synagogue => (
                "Synagogue",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Neighbourhood,
            ),
            Self::Chapel => (
                "Chapel",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Neighbourhood,
            ),
            Self::Manor => (
                "Manor house",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Neighbourhood,
            ),
            Self::Castle => (
                "Castle or keep",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::Arsenal => (
                "Arsenal",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::SaltWorks => (
                "Salt boiling house",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::Smelter => (
                "Ore smelting house",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::AssayHouse => (
                "Assay house",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Market,
            ),
            Self::Brickworks => (
                "Brick and tile kiln house",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::Glassworks => (
                "Glass house",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
            Self::ExecutionerHouse => (
                "Executioner and knacker dwelling",
                1,
                BuildingDemandPolicy::EvidenceOnly,
                HistoricalEvidence,
                Edge,
            ),
        };
        BuildingDefinition {
            label,
            minimum_population,
            demand,
            eligibility,
            district,
        }
    }
}
