pub mod activity;
pub mod alcohol;
pub mod attribute;
pub mod autopsy;
pub mod autoresolve;
pub mod battle_rewards;
pub mod bestiary;
pub mod body;
pub mod book;
pub mod capability;
pub mod case;
pub mod combat;
pub mod composite;
pub mod courtship;
pub mod developer_quest;
pub mod disease;
pub mod durability;
pub mod encounter;
pub mod equipment;
pub mod errantry;
pub mod essential;
pub mod filth;
pub mod food;
pub mod foraging;
pub mod herbalism;
pub mod inventory_measurement;
pub mod investigation;
pub mod investigation_action;
pub mod item_catalog;
pub mod item_catalog_schema;
#[cfg(test)]
mod item_catalog_validation;
pub mod item_references;
pub mod leadership;
pub mod life_simulation;
pub mod local_problem;
pub mod mission;
pub mod morale;
pub mod npc_policy;
pub mod organization;
#[cfg(test)]
mod organization_catalog_validation;
pub mod physiology;
pub mod provisioning;
pub mod quest_catalog;
mod quest_catalog_validation;
pub mod quest_generation;
pub mod reputation;
pub mod road_encounter_catalog;
pub mod settlement_economy;
pub mod settlement_population;
pub mod simulation_security;
pub mod skill;
pub mod social;
pub mod starting_character;
pub mod strategic_currency;
pub mod strategic_economy;
pub mod strategic_inventory;
pub mod strategic_schedule;
pub mod strategic_state;
pub mod strategic_time;
#[doc(hidden)]
pub mod stub;
pub mod surgery;
pub mod survival;
pub mod systemic_character;
pub mod threat_escalation;
mod threat_escalation_limits;
pub mod weather;

pub mod prelude {
    pub use crate::activity::*;
    pub use crate::attribute::*;
    pub use crate::autoresolve::*;
    pub use crate::bestiary::*;
    pub use crate::body::*;
    pub use crate::capability::*;
    pub use crate::combat::*;
    pub use crate::composite::PlayerInfo;
    pub use crate::disease::*;
    pub use crate::durability::*;
    pub use crate::equipment::*;
    pub use crate::essential::*;
    pub use crate::investigation::*;
    pub use crate::investigation_action::*;
    pub use crate::mission::*;
    pub use crate::morale::*;
    pub use crate::organization::*;
    pub use crate::provisioning::*;
    pub use crate::skill::*;
    pub use crate::social::*;
    pub use crate::strategic_economy::*;
    pub use crate::strategic_schedule::*;
    pub use crate::strategic_time::*;
    pub use crate::survival::*;
    pub use crate::weather::*;
}
