[package]
name = "fabelgeist-math"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"
repository = "https://github.com/adventure-simulator-group/fabelgeist"

[dependencies]
serde = { "version" = "1", "features" = ["derive"] }
bytemuck = { "version" = "1.16", "features" = ["derive"] }
wgpu = { "version" = "30.0", "default-features" = false, "features" = ["webgl", "webgpu", "wgsl", "vulkan", "metal", "glsl"], "optional" = true }

[features]
default = []

[lints]
workspace = true
