[package]
name = "adventuresim-armor-model"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/adventure-simulator-group/fabelgeist"
license = "GPL-3.0"

[dependencies]
blake3 = { workspace = true }
bytemuck = "1.16"
fabelgeist-compute = { path = "../fabelgeist-compute" }
fabelgeist-gpu = { path = "../fabelgeist-gpu", default-features = false }
pollster = "0.4"
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
spade = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
