use adventuresim_strategic_sim::*;
use clap::{Parser, Subcommand, ValueEnum};
use fabelgeist_determinism::Seed;
use std::{
    fs,
    io::Read,
    path::{Path, PathBuf},
};

#[derive(Parser)]
#[command(about = "Deterministic strategic NPC balance simulator")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Analyze generated quest content through an offline observer-safe projection.
    QuestAnalyze {
        #[arg(long, value_enum, default_value_t = EvalPolicyArg::Mock)]
        policy: EvalPolicyArg,
        #[arg(long, default_value_t = fabelgeist_determinism::Seed::from_u64(41))]
        seed: Seed,
        #[arg(long, default_value_t = 4)]
        cases_per_template: u32,
        #[arg(long)]
        public_output: PathBuf,
        #[arg(long)]
        developer_output: PathBuf,
        #[arg(long)]
        stories_output: PathBuf,
        #[arg(long, default_value_t = false)]
        overwrite: bool,
        #[arg(long)]
        endpoint: Option<String>,
        #[arg(long, default_value = "gpt-4.1-nano")]
        model: String,
        #[arg(long, default_value = "OPENAI_API_KEY")]
        api_key_env: String,
        #[arg(long, default_value_t = false)]
        allow_network: bool,
    },
    /// Replay a review-approved deterministic quest-analysis fixture.
    QuestAnalyzeReplay {
        #[arg(long)]
        fixture: PathBuf,
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Emit a reviewable fixture candidate from a bounded non-solving run.
    QuestAnalyzePromote {
        #[arg(long, default_value_t = fabelgeist_determinism::Seed::from_u64(41))]
        seed: Seed,
        #[arg(long, value_enum, default_value_t = EvalFamilyArg::RecurringDepredation)]
        family: EvalFamilyArg,
        #[arg(long, default_value_t = 1)]
        max_steps: u32,
        #[arg(long)]
        output: PathBuf,
        #[arg(long, default_value_t = false)]
        overwrite: bool,
    },
    /// Generate profiles and run canonical settlement downtime.
    Run {
        #[arg(long)]
        config: Option<PathBuf>,
        #[arg(long)]
        output: Option<PathBuf>,
        #[arg(long, default_value_t = fabelgeist_determinism::Seed::from_u64(1))]
        seed: Seed,
        #[arg(long, default_value_t = 100)]
        population: u32,
        #[arg(long, default_value_t = DEFAULT_SIMULATION_DAYS)]
        days: u32,
    },
    /// Rerun a report's recorded manifest and verify its digest.
    Replay {
        #[arg(long)]
        report: PathBuf,
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Run a matched labor/thievery pair with common initial circumstances.
    Matched {
        #[arg(long, default_value_t = fabelgeist_determinism::Seed::from_u64(1))]
        seed: Seed,
        #[arg(long, default_value_t = DEFAULT_MATCHED_DAYS)]
        days: u32,
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Exercise the complete strategic loop against an owned disposable local database.
    CoreLoop {
        #[arg(long, default_value = "http://127.0.0.1:3000")]
        host: String,
        /// Must be a unique `adventuresim-sim-*` database published for this run.
        #[arg(long)]
        database: String,
        #[arg(long, default_value_t = fabelgeist_determinism::Seed::from_u64(1))]
        seed: Seed,
        #[arg(long, default_value_t = 2)]
        population: u32,
        #[arg(long, default_value_t = 1)]
        cycles: u32,
        #[arg(long, default_value_t = DEFAULT_CORE_LOOP_DURATION_DAYS)]
        duration_days: u32,
        #[arg(long, default_value_t = 2)]
        party_size: u32,
        /// Unpredictable nonce generated by the owning launcher.
        #[arg(long)]
        run_nonce: String,
        /// Disease used by the disposable medical scenario fixture.
        #[arg(long, default_value = "influenza")]
        fixture_disease: String,
        /// Require a completed authoritative world import and skip fixture seeding.
        #[arg(long, default_value_t = false)]
        imported_world: bool,
        /// Install and require deterministic direct and generated quest coverage.
        #[arg(long, default_value_t = false)]
        require_quest_coverage: bool,
        /// Exact manifest digest read from the verified pinned world artifact.
        #[arg(long, requires = "imported_world")]
        expected_world_manifest_digest: Option<String>,
        #[arg(long)]
        output: Option<PathBuf>,
        /// Public-safe diagnostic JSON created only if the core loop fails.
        #[arg(long)]
        failure_output: Option<PathBuf>,
    },
    /// Run the deterministic offline lifecycle acceptance scenario.
    Lifecycle {
        /// New directory which will receive immutable whole/daily reports.
        #[arg(long)]
        output_dir: PathBuf,
        #[arg(long, default_value_t = fabelgeist_determinism::Seed::from_u64(42))]
        seed: Seed,
    },
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum EvalPolicyArg {
    Scripted,
    Mock,
    Openai,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum EvalFamilyArg {
    RecurringDepredation,
    DisappearanceOrLoss,
    Outbreak,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();
    let command = match cli.command {
        Command::QuestAnalyze {
            policy,
            seed,
            cases_per_template,
            public_output,
            developer_output,
            stories_output,
            overwrite,
            endpoint,
            model,
            api_key_env,
            allow_network,
        } => {
            validate_distinct_output_paths(&[&public_output, &developer_output, &stories_output])?;
            if !overwrite
                && [&public_output, &developer_output, &stories_output]
                    .iter()
                    .any(|path| path.exists())
            {
                return Err(
                    "one or more quest analysis outputs already exist; pass --overwrite explicitly"
                        .into(),
                );
            }
            let mut policy: Box<dyn QuestPolicy> = match policy {
                EvalPolicyArg::Scripted => Box::new(ScriptedPolicy::default()),
                EvalPolicyArg::Mock => Box::new(MockLlmPolicy),
                EvalPolicyArg::Openai => Box::new(OpenAiCompatiblePolicy::new(ProviderConfig {
                    endpoint: endpoint.unwrap_or_else(|| ProviderConfig::default().endpoint),
                    model,
                    api_key_env,
                    allow_network,
                    ..ProviderConfig::default()
                })?),
            };
            let case_count = cases_per_template
                .checked_mul(3)
                .ok_or("case count overflow")?;
            let limits = EvalLimits {
                max_cases: case_count,
                ..EvalLimits::default()
            };
            let bundle = evaluate_cases(
                &golden_suite(seed, cases_per_template),
                policy.as_mut(),
                &limits,
            )?;
            write_output(&public_output, &bundle.artifacts.public_json, overwrite)?;
            write_output(
                &developer_output,
                &bundle.artifacts.developer_json,
                overwrite,
            )?;
            write_output(
                &stories_output,
                &bundle.artifacts.stories_markdown,
                overwrite,
            )?;
            eprintln!(
                "offline quest content analysis: {}/{} solved; public={} developer={} stories={}",
                bundle.public.metrics.solved,
                bundle.public.metrics.cases,
                public_output.display(),
                developer_output.display(),
                stories_output.display()
            );
            return Ok(());
        }
        Command::QuestAnalyzeReplay { fixture, output } => {
            let recorded: ReplayCase = serde_json::from_slice(&read_bounded(&fixture)?)?;
            let trace = replay_case(&recorded)?;
            let json = serde_json::to_vec_pretty(&trace)?;
            if let Some(path) = output {
                write_output(&path, &json, false)?;
            } else {
                println!("{}", String::from_utf8(json)?);
            }
            return Ok(());
        }
        Command::QuestAnalyzePromote {
            seed,
            family,
            max_steps,
            output,
            overwrite,
        } => {
            let family = match family {
                EvalFamilyArg::RecurringDepredation => {
                    adventuresim_core::quest_generation::TemplateFamily::RecurringDepredation
                }
                EvalFamilyArg::DisappearanceOrLoss => {
                    adventuresim_core::quest_generation::TemplateFamily::DisappearanceOrLoss
                }
                EvalFamilyArg::Outbreak => {
                    adventuresim_core::quest_generation::TemplateFamily::Outbreak
                }
            };
            let limits = EvalLimits {
                max_cases: 1,
                max_steps_per_case: max_steps,
                ..EvalLimits::default()
            };
            let mut policy = MockLlmPolicy;
            let bundle = evaluate_cases(
                &[EvalCaseConfig::fixture(seed, family)],
                &mut policy,
                &limits,
            )?;
            let fixture = promote_replay_candidate(&bundle, 0)?;
            write_output(&output, &serde_json::to_vec_pretty(&fixture)?, overwrite)?;
            eprintln!(
                "reviewable replay candidate written to {}; verify before committing",
                output.display()
            );
            return Ok(());
        }
        command => command,
    };
    if let Command::Lifecycle { output_dir, seed } = command {
        let bundle = write_lifecycle_acceptance(&output_dir, seed)?;
        eprintln!(
            "offline lifecycle acceptance: passed={} digest={} output={}",
            bundle.comparison.passed,
            bundle.comparison.normalized_digest,
            output_dir.display()
        );
        if !bundle.comparison.passed {
            return Err("lifecycle acceptance comparison failed".into());
        }
        return Ok(());
    }
    if let Command::CoreLoop {
        host,
        database,
        seed,
        population,
        cycles,
        duration_days,
        party_size,
        run_nonce,
        fixture_disease,
        imported_world,
        require_quest_coverage,
        expected_world_manifest_digest,
        output,
        failure_output,
    } = command
    {
        let acceptance_failure_output = failure_output.clone();
        if let Some(json_output) = &output {
            let mut paths = vec![json_output.as_path()];
            if let Some(failure_output) = &failure_output {
                paths.push(failure_output.as_path());
            }
            validate_distinct_output_paths(&paths)?;
            if json_output.exists() || failure_output.as_ref().is_some_and(|path| path.exists()) {
                return Err("core-loop outputs already exist; use new output paths".into());
            }
        } else if failure_output.as_ref().is_some_and(|path| path.exists()) {
            return Err("failure output already exists; use a new output path".into());
        }
        let report = run_core_loop(CoreLoopConfig {
            host,
            database,
            seed,
            population,
            cycles,
            duration_days,
            party_size,
            run_nonce,
            fixture_disease,
            require_quest_coverage,
            use_imported_world: imported_world,
            expected_world_manifest_digest,
            failure_output,
        })?;
        let json = serde_json::to_vec_pretty(&report)?;
        if let Some(path) = output {
            write_output(&path, &json, false)?;
        } else {
            println!("{}", String::from_utf8(json)?);
        }
        if require_quest_coverage && let Err(error) = validate_quest_coverage(&report) {
            if let Some(path) = acceptance_failure_output.as_deref() {
                write_quest_coverage_failure(&report, path, &error)?;
            }
            return Err(error.into());
        }
        eprintln!(
            "authoritative core loop: {} completed / {} owner-scoped quest intakes or direct-contract attempts (direct {}/{}, generated {}/{}), {} quest defeats, {} encounters ({} encounter defeats, {} wipes), {} camps, {} upgrades",
            report.metrics.quests_completed,
            report.metrics.quests_attempted,
            report.metrics.direct_contracts_completed,
            report.metrics.direct_contracts_attempted,
            report.metrics.generated_quests_completed,
            report.metrics.generated_case_intakes,
            report.metrics.defeats,
            report.metrics.encounters,
            report.metrics.encounter_defeats,
            report.metrics.encounter_wipes,
            report.metrics.camp_stops,
            report.metrics.equipment_upgrades,
        );
        return Ok(());
    }
    let report = match command {
        Command::Run {
            config,
            output,
            seed,
            population,
            days,
        } => {
            let config = if let Some(path) = config {
                serde_json::from_slice(&read_bounded(&path)?)?
            } else {
                SimulationConfig {
                    seed,
                    population,
                    days,
                    max_decisions: u64::from(population)
                        .checked_mul(u64::from(days))
                        .ok_or("decision count overflow")?,
                    ..SimulationConfig::default()
                }
            };
            emit(run(config)?, output)?
        }
        Command::Replay { report, output } => {
            let recorded: SimulationReport = serde_json::from_slice(&read_bounded(&report)?)?;
            let computed = digest(&recorded)?;
            if computed != recorded.canonical_digest {
                return Err(format!(
                    "recorded report digest is invalid: stored {}, computed {computed}",
                    recorded.canonical_digest
                )
                .into());
            }
            let rerun = replay(recorded.manifest.clone())?;
            if rerun.canonical_digest != recorded.canonical_digest {
                return Err("replay digest differs".into());
            }
            emit(rerun, output)?
        }
        Command::Matched { seed, days, output } => {
            let (a, b) = matched_activity_pair(
                seed,
                0,
                ActivityPreference::Labor,
                ActivityPreference::Thievery,
            );
            let mut b = b;
            b.agent_id = 1;
            let config = SimulationConfig {
                seed,
                population: 2,
                days,
                max_decisions: 2_u64
                    .checked_mul(u64::from(days))
                    .ok_or("decision count overflow")?,
                ..SimulationConfig::default()
            };
            emit(run_profiles(config, vec![a, b])?, output)?
        }
        Command::CoreLoop { .. }
        | Command::QuestAnalyze { .. }
        | Command::QuestAnalyzeReplay { .. }
        | Command::QuestAnalyzePromote { .. }
        | Command::Lifecycle { .. } => unreachable!(),
    };
    eprintln!("{}", human_summary(&report));
    Ok(())
}

fn write_output(
    path: &Path,
    bytes: &[u8],
    overwrite: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    use std::fs::OpenOptions;
    let mut options = OpenOptions::new();
    options.write(true);
    if overwrite {
        options.create(true).truncate(true);
    } else {
        options.create_new(true);
    }
    std::io::Write::write_all(&mut options.open(path)?, bytes)?;
    Ok(())
}

fn validate_distinct_output_paths(paths: &[&Path]) -> Result<(), Box<dyn std::error::Error>> {
    let normalize = |path: &Path| -> Result<PathBuf, Box<dyn std::error::Error>> {
        let absolute = if path.is_absolute() {
            path.to_path_buf()
        } else {
            std::env::current_dir()?.join(path)
        };
        let lexical = lexical_normalize(&absolute);
        let existing = lexical
            .ancestors()
            .find(|candidate| candidate.exists())
            .ok_or("output path has no existing ancestor")?;
        let missing_tail = lexical.strip_prefix(existing)?;
        Ok(lexical_normalize(
            &fs::canonicalize(existing)?.join(missing_tail),
        ))
    };
    let normalized = paths
        .iter()
        .map(|path| normalize(path))
        .collect::<Result<Vec<_>, _>>()?;
    for (index, left) in normalized.iter().enumerate() {
        for right in normalized.iter().skip(index + 1) {
            let same = if cfg!(windows) {
                left.to_string_lossy()
                    .eq_ignore_ascii_case(&right.to_string_lossy())
            } else {
                left == right
            };
            if same {
                return Err("evaluation outputs must use distinct paths".into());
            }
        }
    }
    Ok(())
}

fn lexical_normalize(path: &Path) -> PathBuf {
    use std::path::Component;

    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::Prefix(prefix) => normalized.push(prefix.as_os_str()),
            Component::RootDir => normalized.push(component.as_os_str()),
            Component::CurDir => {}
            Component::ParentDir => {
                normalized.pop();
            }
            Component::Normal(segment) => normalized.push(segment),
        }
    }
    normalized
}

fn read_bounded(path: &Path) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let mut bytes = Vec::new();
    fs::File::open(path)?
        .take(MAX_INPUT_BYTES + 1)
        .read_to_end(&mut bytes)?;
    validate_input_len(bytes.len() as u64)?;
    Ok(bytes)
}

fn emit(
    report: SimulationReport,
    output: Option<PathBuf>,
) -> Result<SimulationReport, Box<dyn std::error::Error>> {
    let json = serde_json::to_vec_pretty(&report)?;
    if let Some(path) = output {
        fs::write(path, json)?;
    } else {
        println!("{}", String::from_utf8(json)?);
    }
    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn duplicate_outputs_must_differ() {
        let path = PathBuf::from("simulation-output.json");
        assert!(validate_distinct_output_paths(&[&path, &path]).is_err());
    }

    #[test]
    fn nonexistent_lexical_aliases_are_rejected() {
        let canonical = PathBuf::from("simulation-output.json");
        let alias = PathBuf::from("new-output-directory")
            .join("..")
            .join("simulation-output.json");
        assert!(validate_distinct_output_paths(&[&canonical, &alias]).is_err());
    }

    #[cfg(unix)]
    #[test]
    fn nonexistent_leaves_under_symlinked_parents_are_aliases() {
        use std::os::unix::fs::symlink;

        let root =
            std::env::temp_dir().join(format!("adventuresim-output-alias-{}", std::process::id()));
        let real = root.join("real");
        let alias = root.join("alias");
        fs::create_dir_all(&real).unwrap();
        symlink(&real, &alias).unwrap();
        let direct = real.join("future.json");
        let through_alias = alias.join("future.json");
        assert!(validate_distinct_output_paths(&[&direct, &through_alias]).is_err());
        fs::remove_dir_all(&root).unwrap();
    }
}
