// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::seed_type::Seed;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActivityIncidentEntropy {
    pub id: String,
    pub character_id: u64,
    pub seed: Seed,
}

impl __sdk::InModule for ActivityIncidentEntropy {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActivityIncidentEntropy`.
///
/// Provides typed access to columns for query building.
pub struct ActivityIncidentEntropyCols {
    pub id: __sdk::__query_builder::Col<ActivityIncidentEntropy, String>,
    pub character_id: __sdk::__query_builder::Col<ActivityIncidentEntropy, u64>,
    pub seed: __sdk::__query_builder::Col<ActivityIncidentEntropy, Seed>,
}

impl __sdk::__query_builder::HasCols for ActivityIncidentEntropy {
    type Cols = ActivityIncidentEntropyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActivityIncidentEntropyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            seed: __sdk::__query_builder::Col::new(table_name, "seed"),
        }
    }
}

/// Indexed column accessor struct for the table `ActivityIncidentEntropy`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActivityIncidentEntropyIxCols {
    pub character_id: __sdk::__query_builder::IxCol<ActivityIncidentEntropy, u64>,
    pub id: __sdk::__query_builder::IxCol<ActivityIncidentEntropy, String>,
}

impl __sdk::__query_builder::HasIxCols for ActivityIncidentEntropy {
    type IxCols = ActivityIncidentEntropyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActivityIncidentEntropyIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActivityIncidentEntropy {}
