// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AutomaticSocialChat {
    pub id: String,
    pub actor_id: u64,
    pub target_id: u64,
}

impl __sdk::InModule for AutomaticSocialChat {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AutomaticSocialChat`.
///
/// Provides typed access to columns for query building.
pub struct AutomaticSocialChatCols {
    pub id: __sdk::__query_builder::Col<AutomaticSocialChat, String>,
    pub actor_id: __sdk::__query_builder::Col<AutomaticSocialChat, u64>,
    pub target_id: __sdk::__query_builder::Col<AutomaticSocialChat, u64>,
}

impl __sdk::__query_builder::HasCols for AutomaticSocialChat {
    type Cols = AutomaticSocialChatCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AutomaticSocialChatCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            actor_id: __sdk::__query_builder::Col::new(table_name, "actor_id"),
            target_id: __sdk::__query_builder::Col::new(table_name, "target_id"),
        }
    }
}

/// Indexed column accessor struct for the table `AutomaticSocialChat`.
///
/// Provides typed access to indexed columns for query building.
pub struct AutomaticSocialChatIxCols {
    pub actor_id: __sdk::__query_builder::IxCol<AutomaticSocialChat, u64>,
    pub id: __sdk::__query_builder::IxCol<AutomaticSocialChat, String>,
    pub target_id: __sdk::__query_builder::IxCol<AutomaticSocialChat, u64>,
}

impl __sdk::__query_builder::HasIxCols for AutomaticSocialChat {
    type IxCols = AutomaticSocialChatIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AutomaticSocialChatIxCols {
            actor_id: __sdk::__query_builder::IxCol::new(table_name, "actor_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            target_id: __sdk::__query_builder::IxCol::new(table_name, "target_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AutomaticSocialChat {}
