// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::housing_tier_type::HousingTier;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AvailableResidenceProperty {
    pub property_id: String,
    pub settlement_id: String,
    pub building_id: u64,
    pub resident_capacity: u32,
    pub available_from_minute: StrategicMinute,
    pub tier: HousingTier,
    pub purchase_price: u32,
    pub rent_per_period: u32,
    pub owner_maintenance_per_period: u32,
    pub property_tax_per_period: u32,
    pub leisure_morale_basis_points: u16,
}

impl __sdk::InModule for AvailableResidenceProperty {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AvailableResidenceProperty`.
///
/// Provides typed access to columns for query building.
pub struct AvailableResidencePropertyCols {
    pub property_id: __sdk::__query_builder::Col<AvailableResidenceProperty, String>,
    pub settlement_id: __sdk::__query_builder::Col<AvailableResidenceProperty, String>,
    pub building_id: __sdk::__query_builder::Col<AvailableResidenceProperty, u64>,
    pub resident_capacity: __sdk::__query_builder::Col<AvailableResidenceProperty, u32>,
    pub available_from_minute:
        __sdk::__query_builder::Col<AvailableResidenceProperty, StrategicMinute>,
    pub tier: __sdk::__query_builder::Col<AvailableResidenceProperty, HousingTier>,
    pub purchase_price: __sdk::__query_builder::Col<AvailableResidenceProperty, u32>,
    pub rent_per_period: __sdk::__query_builder::Col<AvailableResidenceProperty, u32>,
    pub owner_maintenance_per_period: __sdk::__query_builder::Col<AvailableResidenceProperty, u32>,
    pub property_tax_per_period: __sdk::__query_builder::Col<AvailableResidenceProperty, u32>,
    pub leisure_morale_basis_points: __sdk::__query_builder::Col<AvailableResidenceProperty, u16>,
}

impl __sdk::__query_builder::HasCols for AvailableResidenceProperty {
    type Cols = AvailableResidencePropertyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AvailableResidencePropertyCols {
            property_id: __sdk::__query_builder::Col::new(table_name, "property_id"),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            building_id: __sdk::__query_builder::Col::new(table_name, "building_id"),
            resident_capacity: __sdk::__query_builder::Col::new(table_name, "resident_capacity"),
            available_from_minute: __sdk::__query_builder::Col::new(
                table_name,
                "available_from_minute",
            ),
            tier: __sdk::__query_builder::Col::new(table_name, "tier"),
            purchase_price: __sdk::__query_builder::Col::new(table_name, "purchase_price"),
            rent_per_period: __sdk::__query_builder::Col::new(table_name, "rent_per_period"),
            owner_maintenance_per_period: __sdk::__query_builder::Col::new(
                table_name,
                "owner_maintenance_per_period",
            ),
            property_tax_per_period: __sdk::__query_builder::Col::new(
                table_name,
                "property_tax_per_period",
            ),
            leisure_morale_basis_points: __sdk::__query_builder::Col::new(
                table_name,
                "leisure_morale_basis_points",
            ),
        }
    }
}
