// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_physiology_chart_type::BackendPhysiologyChart;
use super::backend_physiology_differential_type::BackendPhysiologyDifferential;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_physiology_charts`.
///
/// Obtain a handle from the [`BackendPhysiologyChartsTableAccess::backend_physiology_charts`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_physiology_charts()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_physiology_charts().on_insert(...)`.
pub struct BackendPhysiologyChartsTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendPhysiologyChart>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_physiology_charts`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendPhysiologyChartsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendPhysiologyChartsTableHandle`], which mediates access to the table `backend_physiology_charts`.
    fn backend_physiology_charts(&self) -> BackendPhysiologyChartsTableHandle<'_>;
}

impl BackendPhysiologyChartsTableAccess for super::RemoteTables {
    fn backend_physiology_charts(&self) -> BackendPhysiologyChartsTableHandle<'_> {
        BackendPhysiologyChartsTableHandle {
            imp: self
                .imp
                .get_table::<BackendPhysiologyChart>("backend_physiology_charts"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendPhysiologyChartsInsertCallbackId(__sdk::CallbackId);
pub struct BackendPhysiologyChartsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendPhysiologyChartsTableHandle<'ctx> {
    type Row = BackendPhysiologyChart;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendPhysiologyChart> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendPhysiologyChartsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendPhysiologyChartsInsertCallbackId {
        BackendPhysiologyChartsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendPhysiologyChartsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendPhysiologyChartsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendPhysiologyChartsDeleteCallbackId {
        BackendPhysiologyChartsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendPhysiologyChartsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<BackendPhysiologyChart>("backend_physiology_charts");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendPhysiologyChart>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BackendPhysiologyChart>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendPhysiologyChart`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_physiology_chartsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendPhysiologyChart`.
    fn backend_physiology_charts(&self) -> __sdk::__query_builder::Table<BackendPhysiologyChart>;
}

impl backend_physiology_chartsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_physiology_charts(&self) -> __sdk::__query_builder::Table<BackendPhysiologyChart> {
        __sdk::__query_builder::Table::new("backend_physiology_charts")
    }
}
