// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_legal_property_type::BackendLegalProperty;
use super::legal_owner_kind_type::LegalOwnerKind;
use super::property_kind_type::PropertyKind;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_legal_properties`.
///
/// Obtain a handle from the [`BackendLegalPropertiesTableAccess::backend_legal_properties`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_legal_properties()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_legal_properties().on_insert(...)`.
pub struct BackendLegalPropertiesTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendLegalProperty>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_legal_properties`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendLegalPropertiesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendLegalPropertiesTableHandle`], which mediates access to the table `backend_legal_properties`.
    fn backend_legal_properties(&self) -> BackendLegalPropertiesTableHandle<'_>;
}

impl BackendLegalPropertiesTableAccess for super::RemoteTables {
    fn backend_legal_properties(&self) -> BackendLegalPropertiesTableHandle<'_> {
        BackendLegalPropertiesTableHandle {
            imp: self
                .imp
                .get_table::<BackendLegalProperty>("backend_legal_properties"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendLegalPropertiesInsertCallbackId(__sdk::CallbackId);
pub struct BackendLegalPropertiesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendLegalPropertiesTableHandle<'ctx> {
    type Row = BackendLegalProperty;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendLegalProperty> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendLegalPropertiesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendLegalPropertiesInsertCallbackId {
        BackendLegalPropertiesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendLegalPropertiesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendLegalPropertiesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendLegalPropertiesDeleteCallbackId {
        BackendLegalPropertiesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendLegalPropertiesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BackendLegalProperty>("backend_legal_properties");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendLegalProperty>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BackendLegalProperty>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendLegalProperty`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_legal_propertiesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendLegalProperty`.
    fn backend_legal_properties(&self) -> __sdk::__query_builder::Table<BackendLegalProperty>;
}

impl backend_legal_propertiesQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_legal_properties(&self) -> __sdk::__query_builder::Table<BackendLegalProperty> {
        __sdk::__query_builder::Table::new("backend_legal_properties")
    }
}
