// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::destination_knowledge_stage_type::DestinationKnowledgeStage;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendInvestigationLead {
    pub owner_character_id: u64,
    pub case_id: String,
    pub lead_id: String,
    pub summary: String,
    pub source_label: String,
    pub confidence_bps: u16,
    pub destination_stage: DestinationKnowledgeStage,
    pub directions: String,
    pub exact_location_id: String,
    pub latitude_e_7: i32,
    pub longitude_e_7: i32,
    pub witness_name: String,
    pub witness_description: String,
    pub witness_occupation_or_relationship: String,
    pub expected_location: String,
    pub current_learned_location: String,
    pub contradiction_group: String,
    pub corrected_by: String,
    pub recorded_at: StrategicMinute,
}

impl __sdk::InModule for BackendInvestigationLead {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendInvestigationLead`.
///
/// Provides typed access to columns for query building.
pub struct BackendInvestigationLeadCols {
    pub owner_character_id: __sdk::__query_builder::Col<BackendInvestigationLead, u64>,
    pub case_id: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub lead_id: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub summary: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub source_label: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub confidence_bps: __sdk::__query_builder::Col<BackendInvestigationLead, u16>,
    pub destination_stage:
        __sdk::__query_builder::Col<BackendInvestigationLead, DestinationKnowledgeStage>,
    pub directions: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub exact_location_id: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub latitude_e_7: __sdk::__query_builder::Col<BackendInvestigationLead, i32>,
    pub longitude_e_7: __sdk::__query_builder::Col<BackendInvestigationLead, i32>,
    pub witness_name: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub witness_description: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub witness_occupation_or_relationship:
        __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub expected_location: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub current_learned_location: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub contradiction_group: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub corrected_by: __sdk::__query_builder::Col<BackendInvestigationLead, String>,
    pub recorded_at: __sdk::__query_builder::Col<BackendInvestigationLead, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for BackendInvestigationLead {
    type Cols = BackendInvestigationLeadCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendInvestigationLeadCols {
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            lead_id: __sdk::__query_builder::Col::new(table_name, "lead_id"),
            summary: __sdk::__query_builder::Col::new(table_name, "summary"),
            source_label: __sdk::__query_builder::Col::new(table_name, "source_label"),
            confidence_bps: __sdk::__query_builder::Col::new(table_name, "confidence_bps"),
            destination_stage: __sdk::__query_builder::Col::new(table_name, "destination_stage"),
            directions: __sdk::__query_builder::Col::new(table_name, "directions"),
            exact_location_id: __sdk::__query_builder::Col::new(table_name, "exact_location_id"),
            latitude_e_7: __sdk::__query_builder::Col::new(table_name, "latitude_e_7"),
            longitude_e_7: __sdk::__query_builder::Col::new(table_name, "longitude_e_7"),
            witness_name: __sdk::__query_builder::Col::new(table_name, "witness_name"),
            witness_description: __sdk::__query_builder::Col::new(
                table_name,
                "witness_description",
            ),
            witness_occupation_or_relationship: __sdk::__query_builder::Col::new(
                table_name,
                "witness_occupation_or_relationship",
            ),
            expected_location: __sdk::__query_builder::Col::new(table_name, "expected_location"),
            current_learned_location: __sdk::__query_builder::Col::new(
                table_name,
                "current_learned_location",
            ),
            contradiction_group: __sdk::__query_builder::Col::new(
                table_name,
                "contradiction_group",
            ),
            corrected_by: __sdk::__query_builder::Col::new(table_name, "corrected_by"),
            recorded_at: __sdk::__query_builder::Col::new(table_name, "recorded_at"),
        }
    }
}
