// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_dialogue_witness_claim_type::BackendDialogueWitnessClaim;
use super::witness_claim_resolution_type::WitnessClaimResolution;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_dialogue_witness_claims`.
///
/// Obtain a handle from the [`BackendDialogueWitnessClaimsTableAccess::backend_dialogue_witness_claims`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_dialogue_witness_claims()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_dialogue_witness_claims().on_insert(...)`.
pub struct BackendDialogueWitnessClaimsTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendDialogueWitnessClaim>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_dialogue_witness_claims`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendDialogueWitnessClaimsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendDialogueWitnessClaimsTableHandle`], which mediates access to the table `backend_dialogue_witness_claims`.
    fn backend_dialogue_witness_claims(&self) -> BackendDialogueWitnessClaimsTableHandle<'_>;
}

impl BackendDialogueWitnessClaimsTableAccess for super::RemoteTables {
    fn backend_dialogue_witness_claims(&self) -> BackendDialogueWitnessClaimsTableHandle<'_> {
        BackendDialogueWitnessClaimsTableHandle {
            imp: self
                .imp
                .get_table::<BackendDialogueWitnessClaim>("backend_dialogue_witness_claims"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendDialogueWitnessClaimsInsertCallbackId(__sdk::CallbackId);
pub struct BackendDialogueWitnessClaimsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendDialogueWitnessClaimsTableHandle<'ctx> {
    type Row = BackendDialogueWitnessClaim;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendDialogueWitnessClaim> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendDialogueWitnessClaimsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendDialogueWitnessClaimsInsertCallbackId {
        BackendDialogueWitnessClaimsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendDialogueWitnessClaimsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendDialogueWitnessClaimsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendDialogueWitnessClaimsDeleteCallbackId {
        BackendDialogueWitnessClaimsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendDialogueWitnessClaimsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<BackendDialogueWitnessClaim>("backend_dialogue_witness_claims");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendDialogueWitnessClaim>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<BackendDialogueWitnessClaim>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendDialogueWitnessClaim`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_dialogue_witness_claimsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendDialogueWitnessClaim`.
    fn backend_dialogue_witness_claims(
        &self,
    ) -> __sdk::__query_builder::Table<BackendDialogueWitnessClaim>;
}

impl backend_dialogue_witness_claimsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_dialogue_witness_claims(
        &self,
    ) -> __sdk::__query_builder::Table<BackendDialogueWitnessClaim> {
        __sdk::__query_builder::Table::new("backend_dialogue_witness_claims")
    }
}
