// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::organization_membership_status_type::OrganizationMembershipStatus;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendOrganizationMembership {
    pub id: u64,
    pub character_id: u64,
    pub organization_id: String,
    pub role_id: String,
    pub joined_minute: StrategicMinute,
    pub dues_paid_through_minute: StrategicMinute,
    pub status: OrganizationMembershipStatus,
    pub apprenticeship_minutes_accrued: u64,
    pub practice_minutes_accrued: u64,
}

impl __sdk::InModule for BackendOrganizationMembership {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendOrganizationMembership`.
///
/// Provides typed access to columns for query building.
pub struct BackendOrganizationMembershipCols {
    pub id: __sdk::__query_builder::Col<BackendOrganizationMembership, u64>,
    pub character_id: __sdk::__query_builder::Col<BackendOrganizationMembership, u64>,
    pub organization_id: __sdk::__query_builder::Col<BackendOrganizationMembership, String>,
    pub role_id: __sdk::__query_builder::Col<BackendOrganizationMembership, String>,
    pub joined_minute: __sdk::__query_builder::Col<BackendOrganizationMembership, StrategicMinute>,
    pub dues_paid_through_minute:
        __sdk::__query_builder::Col<BackendOrganizationMembership, StrategicMinute>,
    pub status:
        __sdk::__query_builder::Col<BackendOrganizationMembership, OrganizationMembershipStatus>,
    pub apprenticeship_minutes_accrued:
        __sdk::__query_builder::Col<BackendOrganizationMembership, u64>,
    pub practice_minutes_accrued: __sdk::__query_builder::Col<BackendOrganizationMembership, u64>,
}

impl __sdk::__query_builder::HasCols for BackendOrganizationMembership {
    type Cols = BackendOrganizationMembershipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendOrganizationMembershipCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            role_id: __sdk::__query_builder::Col::new(table_name, "role_id"),
            joined_minute: __sdk::__query_builder::Col::new(table_name, "joined_minute"),
            dues_paid_through_minute: __sdk::__query_builder::Col::new(
                table_name,
                "dues_paid_through_minute",
            ),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            apprenticeship_minutes_accrued: __sdk::__query_builder::Col::new(
                table_name,
                "apprenticeship_minutes_accrued",
            ),
            practice_minutes_accrued: __sdk::__query_builder::Col::new(
                table_name,
                "practice_minutes_accrued",
            ),
        }
    }
}
