// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_affinity_type::CharacterAffinity;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_character_affinities`.
///
/// Obtain a handle from the [`BackendCharacterAffinitiesTableAccess::backend_character_affinities`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_character_affinities()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_character_affinities().on_insert(...)`.
pub struct BackendCharacterAffinitiesTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterAffinity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_character_affinities`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendCharacterAffinitiesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendCharacterAffinitiesTableHandle`], which mediates access to the table `backend_character_affinities`.
    fn backend_character_affinities(&self) -> BackendCharacterAffinitiesTableHandle<'_>;
}

impl BackendCharacterAffinitiesTableAccess for super::RemoteTables {
    fn backend_character_affinities(&self) -> BackendCharacterAffinitiesTableHandle<'_> {
        BackendCharacterAffinitiesTableHandle {
            imp: self
                .imp
                .get_table::<CharacterAffinity>("backend_character_affinities"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendCharacterAffinitiesInsertCallbackId(__sdk::CallbackId);
pub struct BackendCharacterAffinitiesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendCharacterAffinitiesTableHandle<'ctx> {
    type Row = CharacterAffinity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterAffinity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendCharacterAffinitiesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterAffinitiesInsertCallbackId {
        BackendCharacterAffinitiesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendCharacterAffinitiesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendCharacterAffinitiesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterAffinitiesDeleteCallbackId {
        BackendCharacterAffinitiesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendCharacterAffinitiesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<CharacterAffinity>("backend_character_affinities");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterAffinity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterAffinity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterAffinity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_character_affinitiesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterAffinity`.
    fn backend_character_affinities(&self) -> __sdk::__query_builder::Table<CharacterAffinity>;
}

impl backend_character_affinitiesQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_character_affinities(&self) -> __sdk::__query_builder::Table<CharacterAffinity> {
        __sdk::__query_builder::Table::new("backend_character_affinities")
    }
}
