// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_property_event_type::BackendPropertyEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_property_events`.
///
/// Obtain a handle from the [`BackendPropertyEventsTableAccess::backend_property_events`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_property_events()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_property_events().on_insert(...)`.
pub struct BackendPropertyEventsTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendPropertyEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_property_events`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendPropertyEventsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendPropertyEventsTableHandle`], which mediates access to the table `backend_property_events`.
    fn backend_property_events(&self) -> BackendPropertyEventsTableHandle<'_>;
}

impl BackendPropertyEventsTableAccess for super::RemoteTables {
    fn backend_property_events(&self) -> BackendPropertyEventsTableHandle<'_> {
        BackendPropertyEventsTableHandle {
            imp: self
                .imp
                .get_table::<BackendPropertyEvent>("backend_property_events"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendPropertyEventsInsertCallbackId(__sdk::CallbackId);
pub struct BackendPropertyEventsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendPropertyEventsTableHandle<'ctx> {
    type Row = BackendPropertyEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendPropertyEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendPropertyEventsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendPropertyEventsInsertCallbackId {
        BackendPropertyEventsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendPropertyEventsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendPropertyEventsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendPropertyEventsDeleteCallbackId {
        BackendPropertyEventsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendPropertyEventsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BackendPropertyEvent>("backend_property_events");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendPropertyEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BackendPropertyEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendPropertyEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_property_eventsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendPropertyEvent`.
    fn backend_property_events(&self) -> __sdk::__query_builder::Table<BackendPropertyEvent>;
}

impl backend_property_eventsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_property_events(&self) -> __sdk::__query_builder::Table<BackendPropertyEvent> {
        __sdk::__query_builder::Table::new("backend_property_events")
    }
}
