// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_investigation_action_outcome_type::BackendInvestigationActionOutcome;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_investigation_action_outcomes`.
///
/// Obtain a handle from the [`BackendInvestigationActionOutcomesTableAccess::backend_investigation_action_outcomes`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_investigation_action_outcomes()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_investigation_action_outcomes().on_insert(...)`.
pub struct BackendInvestigationActionOutcomesTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendInvestigationActionOutcome>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_investigation_action_outcomes`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendInvestigationActionOutcomesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendInvestigationActionOutcomesTableHandle`], which mediates access to the table `backend_investigation_action_outcomes`.
    fn backend_investigation_action_outcomes(
        &self,
    ) -> BackendInvestigationActionOutcomesTableHandle<'_>;
}

impl BackendInvestigationActionOutcomesTableAccess for super::RemoteTables {
    fn backend_investigation_action_outcomes(
        &self,
    ) -> BackendInvestigationActionOutcomesTableHandle<'_> {
        BackendInvestigationActionOutcomesTableHandle {
            imp: self.imp.get_table::<BackendInvestigationActionOutcome>(
                "backend_investigation_action_outcomes",
            ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendInvestigationActionOutcomesInsertCallbackId(__sdk::CallbackId);
pub struct BackendInvestigationActionOutcomesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendInvestigationActionOutcomesTableHandle<'ctx> {
    type Row = BackendInvestigationActionOutcome;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendInvestigationActionOutcome> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendInvestigationActionOutcomesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendInvestigationActionOutcomesInsertCallbackId {
        BackendInvestigationActionOutcomesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendInvestigationActionOutcomesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendInvestigationActionOutcomesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendInvestigationActionOutcomesDeleteCallbackId {
        BackendInvestigationActionOutcomesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendInvestigationActionOutcomesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BackendInvestigationActionOutcome>(
        "backend_investigation_action_outcomes",
    );
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendInvestigationActionOutcome>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<BackendInvestigationActionOutcome>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendInvestigationActionOutcome`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_investigation_action_outcomesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendInvestigationActionOutcome`.
    fn backend_investigation_action_outcomes(
        &self,
    ) -> __sdk::__query_builder::Table<BackendInvestigationActionOutcome>;
}

impl backend_investigation_action_outcomesQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_investigation_action_outcomes(
        &self,
    ) -> __sdk::__query_builder::Table<BackendInvestigationActionOutcome> {
        __sdk::__query_builder::Table::new("backend_investigation_action_outcomes")
    }
}
