// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_character_residence_status_type::BackendCharacterResidenceStatus;
use super::housing_tier_type::HousingTier;
use super::residence_tenure_type::ResidenceTenure;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_character_residence_statuses`.
///
/// Obtain a handle from the [`BackendCharacterResidenceStatusesTableAccess::backend_character_residence_statuses`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_character_residence_statuses()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_character_residence_statuses().on_insert(...)`.
pub struct BackendCharacterResidenceStatusesTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendCharacterResidenceStatus>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_character_residence_statuses`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendCharacterResidenceStatusesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendCharacterResidenceStatusesTableHandle`], which mediates access to the table `backend_character_residence_statuses`.
    fn backend_character_residence_statuses(
        &self,
    ) -> BackendCharacterResidenceStatusesTableHandle<'_>;
}

impl BackendCharacterResidenceStatusesTableAccess for super::RemoteTables {
    fn backend_character_residence_statuses(
        &self,
    ) -> BackendCharacterResidenceStatusesTableHandle<'_> {
        BackendCharacterResidenceStatusesTableHandle {
            imp: self.imp.get_table::<BackendCharacterResidenceStatus>(
                "backend_character_residence_statuses",
            ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendCharacterResidenceStatusesInsertCallbackId(__sdk::CallbackId);
pub struct BackendCharacterResidenceStatusesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendCharacterResidenceStatusesTableHandle<'ctx> {
    type Row = BackendCharacterResidenceStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendCharacterResidenceStatus> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendCharacterResidenceStatusesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterResidenceStatusesInsertCallbackId {
        BackendCharacterResidenceStatusesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendCharacterResidenceStatusesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendCharacterResidenceStatusesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterResidenceStatusesDeleteCallbackId {
        BackendCharacterResidenceStatusesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendCharacterResidenceStatusesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BackendCharacterResidenceStatus>(
        "backend_character_residence_statuses",
    );
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendCharacterResidenceStatus>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<BackendCharacterResidenceStatus>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendCharacterResidenceStatus`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_character_residence_statusesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendCharacterResidenceStatus`.
    fn backend_character_residence_statuses(
        &self,
    ) -> __sdk::__query_builder::Table<BackendCharacterResidenceStatus>;
}

impl backend_character_residence_statusesQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_character_residence_statuses(
        &self,
    ) -> __sdk::__query_builder::Table<BackendCharacterResidenceStatus> {
        __sdk::__query_builder::Table::new("backend_character_residence_statuses")
    }
}
