// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendPropertyEvent {
    pub observer_party_id: String,
    pub source_id: String,
    pub actor_id: u64,
    pub victim_id: String,
    pub property_id: String,
    pub location_id: String,
    pub theft: bool,
    pub witnessed: bool,
}

impl __sdk::InModule for BackendPropertyEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendPropertyEvent`.
///
/// Provides typed access to columns for query building.
pub struct BackendPropertyEventCols {
    pub observer_party_id: __sdk::__query_builder::Col<BackendPropertyEvent, String>,
    pub source_id: __sdk::__query_builder::Col<BackendPropertyEvent, String>,
    pub actor_id: __sdk::__query_builder::Col<BackendPropertyEvent, u64>,
    pub victim_id: __sdk::__query_builder::Col<BackendPropertyEvent, String>,
    pub property_id: __sdk::__query_builder::Col<BackendPropertyEvent, String>,
    pub location_id: __sdk::__query_builder::Col<BackendPropertyEvent, String>,
    pub theft: __sdk::__query_builder::Col<BackendPropertyEvent, bool>,
    pub witnessed: __sdk::__query_builder::Col<BackendPropertyEvent, bool>,
}

impl __sdk::__query_builder::HasCols for BackendPropertyEvent {
    type Cols = BackendPropertyEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendPropertyEventCols {
            observer_party_id: __sdk::__query_builder::Col::new(table_name, "observer_party_id"),
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            actor_id: __sdk::__query_builder::Col::new(table_name, "actor_id"),
            victim_id: __sdk::__query_builder::Col::new(table_name, "victim_id"),
            property_id: __sdk::__query_builder::Col::new(table_name, "property_id"),
            location_id: __sdk::__query_builder::Col::new(table_name, "location_id"),
            theft: __sdk::__query_builder::Col::new(table_name, "theft"),
            witnessed: __sdk::__query_builder::Col::new(table_name, "witnessed"),
        }
    }
}
