// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::npc_age_band_type::NpcAgeBand;
use super::npc_presentation_type::NpcPresentation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendSettlementResident {
    pub character_id: u64,
    pub home_settlement_id: String,
    pub name: String,
    pub age_band: NpcAgeBand,
    pub presentation: NpcPresentation,
    pub height: String,
    pub build: String,
    pub hair: String,
    pub facial_hair: String,
    pub complexion: String,
    pub visible_features: String,
    pub clothing: String,
    pub profession: String,
    pub household_kind: String,
    pub local_role: String,
    pub service_id: String,
    pub organization_id: String,
    pub conversation_id: String,
}

impl __sdk::InModule for BackendSettlementResident {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendSettlementResident`.
///
/// Provides typed access to columns for query building.
pub struct BackendSettlementResidentCols {
    pub character_id: __sdk::__query_builder::Col<BackendSettlementResident, u64>,
    pub home_settlement_id: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub name: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub age_band: __sdk::__query_builder::Col<BackendSettlementResident, NpcAgeBand>,
    pub presentation: __sdk::__query_builder::Col<BackendSettlementResident, NpcPresentation>,
    pub height: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub build: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub hair: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub facial_hair: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub complexion: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub visible_features: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub clothing: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub profession: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub household_kind: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub local_role: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub service_id: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub organization_id: __sdk::__query_builder::Col<BackendSettlementResident, String>,
    pub conversation_id: __sdk::__query_builder::Col<BackendSettlementResident, String>,
}

impl __sdk::__query_builder::HasCols for BackendSettlementResident {
    type Cols = BackendSettlementResidentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendSettlementResidentCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            home_settlement_id: __sdk::__query_builder::Col::new(table_name, "home_settlement_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            age_band: __sdk::__query_builder::Col::new(table_name, "age_band"),
            presentation: __sdk::__query_builder::Col::new(table_name, "presentation"),
            height: __sdk::__query_builder::Col::new(table_name, "height"),
            build: __sdk::__query_builder::Col::new(table_name, "build"),
            hair: __sdk::__query_builder::Col::new(table_name, "hair"),
            facial_hair: __sdk::__query_builder::Col::new(table_name, "facial_hair"),
            complexion: __sdk::__query_builder::Col::new(table_name, "complexion"),
            visible_features: __sdk::__query_builder::Col::new(table_name, "visible_features"),
            clothing: __sdk::__query_builder::Col::new(table_name, "clothing"),
            profession: __sdk::__query_builder::Col::new(table_name, "profession"),
            household_kind: __sdk::__query_builder::Col::new(table_name, "household_kind"),
            local_role: __sdk::__query_builder::Col::new(table_name, "local_role"),
            service_id: __sdk::__query_builder::Col::new(table_name, "service_id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            conversation_id: __sdk::__query_builder::Col::new(table_name, "conversation_id"),
        }
    }
}
