// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::case_site_id_type::CaseSiteId;
use super::destination_knowledge_stage_type::DestinationKnowledgeStage;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendCaseSitePin {
    pub owner_character_id: u64,
    pub case_id: String,
    pub case_site_id: CaseSiteId,
    pub origin_settlement_id: String,
    pub name: String,
    pub description: String,
    pub scene_key: String,
    pub longitude_e_7: i32,
    pub latitude_e_7: i32,
    pub coordinates_are_geographic: bool,
    pub distance_m: u64,
    pub raiding_allowed: bool,
    pub knowledge_stage: DestinationKnowledgeStage,
    pub tracked: bool,
    pub display_title: String,
    pub generated_case: bool,
    pub case_resolved: bool,
    pub combat_available: bool,
    pub opposition_count: Option<u32>,
    pub opposition_combat_power: Option<u64>,
}

impl __sdk::InModule for BackendCaseSitePin {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendCaseSitePin`.
///
/// Provides typed access to columns for query building.
pub struct BackendCaseSitePinCols {
    pub owner_character_id: __sdk::__query_builder::Col<BackendCaseSitePin, u64>,
    pub case_id: __sdk::__query_builder::Col<BackendCaseSitePin, String>,
    pub case_site_id: __sdk::__query_builder::Col<BackendCaseSitePin, CaseSiteId>,
    pub origin_settlement_id: __sdk::__query_builder::Col<BackendCaseSitePin, String>,
    pub name: __sdk::__query_builder::Col<BackendCaseSitePin, String>,
    pub description: __sdk::__query_builder::Col<BackendCaseSitePin, String>,
    pub scene_key: __sdk::__query_builder::Col<BackendCaseSitePin, String>,
    pub longitude_e_7: __sdk::__query_builder::Col<BackendCaseSitePin, i32>,
    pub latitude_e_7: __sdk::__query_builder::Col<BackendCaseSitePin, i32>,
    pub coordinates_are_geographic: __sdk::__query_builder::Col<BackendCaseSitePin, bool>,
    pub distance_m: __sdk::__query_builder::Col<BackendCaseSitePin, u64>,
    pub raiding_allowed: __sdk::__query_builder::Col<BackendCaseSitePin, bool>,
    pub knowledge_stage: __sdk::__query_builder::Col<BackendCaseSitePin, DestinationKnowledgeStage>,
    pub tracked: __sdk::__query_builder::Col<BackendCaseSitePin, bool>,
    pub display_title: __sdk::__query_builder::Col<BackendCaseSitePin, String>,
    pub generated_case: __sdk::__query_builder::Col<BackendCaseSitePin, bool>,
    pub case_resolved: __sdk::__query_builder::Col<BackendCaseSitePin, bool>,
    pub combat_available: __sdk::__query_builder::Col<BackendCaseSitePin, bool>,
    pub opposition_count: __sdk::__query_builder::Col<BackendCaseSitePin, Option<u32>>,
    pub opposition_combat_power: __sdk::__query_builder::Col<BackendCaseSitePin, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for BackendCaseSitePin {
    type Cols = BackendCaseSitePinCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendCaseSitePinCols {
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            case_site_id: __sdk::__query_builder::Col::new(table_name, "case_site_id"),
            origin_settlement_id: __sdk::__query_builder::Col::new(
                table_name,
                "origin_settlement_id",
            ),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            scene_key: __sdk::__query_builder::Col::new(table_name, "scene_key"),
            longitude_e_7: __sdk::__query_builder::Col::new(table_name, "longitude_e_7"),
            latitude_e_7: __sdk::__query_builder::Col::new(table_name, "latitude_e_7"),
            coordinates_are_geographic: __sdk::__query_builder::Col::new(
                table_name,
                "coordinates_are_geographic",
            ),
            distance_m: __sdk::__query_builder::Col::new(table_name, "distance_m"),
            raiding_allowed: __sdk::__query_builder::Col::new(table_name, "raiding_allowed"),
            knowledge_stage: __sdk::__query_builder::Col::new(table_name, "knowledge_stage"),
            tracked: __sdk::__query_builder::Col::new(table_name, "tracked"),
            display_title: __sdk::__query_builder::Col::new(table_name, "display_title"),
            generated_case: __sdk::__query_builder::Col::new(table_name, "generated_case"),
            case_resolved: __sdk::__query_builder::Col::new(table_name, "case_resolved"),
            combat_available: __sdk::__query_builder::Col::new(table_name, "combat_available"),
            opposition_count: __sdk::__query_builder::Col::new(table_name, "opposition_count"),
            opposition_combat_power: __sdk::__query_builder::Col::new(
                table_name,
                "opposition_combat_power",
            ),
        }
    }
}
