// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendRoadChallenge {
    pub id: String,
    pub owner_character_id: u64,
    pub absolute_minute: StrategicMinute,
    pub presentation_json: String,
    pub revision: u32,
    pub open: bool,
    pub active: bool,
    pub result_transcript: Option<String>,
    pub quest_reward_addendum: Option<String>,
}

impl __sdk::InModule for BackendRoadChallenge {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendRoadChallenge`.
///
/// Provides typed access to columns for query building.
pub struct BackendRoadChallengeCols {
    pub id: __sdk::__query_builder::Col<BackendRoadChallenge, String>,
    pub owner_character_id: __sdk::__query_builder::Col<BackendRoadChallenge, u64>,
    pub absolute_minute: __sdk::__query_builder::Col<BackendRoadChallenge, StrategicMinute>,
    pub presentation_json: __sdk::__query_builder::Col<BackendRoadChallenge, String>,
    pub revision: __sdk::__query_builder::Col<BackendRoadChallenge, u32>,
    pub open: __sdk::__query_builder::Col<BackendRoadChallenge, bool>,
    pub active: __sdk::__query_builder::Col<BackendRoadChallenge, bool>,
    pub result_transcript: __sdk::__query_builder::Col<BackendRoadChallenge, Option<String>>,
    pub quest_reward_addendum: __sdk::__query_builder::Col<BackendRoadChallenge, Option<String>>,
}

impl __sdk::__query_builder::HasCols for BackendRoadChallenge {
    type Cols = BackendRoadChallengeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendRoadChallengeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            absolute_minute: __sdk::__query_builder::Col::new(table_name, "absolute_minute"),
            presentation_json: __sdk::__query_builder::Col::new(table_name, "presentation_json"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            open: __sdk::__query_builder::Col::new(table_name, "open"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
            result_transcript: __sdk::__query_builder::Col::new(table_name, "result_transcript"),
            quest_reward_addendum: __sdk::__query_builder::Col::new(
                table_name,
                "quest_reward_addendum",
            ),
        }
    }
}
