// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::contract_status_type::ContractStatus;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendContract {
    pub id: String,
    pub case_id: String,
    pub title: String,
    pub description: String,
    pub difficulty: i32,
    pub gold_reward: i32,
    pub xp_reward: i32,
    pub settlement_id: String,
    pub service_id: String,
    pub issuer_resident_character_id: u64,
    pub status: ContractStatus,
    pub accepted_by: Option<String>,
    pub opposition_wording: String,
    pub opposition_count_wording: String,
    pub opposition_count: u32,
    pub opposition_combat_power: u64,
    pub accepted_at_minute: Option<StrategicMinute>,
    pub paid_at_minute: Option<StrategicMinute>,
    pub distance_m: u64,
}

impl __sdk::InModule for BackendContract {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendContract`.
///
/// Provides typed access to columns for query building.
pub struct BackendContractCols {
    pub id: __sdk::__query_builder::Col<BackendContract, String>,
    pub case_id: __sdk::__query_builder::Col<BackendContract, String>,
    pub title: __sdk::__query_builder::Col<BackendContract, String>,
    pub description: __sdk::__query_builder::Col<BackendContract, String>,
    pub difficulty: __sdk::__query_builder::Col<BackendContract, i32>,
    pub gold_reward: __sdk::__query_builder::Col<BackendContract, i32>,
    pub xp_reward: __sdk::__query_builder::Col<BackendContract, i32>,
    pub settlement_id: __sdk::__query_builder::Col<BackendContract, String>,
    pub service_id: __sdk::__query_builder::Col<BackendContract, String>,
    pub issuer_resident_character_id: __sdk::__query_builder::Col<BackendContract, u64>,
    pub status: __sdk::__query_builder::Col<BackendContract, ContractStatus>,
    pub accepted_by: __sdk::__query_builder::Col<BackendContract, Option<String>>,
    pub opposition_wording: __sdk::__query_builder::Col<BackendContract, String>,
    pub opposition_count_wording: __sdk::__query_builder::Col<BackendContract, String>,
    pub opposition_count: __sdk::__query_builder::Col<BackendContract, u32>,
    pub opposition_combat_power: __sdk::__query_builder::Col<BackendContract, u64>,
    pub accepted_at_minute: __sdk::__query_builder::Col<BackendContract, Option<StrategicMinute>>,
    pub paid_at_minute: __sdk::__query_builder::Col<BackendContract, Option<StrategicMinute>>,
    pub distance_m: __sdk::__query_builder::Col<BackendContract, u64>,
}

impl __sdk::__query_builder::HasCols for BackendContract {
    type Cols = BackendContractCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendContractCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            difficulty: __sdk::__query_builder::Col::new(table_name, "difficulty"),
            gold_reward: __sdk::__query_builder::Col::new(table_name, "gold_reward"),
            xp_reward: __sdk::__query_builder::Col::new(table_name, "xp_reward"),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            service_id: __sdk::__query_builder::Col::new(table_name, "service_id"),
            issuer_resident_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "issuer_resident_character_id",
            ),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            accepted_by: __sdk::__query_builder::Col::new(table_name, "accepted_by"),
            opposition_wording: __sdk::__query_builder::Col::new(table_name, "opposition_wording"),
            opposition_count_wording: __sdk::__query_builder::Col::new(
                table_name,
                "opposition_count_wording",
            ),
            opposition_count: __sdk::__query_builder::Col::new(table_name, "opposition_count"),
            opposition_combat_power: __sdk::__query_builder::Col::new(
                table_name,
                "opposition_combat_power",
            ),
            accepted_at_minute: __sdk::__query_builder::Col::new(table_name, "accepted_at_minute"),
            paid_at_minute: __sdk::__query_builder::Col::new(table_name, "paid_at_minute"),
            distance_m: __sdk::__query_builder::Col::new(table_name, "distance_m"),
        }
    }
}
