// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_tincture_status_type::BackendTinctureStatus;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_tincture_statuses`.
///
/// Obtain a handle from the [`BackendTinctureStatusesTableAccess::backend_tincture_statuses`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_tincture_statuses()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_tincture_statuses().on_insert(...)`.
pub struct BackendTinctureStatusesTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendTinctureStatus>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_tincture_statuses`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendTinctureStatusesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendTinctureStatusesTableHandle`], which mediates access to the table `backend_tincture_statuses`.
    fn backend_tincture_statuses(&self) -> BackendTinctureStatusesTableHandle<'_>;
}

impl BackendTinctureStatusesTableAccess for super::RemoteTables {
    fn backend_tincture_statuses(&self) -> BackendTinctureStatusesTableHandle<'_> {
        BackendTinctureStatusesTableHandle {
            imp: self
                .imp
                .get_table::<BackendTinctureStatus>("backend_tincture_statuses"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendTinctureStatusesInsertCallbackId(__sdk::CallbackId);
pub struct BackendTinctureStatusesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendTinctureStatusesTableHandle<'ctx> {
    type Row = BackendTinctureStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendTinctureStatus> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendTinctureStatusesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendTinctureStatusesInsertCallbackId {
        BackendTinctureStatusesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendTinctureStatusesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendTinctureStatusesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendTinctureStatusesDeleteCallbackId {
        BackendTinctureStatusesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendTinctureStatusesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<BackendTinctureStatus>("backend_tincture_statuses");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendTinctureStatus>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BackendTinctureStatus>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendTinctureStatus`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_tincture_statusesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendTinctureStatus`.
    fn backend_tincture_statuses(&self) -> __sdk::__query_builder::Table<BackendTinctureStatus>;
}

impl backend_tincture_statusesQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_tincture_statuses(&self) -> __sdk::__query_builder::Table<BackendTinctureStatus> {
        __sdk::__query_builder::Table::new("backend_tincture_statuses")
    }
}
