// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::housing_tier_type::HousingTier;
use super::residence_tenure_type::ResidenceTenure;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendCharacterResidenceStatus {
    pub property_id: String,
    pub character_id: u64,
    pub holding_id: String,
    pub holder_character_id: u64,
    pub settlement_id: String,
    pub tier: HousingTier,
    pub tenure: ResidenceTenure,
    pub active: bool,
    pub primary: bool,
    pub occupied: bool,
    pub acquired_minute: StrategicMinute,
    pub last_billed_minute: StrategicMinute,
    pub next_due_minute: StrategicMinute,
}

impl __sdk::InModule for BackendCharacterResidenceStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendCharacterResidenceStatus`.
///
/// Provides typed access to columns for query building.
pub struct BackendCharacterResidenceStatusCols {
    pub property_id: __sdk::__query_builder::Col<BackendCharacterResidenceStatus, String>,
    pub character_id: __sdk::__query_builder::Col<BackendCharacterResidenceStatus, u64>,
    pub holding_id: __sdk::__query_builder::Col<BackendCharacterResidenceStatus, String>,
    pub holder_character_id: __sdk::__query_builder::Col<BackendCharacterResidenceStatus, u64>,
    pub settlement_id: __sdk::__query_builder::Col<BackendCharacterResidenceStatus, String>,
    pub tier: __sdk::__query_builder::Col<BackendCharacterResidenceStatus, HousingTier>,
    pub tenure: __sdk::__query_builder::Col<BackendCharacterResidenceStatus, ResidenceTenure>,
    pub active: __sdk::__query_builder::Col<BackendCharacterResidenceStatus, bool>,
    pub primary: __sdk::__query_builder::Col<BackendCharacterResidenceStatus, bool>,
    pub occupied: __sdk::__query_builder::Col<BackendCharacterResidenceStatus, bool>,
    pub acquired_minute:
        __sdk::__query_builder::Col<BackendCharacterResidenceStatus, StrategicMinute>,
    pub last_billed_minute:
        __sdk::__query_builder::Col<BackendCharacterResidenceStatus, StrategicMinute>,
    pub next_due_minute:
        __sdk::__query_builder::Col<BackendCharacterResidenceStatus, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for BackendCharacterResidenceStatus {
    type Cols = BackendCharacterResidenceStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendCharacterResidenceStatusCols {
            property_id: __sdk::__query_builder::Col::new(table_name, "property_id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            holding_id: __sdk::__query_builder::Col::new(table_name, "holding_id"),
            holder_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "holder_character_id",
            ),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            tier: __sdk::__query_builder::Col::new(table_name, "tier"),
            tenure: __sdk::__query_builder::Col::new(table_name, "tenure"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
            primary: __sdk::__query_builder::Col::new(table_name, "primary"),
            occupied: __sdk::__query_builder::Col::new(table_name, "occupied"),
            acquired_minute: __sdk::__query_builder::Col::new(table_name, "acquired_minute"),
            last_billed_minute: __sdk::__query_builder::Col::new(table_name, "last_billed_minute"),
            next_due_minute: __sdk::__query_builder::Col::new(table_name, "next_due_minute"),
        }
    }
}
