// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_fireplace_dish_type::BackendFireplaceDish;
use super::cooking_method_type::CookingMethod;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_fireplace_dishes`.
///
/// Obtain a handle from the [`BackendFireplaceDishesTableAccess::backend_fireplace_dishes`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_fireplace_dishes()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_fireplace_dishes().on_insert(...)`.
pub struct BackendFireplaceDishesTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendFireplaceDish>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_fireplace_dishes`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendFireplaceDishesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendFireplaceDishesTableHandle`], which mediates access to the table `backend_fireplace_dishes`.
    fn backend_fireplace_dishes(&self) -> BackendFireplaceDishesTableHandle<'_>;
}

impl BackendFireplaceDishesTableAccess for super::RemoteTables {
    fn backend_fireplace_dishes(&self) -> BackendFireplaceDishesTableHandle<'_> {
        BackendFireplaceDishesTableHandle {
            imp: self
                .imp
                .get_table::<BackendFireplaceDish>("backend_fireplace_dishes"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendFireplaceDishesInsertCallbackId(__sdk::CallbackId);
pub struct BackendFireplaceDishesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendFireplaceDishesTableHandle<'ctx> {
    type Row = BackendFireplaceDish;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendFireplaceDish> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendFireplaceDishesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendFireplaceDishesInsertCallbackId {
        BackendFireplaceDishesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendFireplaceDishesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendFireplaceDishesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendFireplaceDishesDeleteCallbackId {
        BackendFireplaceDishesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendFireplaceDishesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BackendFireplaceDish>("backend_fireplace_dishes");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendFireplaceDish>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BackendFireplaceDish>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendFireplaceDish`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_fireplace_dishesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendFireplaceDish`.
    fn backend_fireplace_dishes(&self) -> __sdk::__query_builder::Table<BackendFireplaceDish>;
}

impl backend_fireplace_dishesQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_fireplace_dishes(&self) -> __sdk::__query_builder::Table<BackendFireplaceDish> {
        __sdk::__query_builder::Table::new("backend_fireplace_dishes")
    }
}
