// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::witness_claim_resolution_type::WitnessClaimResolution;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendDialogueWitnessClaim {
    pub observer_character_id: u64,
    pub session_id: String,
    pub resident_character_id: u64,
    pub event_sequence: u32,
    pub claim_order: u32,
    pub challenge_token: String,
    pub displayed_text: String,
    pub charm_response: Option<String>,
    pub command_response: Option<String>,
    pub bluff_response: Option<String>,
    pub assessment_direction: String,
    pub assessment_strength: f32,
    pub resolution: Option<WitnessClaimResolution>,
}

impl __sdk::InModule for BackendDialogueWitnessClaim {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendDialogueWitnessClaim`.
///
/// Provides typed access to columns for query building.
pub struct BackendDialogueWitnessClaimCols {
    pub observer_character_id: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, u64>,
    pub session_id: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, String>,
    pub resident_character_id: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, u64>,
    pub event_sequence: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, u32>,
    pub claim_order: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, u32>,
    pub challenge_token: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, String>,
    pub displayed_text: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, String>,
    pub charm_response: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, Option<String>>,
    pub command_response: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, Option<String>>,
    pub bluff_response: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, Option<String>>,
    pub assessment_direction: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, String>,
    pub assessment_strength: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, f32>,
    pub resolution:
        __sdk::__query_builder::Col<BackendDialogueWitnessClaim, Option<WitnessClaimResolution>>,
}

impl __sdk::__query_builder::HasCols for BackendDialogueWitnessClaim {
    type Cols = BackendDialogueWitnessClaimCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendDialogueWitnessClaimCols {
            observer_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "observer_character_id",
            ),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            resident_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "resident_character_id",
            ),
            event_sequence: __sdk::__query_builder::Col::new(table_name, "event_sequence"),
            claim_order: __sdk::__query_builder::Col::new(table_name, "claim_order"),
            challenge_token: __sdk::__query_builder::Col::new(table_name, "challenge_token"),
            displayed_text: __sdk::__query_builder::Col::new(table_name, "displayed_text"),
            charm_response: __sdk::__query_builder::Col::new(table_name, "charm_response"),
            command_response: __sdk::__query_builder::Col::new(table_name, "command_response"),
            bluff_response: __sdk::__query_builder::Col::new(table_name, "bluff_response"),
            assessment_direction: __sdk::__query_builder::Col::new(
                table_name,
                "assessment_direction",
            ),
            assessment_strength: __sdk::__query_builder::Col::new(
                table_name,
                "assessment_strength",
            ),
            resolution: __sdk::__query_builder::Col::new(table_name, "resolution"),
        }
    }
}
