// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendTinctureStatus {
    pub container_object_id: u64,
    pub ready_at_world_minute: StrategicMinute,
    pub matured: bool,
}

impl __sdk::InModule for BackendTinctureStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendTinctureStatus`.
///
/// Provides typed access to columns for query building.
pub struct BackendTinctureStatusCols {
    pub container_object_id: __sdk::__query_builder::Col<BackendTinctureStatus, u64>,
    pub ready_at_world_minute: __sdk::__query_builder::Col<BackendTinctureStatus, StrategicMinute>,
    pub matured: __sdk::__query_builder::Col<BackendTinctureStatus, bool>,
}

impl __sdk::__query_builder::HasCols for BackendTinctureStatus {
    type Cols = BackendTinctureStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendTinctureStatusCols {
            container_object_id: __sdk::__query_builder::Col::new(
                table_name,
                "container_object_id",
            ),
            ready_at_world_minute: __sdk::__query_builder::Col::new(
                table_name,
                "ready_at_world_minute",
            ),
            matured: __sdk::__query_builder::Col::new(table_name, "matured"),
        }
    }
}
