// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendCourtshipDiscoveryStatus {
    pub observer_character_id: u64,
    pub first_character_id: u64,
    pub second_character_id: u64,
    pub discovered_minute: StrategicMinute,
}

impl __sdk::InModule for BackendCourtshipDiscoveryStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendCourtshipDiscoveryStatus`.
///
/// Provides typed access to columns for query building.
pub struct BackendCourtshipDiscoveryStatusCols {
    pub observer_character_id: __sdk::__query_builder::Col<BackendCourtshipDiscoveryStatus, u64>,
    pub first_character_id: __sdk::__query_builder::Col<BackendCourtshipDiscoveryStatus, u64>,
    pub second_character_id: __sdk::__query_builder::Col<BackendCourtshipDiscoveryStatus, u64>,
    pub discovered_minute:
        __sdk::__query_builder::Col<BackendCourtshipDiscoveryStatus, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for BackendCourtshipDiscoveryStatus {
    type Cols = BackendCourtshipDiscoveryStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendCourtshipDiscoveryStatusCols {
            observer_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "observer_character_id",
            ),
            first_character_id: __sdk::__query_builder::Col::new(table_name, "first_character_id"),
            second_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "second_character_id",
            ),
            discovered_minute: __sdk::__query_builder::Col::new(table_name, "discovered_minute"),
        }
    }
}
