// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_contract_type::BackendContract;
use super::contract_status_type::ContractStatus;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_contracts`.
///
/// Obtain a handle from the [`BackendContractsTableAccess::backend_contracts`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_contracts()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_contracts().on_insert(...)`.
pub struct BackendContractsTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendContract>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_contracts`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendContractsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendContractsTableHandle`], which mediates access to the table `backend_contracts`.
    fn backend_contracts(&self) -> BackendContractsTableHandle<'_>;
}

impl BackendContractsTableAccess for super::RemoteTables {
    fn backend_contracts(&self) -> BackendContractsTableHandle<'_> {
        BackendContractsTableHandle {
            imp: self.imp.get_table::<BackendContract>("backend_contracts"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendContractsInsertCallbackId(__sdk::CallbackId);
pub struct BackendContractsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendContractsTableHandle<'ctx> {
    type Row = BackendContract;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendContract> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendContractsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendContractsInsertCallbackId {
        BackendContractsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendContractsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendContractsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendContractsDeleteCallbackId {
        BackendContractsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendContractsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BackendContract>("backend_contracts");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendContract>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BackendContract>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendContract`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_contractsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendContract`.
    fn backend_contracts(&self) -> __sdk::__query_builder::Table<BackendContract>;
}

impl backend_contractsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_contracts(&self) -> __sdk::__query_builder::Table<BackendContract> {
        __sdk::__query_builder::Table::new("backend_contracts")
    }
}
