// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_physical_evidence_inspection_type::BackendPhysicalEvidenceInspection;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_physical_evidence_inspections`.
///
/// Obtain a handle from the [`BackendPhysicalEvidenceInspectionsTableAccess::backend_physical_evidence_inspections`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_physical_evidence_inspections()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_physical_evidence_inspections().on_insert(...)`.
pub struct BackendPhysicalEvidenceInspectionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendPhysicalEvidenceInspection>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_physical_evidence_inspections`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendPhysicalEvidenceInspectionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendPhysicalEvidenceInspectionsTableHandle`], which mediates access to the table `backend_physical_evidence_inspections`.
    fn backend_physical_evidence_inspections(
        &self,
    ) -> BackendPhysicalEvidenceInspectionsTableHandle<'_>;
}

impl BackendPhysicalEvidenceInspectionsTableAccess for super::RemoteTables {
    fn backend_physical_evidence_inspections(
        &self,
    ) -> BackendPhysicalEvidenceInspectionsTableHandle<'_> {
        BackendPhysicalEvidenceInspectionsTableHandle {
            imp: self.imp.get_table::<BackendPhysicalEvidenceInspection>(
                "backend_physical_evidence_inspections",
            ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendPhysicalEvidenceInspectionsInsertCallbackId(__sdk::CallbackId);
pub struct BackendPhysicalEvidenceInspectionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendPhysicalEvidenceInspectionsTableHandle<'ctx> {
    type Row = BackendPhysicalEvidenceInspection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendPhysicalEvidenceInspection> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendPhysicalEvidenceInspectionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendPhysicalEvidenceInspectionsInsertCallbackId {
        BackendPhysicalEvidenceInspectionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendPhysicalEvidenceInspectionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendPhysicalEvidenceInspectionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendPhysicalEvidenceInspectionsDeleteCallbackId {
        BackendPhysicalEvidenceInspectionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendPhysicalEvidenceInspectionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BackendPhysicalEvidenceInspection>(
        "backend_physical_evidence_inspections",
    );
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendPhysicalEvidenceInspection>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<BackendPhysicalEvidenceInspection>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendPhysicalEvidenceInspection`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_physical_evidence_inspectionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendPhysicalEvidenceInspection`.
    fn backend_physical_evidence_inspections(
        &self,
    ) -> __sdk::__query_builder::Table<BackendPhysicalEvidenceInspection>;
}

impl backend_physical_evidence_inspectionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_physical_evidence_inspections(
        &self,
    ) -> __sdk::__query_builder::Table<BackendPhysicalEvidenceInspection> {
        __sdk::__query_builder::Table::new("backend_physical_evidence_inspections")
    }
}
