// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_death_type::CharacterDeath;
use super::death_cause_type::DeathCause;
use super::death_source_type::DeathSource;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_character_deaths`.
///
/// Obtain a handle from the [`BackendCharacterDeathsTableAccess::backend_character_deaths`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_character_deaths()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_character_deaths().on_insert(...)`.
pub struct BackendCharacterDeathsTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterDeath>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_character_deaths`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendCharacterDeathsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendCharacterDeathsTableHandle`], which mediates access to the table `backend_character_deaths`.
    fn backend_character_deaths(&self) -> BackendCharacterDeathsTableHandle<'_>;
}

impl BackendCharacterDeathsTableAccess for super::RemoteTables {
    fn backend_character_deaths(&self) -> BackendCharacterDeathsTableHandle<'_> {
        BackendCharacterDeathsTableHandle {
            imp: self
                .imp
                .get_table::<CharacterDeath>("backend_character_deaths"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendCharacterDeathsInsertCallbackId(__sdk::CallbackId);
pub struct BackendCharacterDeathsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendCharacterDeathsTableHandle<'ctx> {
    type Row = CharacterDeath;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterDeath> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendCharacterDeathsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterDeathsInsertCallbackId {
        BackendCharacterDeathsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendCharacterDeathsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendCharacterDeathsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterDeathsDeleteCallbackId {
        BackendCharacterDeathsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendCharacterDeathsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterDeath>("backend_character_deaths");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterDeath>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterDeath>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterDeath`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_character_deathsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterDeath`.
    fn backend_character_deaths(&self) -> __sdk::__query_builder::Table<CharacterDeath>;
}

impl backend_character_deathsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_character_deaths(&self) -> __sdk::__query_builder::Table<CharacterDeath> {
        __sdk::__query_builder::Table::new("backend_character_deaths")
    }
}
