// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_time_type::CharacterTime;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_character_times`.
///
/// Obtain a handle from the [`BackendCharacterTimesTableAccess::backend_character_times`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_character_times()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_character_times().on_insert(...)`.
pub struct BackendCharacterTimesTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterTime>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_character_times`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendCharacterTimesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendCharacterTimesTableHandle`], which mediates access to the table `backend_character_times`.
    fn backend_character_times(&self) -> BackendCharacterTimesTableHandle<'_>;
}

impl BackendCharacterTimesTableAccess for super::RemoteTables {
    fn backend_character_times(&self) -> BackendCharacterTimesTableHandle<'_> {
        BackendCharacterTimesTableHandle {
            imp: self
                .imp
                .get_table::<CharacterTime>("backend_character_times"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendCharacterTimesInsertCallbackId(__sdk::CallbackId);
pub struct BackendCharacterTimesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendCharacterTimesTableHandle<'ctx> {
    type Row = CharacterTime;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterTime> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendCharacterTimesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterTimesInsertCallbackId {
        BackendCharacterTimesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendCharacterTimesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendCharacterTimesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterTimesDeleteCallbackId {
        BackendCharacterTimesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendCharacterTimesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterTime>("backend_character_times");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterTime>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterTime>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterTime`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_character_timesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterTime`.
    fn backend_character_times(&self) -> __sdk::__query_builder::Table<CharacterTime>;
}

impl backend_character_timesQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_character_times(&self) -> __sdk::__query_builder::Table<CharacterTime> {
        __sdk::__query_builder::Table::new("backend_character_times")
    }
}
