// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::courtship_kind_type::CourtshipKind;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendCharacterRelationshipStatus {
    pub character_id: u64,
    pub spouse_id: Option<u64>,
    pub courtship_partner_id: Option<u64>,
    pub courtship_kind: Option<CourtshipKind>,
    pub courtship_exposed: bool,
    pub wedding_commitment_id: Option<String>,
    pub wedding_partner_id: Option<u64>,
    pub wedding_effective_minute: Option<StrategicMinute>,
    pub wedding_settlement_id: Option<String>,
    pub pregnancy_due_minute: Option<StrategicMinute>,
    pub pregnancy_child_id: Option<u64>,
}

impl __sdk::InModule for BackendCharacterRelationshipStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendCharacterRelationshipStatus`.
///
/// Provides typed access to columns for query building.
pub struct BackendCharacterRelationshipStatusCols {
    pub character_id: __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, u64>,
    pub spouse_id: __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, Option<u64>>,
    pub courtship_partner_id:
        __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, Option<u64>>,
    pub courtship_kind:
        __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, Option<CourtshipKind>>,
    pub courtship_exposed: __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, bool>,
    pub wedding_commitment_id:
        __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, Option<String>>,
    pub wedding_partner_id:
        __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, Option<u64>>,
    pub wedding_effective_minute:
        __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, Option<StrategicMinute>>,
    pub wedding_settlement_id:
        __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, Option<String>>,
    pub pregnancy_due_minute:
        __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, Option<StrategicMinute>>,
    pub pregnancy_child_id:
        __sdk::__query_builder::Col<BackendCharacterRelationshipStatus, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for BackendCharacterRelationshipStatus {
    type Cols = BackendCharacterRelationshipStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendCharacterRelationshipStatusCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            spouse_id: __sdk::__query_builder::Col::new(table_name, "spouse_id"),
            courtship_partner_id: __sdk::__query_builder::Col::new(
                table_name,
                "courtship_partner_id",
            ),
            courtship_kind: __sdk::__query_builder::Col::new(table_name, "courtship_kind"),
            courtship_exposed: __sdk::__query_builder::Col::new(table_name, "courtship_exposed"),
            wedding_commitment_id: __sdk::__query_builder::Col::new(
                table_name,
                "wedding_commitment_id",
            ),
            wedding_partner_id: __sdk::__query_builder::Col::new(table_name, "wedding_partner_id"),
            wedding_effective_minute: __sdk::__query_builder::Col::new(
                table_name,
                "wedding_effective_minute",
            ),
            wedding_settlement_id: __sdk::__query_builder::Col::new(
                table_name,
                "wedding_settlement_id",
            ),
            pregnancy_due_minute: __sdk::__query_builder::Col::new(
                table_name,
                "pregnancy_due_minute",
            ),
            pregnancy_child_id: __sdk::__query_builder::Col::new(table_name, "pregnancy_child_id"),
        }
    }
}
