// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::body_region_type::BodyRegion;
use super::intervention_route_type::InterventionRoute;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendPhysiologyAdministration {
    pub id: u64,
    pub patient_id: u64,
    pub preparation_id: String,
    pub profile_version: u16,
    pub route: InterventionRoute,
    pub dose_milliunits: u32,
    pub region: Option<BodyRegion>,
    pub administered_at: StrategicMinute,
    pub stopped_at: Option<StrategicMinute>,
}

impl __sdk::InModule for BackendPhysiologyAdministration {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendPhysiologyAdministration`.
///
/// Provides typed access to columns for query building.
pub struct BackendPhysiologyAdministrationCols {
    pub id: __sdk::__query_builder::Col<BackendPhysiologyAdministration, u64>,
    pub patient_id: __sdk::__query_builder::Col<BackendPhysiologyAdministration, u64>,
    pub preparation_id: __sdk::__query_builder::Col<BackendPhysiologyAdministration, String>,
    pub profile_version: __sdk::__query_builder::Col<BackendPhysiologyAdministration, u16>,
    pub route: __sdk::__query_builder::Col<BackendPhysiologyAdministration, InterventionRoute>,
    pub dose_milliunits: __sdk::__query_builder::Col<BackendPhysiologyAdministration, u32>,
    pub region: __sdk::__query_builder::Col<BackendPhysiologyAdministration, Option<BodyRegion>>,
    pub administered_at:
        __sdk::__query_builder::Col<BackendPhysiologyAdministration, StrategicMinute>,
    pub stopped_at:
        __sdk::__query_builder::Col<BackendPhysiologyAdministration, Option<StrategicMinute>>,
}

impl __sdk::__query_builder::HasCols for BackendPhysiologyAdministration {
    type Cols = BackendPhysiologyAdministrationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendPhysiologyAdministrationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            patient_id: __sdk::__query_builder::Col::new(table_name, "patient_id"),
            preparation_id: __sdk::__query_builder::Col::new(table_name, "preparation_id"),
            profile_version: __sdk::__query_builder::Col::new(table_name, "profile_version"),
            route: __sdk::__query_builder::Col::new(table_name, "route"),
            dose_milliunits: __sdk::__query_builder::Col::new(table_name, "dose_milliunits"),
            region: __sdk::__query_builder::Col::new(table_name, "region"),
            administered_at: __sdk::__query_builder::Col::new(table_name, "administered_at"),
            stopped_at: __sdk::__query_builder::Col::new(table_name, "stopped_at"),
        }
    }
}
