// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_physiology_administration_type::BackendPhysiologyAdministration;
use super::body_region_type::BodyRegion;
use super::intervention_route_type::InterventionRoute;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_physiology_administrations`.
///
/// Obtain a handle from the [`BackendPhysiologyAdministrationsTableAccess::backend_physiology_administrations`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_physiology_administrations()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_physiology_administrations().on_insert(...)`.
pub struct BackendPhysiologyAdministrationsTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendPhysiologyAdministration>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_physiology_administrations`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendPhysiologyAdministrationsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendPhysiologyAdministrationsTableHandle`], which mediates access to the table `backend_physiology_administrations`.
    fn backend_physiology_administrations(&self)
    -> BackendPhysiologyAdministrationsTableHandle<'_>;
}

impl BackendPhysiologyAdministrationsTableAccess for super::RemoteTables {
    fn backend_physiology_administrations(
        &self,
    ) -> BackendPhysiologyAdministrationsTableHandle<'_> {
        BackendPhysiologyAdministrationsTableHandle {
            imp: self
                .imp
                .get_table::<BackendPhysiologyAdministration>("backend_physiology_administrations"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendPhysiologyAdministrationsInsertCallbackId(__sdk::CallbackId);
pub struct BackendPhysiologyAdministrationsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendPhysiologyAdministrationsTableHandle<'ctx> {
    type Row = BackendPhysiologyAdministration;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendPhysiologyAdministration> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendPhysiologyAdministrationsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendPhysiologyAdministrationsInsertCallbackId {
        BackendPhysiologyAdministrationsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendPhysiologyAdministrationsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendPhysiologyAdministrationsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendPhysiologyAdministrationsDeleteCallbackId {
        BackendPhysiologyAdministrationsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendPhysiologyAdministrationsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<BackendPhysiologyAdministration>("backend_physiology_administrations");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendPhysiologyAdministration>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<BackendPhysiologyAdministration>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendPhysiologyAdministration`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_physiology_administrationsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendPhysiologyAdministration`.
    fn backend_physiology_administrations(
        &self,
    ) -> __sdk::__query_builder::Table<BackendPhysiologyAdministration>;
}

impl backend_physiology_administrationsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_physiology_administrations(
        &self,
    ) -> __sdk::__query_builder::Table<BackendPhysiologyAdministration> {
        __sdk::__query_builder::Table::new("backend_physiology_administrations")
    }
}
