// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendInvestigationJournalEntry {
    pub owner_character_id: u64,
    pub case_id: String,
    pub record_id: String,
    pub kind: String,
    pub summary: String,
    pub source_label: String,
    pub confidence_bps: u16,
    pub contradiction_group: String,
    pub corrected_by: String,
    pub supersedes: String,
    pub recorded_at: StrategicMinute,
}

impl __sdk::InModule for BackendInvestigationJournalEntry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendInvestigationJournalEntry`.
///
/// Provides typed access to columns for query building.
pub struct BackendInvestigationJournalEntryCols {
    pub owner_character_id: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, u64>,
    pub case_id: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, String>,
    pub record_id: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, String>,
    pub kind: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, String>,
    pub summary: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, String>,
    pub source_label: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, String>,
    pub confidence_bps: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, u16>,
    pub contradiction_group: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, String>,
    pub corrected_by: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, String>,
    pub supersedes: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, String>,
    pub recorded_at: __sdk::__query_builder::Col<BackendInvestigationJournalEntry, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for BackendInvestigationJournalEntry {
    type Cols = BackendInvestigationJournalEntryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendInvestigationJournalEntryCols {
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            record_id: __sdk::__query_builder::Col::new(table_name, "record_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            summary: __sdk::__query_builder::Col::new(table_name, "summary"),
            source_label: __sdk::__query_builder::Col::new(table_name, "source_label"),
            confidence_bps: __sdk::__query_builder::Col::new(table_name, "confidence_bps"),
            contradiction_group: __sdk::__query_builder::Col::new(
                table_name,
                "contradiction_group",
            ),
            corrected_by: __sdk::__query_builder::Col::new(table_name, "corrected_by"),
            supersedes: __sdk::__query_builder::Col::new(table_name, "supersedes"),
            recorded_at: __sdk::__query_builder::Col::new(table_name, "recorded_at"),
        }
    }
}
