// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::case_site_id_type::CaseSiteId;
use super::interaction_presentation_decision_type::InteractionPresentationDecision;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendHostileNegotiation {
    pub owner_character_id: u64,
    pub case_site_id: CaseSiteId,
    pub spokesman_id: u64,
    pub context_ref: String,
    pub expected_revision: u32,
    pub decision: InteractionPresentationDecision,
    pub latest_response: Option<String>,
}

impl __sdk::InModule for BackendHostileNegotiation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendHostileNegotiation`.
///
/// Provides typed access to columns for query building.
pub struct BackendHostileNegotiationCols {
    pub owner_character_id: __sdk::__query_builder::Col<BackendHostileNegotiation, u64>,
    pub case_site_id: __sdk::__query_builder::Col<BackendHostileNegotiation, CaseSiteId>,
    pub spokesman_id: __sdk::__query_builder::Col<BackendHostileNegotiation, u64>,
    pub context_ref: __sdk::__query_builder::Col<BackendHostileNegotiation, String>,
    pub expected_revision: __sdk::__query_builder::Col<BackendHostileNegotiation, u32>,
    pub decision:
        __sdk::__query_builder::Col<BackendHostileNegotiation, InteractionPresentationDecision>,
    pub latest_response: __sdk::__query_builder::Col<BackendHostileNegotiation, Option<String>>,
}

impl __sdk::__query_builder::HasCols for BackendHostileNegotiation {
    type Cols = BackendHostileNegotiationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendHostileNegotiationCols {
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            case_site_id: __sdk::__query_builder::Col::new(table_name, "case_site_id"),
            spokesman_id: __sdk::__query_builder::Col::new(table_name, "spokesman_id"),
            context_ref: __sdk::__query_builder::Col::new(table_name, "context_ref"),
            expected_revision: __sdk::__query_builder::Col::new(table_name, "expected_revision"),
            decision: __sdk::__query_builder::Col::new(table_name, "decision"),
            latest_response: __sdk::__query_builder::Col::new(table_name, "latest_response"),
        }
    }
}
