// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BloodExposureCheckpoint {
    pub id: String,
    pub character_id: u64,
    pub disease_id: String,
    pub evaluated_through: StrategicMinute,
}

impl __sdk::InModule for BloodExposureCheckpoint {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BloodExposureCheckpoint`.
///
/// Provides typed access to columns for query building.
pub struct BloodExposureCheckpointCols {
    pub id: __sdk::__query_builder::Col<BloodExposureCheckpoint, String>,
    pub character_id: __sdk::__query_builder::Col<BloodExposureCheckpoint, u64>,
    pub disease_id: __sdk::__query_builder::Col<BloodExposureCheckpoint, String>,
    pub evaluated_through: __sdk::__query_builder::Col<BloodExposureCheckpoint, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for BloodExposureCheckpoint {
    type Cols = BloodExposureCheckpointCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BloodExposureCheckpointCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            disease_id: __sdk::__query_builder::Col::new(table_name, "disease_id"),
            evaluated_through: __sdk::__query_builder::Col::new(table_name, "evaluated_through"),
        }
    }
}

/// Indexed column accessor struct for the table `BloodExposureCheckpoint`.
///
/// Provides typed access to indexed columns for query building.
pub struct BloodExposureCheckpointIxCols {
    pub id: __sdk::__query_builder::IxCol<BloodExposureCheckpoint, String>,
}

impl __sdk::__query_builder::HasIxCols for BloodExposureCheckpoint {
    type IxCols = BloodExposureCheckpointIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BloodExposureCheckpointIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BloodExposureCheckpoint {}
