// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
#[derive(Copy, Eq, Hash)]
pub enum BuildingUse {
    Dwelling,

    ParishChurch,

    Inn,

    GeneralShop,

    MarketHall,

    Smithy,

    Weaponsmith,

    Armorer,

    Tailor,

    Herbalist,

    Bookshop,

    Bakehouse,

    Brewery,

    Malthouse,

    Butcher,

    Stable,

    Barn,

    Granary,

    HorseMill,

    Cooper,

    Carpenter,

    Wheelwright,

    Cobbler,

    Weaver,

    Tannery,

    Dyer,

    Ropemaker,

    Chandler,

    Potter,

    Stonecutter,

    TimberYard,

    Warehouse,

    WoadStore,

    Fishmonger,

    TownHall,

    WeighHouse,

    Guildhall,

    Hospital,

    Bathhouse,

    School,

    Apothecary,

    PrintingHouse,

    Guardhouse,

    Prison,

    Rectory,

    WaterMill,

    FullingMill,

    PaperMill,

    Sawmill,

    Windmill,

    Cathedral,

    Monastery,

    University,

    Mint,

    CustomsHouse,

    Synagogue,

    Chapel,

    Manor,

    Castle,

    Arsenal,

    SaltWorks,

    Smelter,

    AssayHouse,

    Brickworks,

    Glassworks,

    ExecutionerHouse,
}

impl __sdk::InModule for BuildingUse {
    type Module = super::RemoteModule;
}
