// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CaseReputationParticipant {
    pub id: String,
    pub case_id: String,
    pub character_id: u64,
    pub party_id: String,
    pub captured_at_minute: StrategicMinute,
}

impl __sdk::InModule for CaseReputationParticipant {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CaseReputationParticipant`.
///
/// Provides typed access to columns for query building.
pub struct CaseReputationParticipantCols {
    pub id: __sdk::__query_builder::Col<CaseReputationParticipant, String>,
    pub case_id: __sdk::__query_builder::Col<CaseReputationParticipant, String>,
    pub character_id: __sdk::__query_builder::Col<CaseReputationParticipant, u64>,
    pub party_id: __sdk::__query_builder::Col<CaseReputationParticipant, String>,
    pub captured_at_minute: __sdk::__query_builder::Col<CaseReputationParticipant, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for CaseReputationParticipant {
    type Cols = CaseReputationParticipantCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CaseReputationParticipantCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            captured_at_minute: __sdk::__query_builder::Col::new(table_name, "captured_at_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `CaseReputationParticipant`.
///
/// Provides typed access to indexed columns for query building.
pub struct CaseReputationParticipantIxCols {
    pub case_id: __sdk::__query_builder::IxCol<CaseReputationParticipant, String>,
    pub character_id: __sdk::__query_builder::IxCol<CaseReputationParticipant, u64>,
    pub id: __sdk::__query_builder::IxCol<CaseReputationParticipant, String>,
}

impl __sdk::__query_builder::HasIxCols for CaseReputationParticipant {
    type IxCols = CaseReputationParticipantIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CaseReputationParticipantIxCols {
            case_id: __sdk::__query_builder::IxCol::new(table_name, "case_id"),
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CaseReputationParticipant {}
