// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CaseFinaleExecution {
    pub finale_id: String,
    pub source_id: String,
    pub case_id: String,
    pub party_id: String,
    pub executed_at_minute: StrategicMinute,
}

impl __sdk::InModule for CaseFinaleExecution {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CaseFinaleExecution`.
///
/// Provides typed access to columns for query building.
pub struct CaseFinaleExecutionCols {
    pub finale_id: __sdk::__query_builder::Col<CaseFinaleExecution, String>,
    pub source_id: __sdk::__query_builder::Col<CaseFinaleExecution, String>,
    pub case_id: __sdk::__query_builder::Col<CaseFinaleExecution, String>,
    pub party_id: __sdk::__query_builder::Col<CaseFinaleExecution, String>,
    pub executed_at_minute: __sdk::__query_builder::Col<CaseFinaleExecution, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for CaseFinaleExecution {
    type Cols = CaseFinaleExecutionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CaseFinaleExecutionCols {
            finale_id: __sdk::__query_builder::Col::new(table_name, "finale_id"),
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            executed_at_minute: __sdk::__query_builder::Col::new(table_name, "executed_at_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `CaseFinaleExecution`.
///
/// Provides typed access to indexed columns for query building.
pub struct CaseFinaleExecutionIxCols {
    pub finale_id: __sdk::__query_builder::IxCol<CaseFinaleExecution, String>,
    pub source_id: __sdk::__query_builder::IxCol<CaseFinaleExecution, String>,
}

impl __sdk::__query_builder::HasIxCols for CaseFinaleExecution {
    type IxCols = CaseFinaleExecutionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CaseFinaleExecutionIxCols {
            finale_id: __sdk::__query_builder::IxCol::new(table_name, "finale_id"),
            source_id: __sdk::__query_builder::IxCol::new(table_name, "source_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CaseFinaleExecution {}
