// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::case_site_id_type::CaseSiteId;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterCaseSiteOccupancy {
    pub id: String,
    pub character_id: u64,
    pub gateway_bucket: u8,
    pub case_site_id: CaseSiteId,
    pub entered_at: StrategicMinute,
    pub left_at: Option<StrategicMinute>,
}

impl __sdk::InModule for CharacterCaseSiteOccupancy {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterCaseSiteOccupancy`.
///
/// Provides typed access to columns for query building.
pub struct CharacterCaseSiteOccupancyCols {
    pub id: __sdk::__query_builder::Col<CharacterCaseSiteOccupancy, String>,
    pub character_id: __sdk::__query_builder::Col<CharacterCaseSiteOccupancy, u64>,
    pub gateway_bucket: __sdk::__query_builder::Col<CharacterCaseSiteOccupancy, u8>,
    pub case_site_id: __sdk::__query_builder::Col<CharacterCaseSiteOccupancy, CaseSiteId>,
    pub entered_at: __sdk::__query_builder::Col<CharacterCaseSiteOccupancy, StrategicMinute>,
    pub left_at: __sdk::__query_builder::Col<CharacterCaseSiteOccupancy, Option<StrategicMinute>>,
}

impl __sdk::__query_builder::HasCols for CharacterCaseSiteOccupancy {
    type Cols = CharacterCaseSiteOccupancyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterCaseSiteOccupancyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            gateway_bucket: __sdk::__query_builder::Col::new(table_name, "gateway_bucket"),
            case_site_id: __sdk::__query_builder::Col::new(table_name, "case_site_id"),
            entered_at: __sdk::__query_builder::Col::new(table_name, "entered_at"),
            left_at: __sdk::__query_builder::Col::new(table_name, "left_at"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterCaseSiteOccupancy`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterCaseSiteOccupancyIxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterCaseSiteOccupancy, u64>,
    pub gateway_bucket: __sdk::__query_builder::IxCol<CharacterCaseSiteOccupancy, u8>,
    pub id: __sdk::__query_builder::IxCol<CharacterCaseSiteOccupancy, String>,
}

impl __sdk::__query_builder::HasIxCols for CharacterCaseSiteOccupancy {
    type IxCols = CharacterCaseSiteOccupancyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterCaseSiteOccupancyIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            gateway_bucket: __sdk::__query_builder::IxCol::new(table_name, "gateway_bucket"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterCaseSiteOccupancy {}
