// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterFamiliarity {
    pub id: String,
    pub low_id: u64,
    pub high_id: u64,
    pub shared_minutes: u64,
    pub joint_minute_anchor: StrategicMinute,
}

impl __sdk::InModule for CharacterFamiliarity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterFamiliarity`.
///
/// Provides typed access to columns for query building.
pub struct CharacterFamiliarityCols {
    pub id: __sdk::__query_builder::Col<CharacterFamiliarity, String>,
    pub low_id: __sdk::__query_builder::Col<CharacterFamiliarity, u64>,
    pub high_id: __sdk::__query_builder::Col<CharacterFamiliarity, u64>,
    pub shared_minutes: __sdk::__query_builder::Col<CharacterFamiliarity, u64>,
    pub joint_minute_anchor: __sdk::__query_builder::Col<CharacterFamiliarity, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for CharacterFamiliarity {
    type Cols = CharacterFamiliarityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterFamiliarityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            low_id: __sdk::__query_builder::Col::new(table_name, "low_id"),
            high_id: __sdk::__query_builder::Col::new(table_name, "high_id"),
            shared_minutes: __sdk::__query_builder::Col::new(table_name, "shared_minutes"),
            joint_minute_anchor: __sdk::__query_builder::Col::new(
                table_name,
                "joint_minute_anchor",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterFamiliarity`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterFamiliarityIxCols {
    pub high_id: __sdk::__query_builder::IxCol<CharacterFamiliarity, u64>,
    pub id: __sdk::__query_builder::IxCol<CharacterFamiliarity, String>,
    pub low_id: __sdk::__query_builder::IxCol<CharacterFamiliarity, u64>,
}

impl __sdk::__query_builder::HasIxCols for CharacterFamiliarity {
    type IxCols = CharacterFamiliarityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterFamiliarityIxCols {
            high_id: __sdk::__query_builder::IxCol::new(table_name, "high_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            low_id: __sdk::__query_builder::IxCol::new(table_name, "low_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterFamiliarity {}
