// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_illness_status_type::CharacterIllnessStatus;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_illness_status`.
///
/// Obtain a handle from the [`CharacterIllnessStatusTableAccess::character_illness_status`] method on [`super::RemoteTables`],
/// like `ctx.db.character_illness_status()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_illness_status().on_insert(...)`.
pub struct CharacterIllnessStatusTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterIllnessStatus>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_illness_status`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterIllnessStatusTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterIllnessStatusTableHandle`], which mediates access to the table `character_illness_status`.
    fn character_illness_status(&self) -> CharacterIllnessStatusTableHandle<'_>;
}

impl CharacterIllnessStatusTableAccess for super::RemoteTables {
    fn character_illness_status(&self) -> CharacterIllnessStatusTableHandle<'_> {
        CharacterIllnessStatusTableHandle {
            imp: self
                .imp
                .get_table::<CharacterIllnessStatus>("character_illness_status"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterIllnessStatusInsertCallbackId(__sdk::CallbackId);
pub struct CharacterIllnessStatusDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterIllnessStatusTableHandle<'ctx> {
    type Row = CharacterIllnessStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterIllnessStatus> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterIllnessStatusInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterIllnessStatusInsertCallbackId {
        CharacterIllnessStatusInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterIllnessStatusInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterIllnessStatusDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterIllnessStatusDeleteCallbackId {
        CharacterIllnessStatusDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterIllnessStatusDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CharacterIllnessStatusUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterIllnessStatusTableHandle<'ctx> {
    type UpdateCallbackId = CharacterIllnessStatusUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterIllnessStatusUpdateCallbackId {
        CharacterIllnessStatusUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterIllnessStatusUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `character_id` unique index on the table `character_illness_status`,
/// which allows point queries on the field of the same name
/// via the [`CharacterIllnessStatusCharacterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_illness_status().character_id().find(...)`.
pub struct CharacterIllnessStatusCharacterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterIllnessStatus, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterIllnessStatusTableHandle<'ctx> {
    /// Get a handle on the `character_id` unique index on the table `character_illness_status`.
    pub fn character_id(&self) -> CharacterIllnessStatusCharacterIdUnique<'ctx> {
        CharacterIllnessStatusCharacterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("character_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterIllnessStatusCharacterIdUnique<'ctx> {
    /// Find the subscribed row whose `character_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CharacterIllnessStatus> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<CharacterIllnessStatus>("character_illness_status");
    _table.add_unique_constraint::<u64>("character_id", |row| &row.character_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterIllnessStatus>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterIllnessStatus>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterIllnessStatus`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait character_illness_statusQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterIllnessStatus`.
    fn character_illness_status(&self) -> __sdk::__query_builder::Table<CharacterIllnessStatus>;
}

impl character_illness_statusQueryTableAccess for __sdk::QueryTableAccessor {
    fn character_illness_status(&self) -> __sdk::__query_builder::Table<CharacterIllnessStatus> {
        __sdk::__query_builder::Table::new("character_illness_status")
    }
}
