// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterIllnessStatus {
    pub character_id: u64,
    pub symptomatic: bool,
    pub critical: bool,
    pub updated_at_minute: StrategicMinute,
}

impl __sdk::InModule for CharacterIllnessStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterIllnessStatus`.
///
/// Provides typed access to columns for query building.
pub struct CharacterIllnessStatusCols {
    pub character_id: __sdk::__query_builder::Col<CharacterIllnessStatus, u64>,
    pub symptomatic: __sdk::__query_builder::Col<CharacterIllnessStatus, bool>,
    pub critical: __sdk::__query_builder::Col<CharacterIllnessStatus, bool>,
    pub updated_at_minute: __sdk::__query_builder::Col<CharacterIllnessStatus, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for CharacterIllnessStatus {
    type Cols = CharacterIllnessStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterIllnessStatusCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            symptomatic: __sdk::__query_builder::Col::new(table_name, "symptomatic"),
            critical: __sdk::__query_builder::Col::new(table_name, "critical"),
            updated_at_minute: __sdk::__query_builder::Col::new(table_name, "updated_at_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterIllnessStatus`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterIllnessStatusIxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterIllnessStatus, u64>,
}

impl __sdk::__query_builder::HasIxCols for CharacterIllnessStatus {
    type IxCols = CharacterIllnessStatusIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterIllnessStatusIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterIllnessStatus {}
