// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::character_custodian_kind_type::CharacterCustodianKind;
use super::character_custody_status_type::CharacterCustodyStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterCustody {
    pub character_id: u64,
    pub observer_party_id: String,
    pub status: CharacterCustodyStatus,
    pub custodian_kind: CharacterCustodianKind,
    pub custodian_id: String,
    pub version: u32,
    pub source_id: String,
    pub context_id: String,
    pub case_id: Option<String>,
    pub ransom_minor: Option<u64>,
}

impl __sdk::InModule for CharacterCustody {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterCustody`.
///
/// Provides typed access to columns for query building.
pub struct CharacterCustodyCols {
    pub character_id: __sdk::__query_builder::Col<CharacterCustody, u64>,
    pub observer_party_id: __sdk::__query_builder::Col<CharacterCustody, String>,
    pub status: __sdk::__query_builder::Col<CharacterCustody, CharacterCustodyStatus>,
    pub custodian_kind: __sdk::__query_builder::Col<CharacterCustody, CharacterCustodianKind>,
    pub custodian_id: __sdk::__query_builder::Col<CharacterCustody, String>,
    pub version: __sdk::__query_builder::Col<CharacterCustody, u32>,
    pub source_id: __sdk::__query_builder::Col<CharacterCustody, String>,
    pub context_id: __sdk::__query_builder::Col<CharacterCustody, String>,
    pub case_id: __sdk::__query_builder::Col<CharacterCustody, Option<String>>,
    pub ransom_minor: __sdk::__query_builder::Col<CharacterCustody, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for CharacterCustody {
    type Cols = CharacterCustodyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterCustodyCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            observer_party_id: __sdk::__query_builder::Col::new(table_name, "observer_party_id"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            custodian_kind: __sdk::__query_builder::Col::new(table_name, "custodian_kind"),
            custodian_id: __sdk::__query_builder::Col::new(table_name, "custodian_id"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            context_id: __sdk::__query_builder::Col::new(table_name, "context_id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            ransom_minor: __sdk::__query_builder::Col::new(table_name, "ransom_minor"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterCustody`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterCustodyIxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterCustody, u64>,
    pub observer_party_id: __sdk::__query_builder::IxCol<CharacterCustody, String>,
}

impl __sdk::__query_builder::HasIxCols for CharacterCustody {
    type IxCols = CharacterCustodyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterCustodyIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            observer_party_id: __sdk::__query_builder::IxCol::new(table_name, "observer_party_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterCustody {}
