// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::death_cause_type::DeathCause;
use super::death_source_type::DeathSource;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterDeath {
    pub character_id: u64,
    pub cause: DeathCause,
    pub source: DeathSource,
    pub source_id: Option<String>,
    pub strategic_minute: StrategicMinute,
}

impl __sdk::InModule for CharacterDeath {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterDeath`.
///
/// Provides typed access to columns for query building.
pub struct CharacterDeathCols {
    pub character_id: __sdk::__query_builder::Col<CharacterDeath, u64>,
    pub cause: __sdk::__query_builder::Col<CharacterDeath, DeathCause>,
    pub source: __sdk::__query_builder::Col<CharacterDeath, DeathSource>,
    pub source_id: __sdk::__query_builder::Col<CharacterDeath, Option<String>>,
    pub strategic_minute: __sdk::__query_builder::Col<CharacterDeath, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for CharacterDeath {
    type Cols = CharacterDeathCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterDeathCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            cause: __sdk::__query_builder::Col::new(table_name, "cause"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            strategic_minute: __sdk::__query_builder::Col::new(table_name, "strategic_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterDeath`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterDeathIxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterDeath, u64>,
}

impl __sdk::__query_builder::HasIxCols for CharacterDeath {
    type IxCols = CharacterDeathIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterDeathIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterDeath {}
