// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::disposition_kind_type::DispositionKind;
use super::surrender_obligation_type::SurrenderObligation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterContextDispositionAuthority {
    pub id: String,
    pub context_id: String,
    pub character_id: u64,
    pub disposition: DispositionKind,
    pub revision: u32,
    pub obligations: Vec<SurrenderObligation>,
    pub refusal_count: u16,
    pub last_source_id: String,
}

impl __sdk::InModule for CharacterContextDispositionAuthority {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterContextDispositionAuthority`.
///
/// Provides typed access to columns for query building.
pub struct CharacterContextDispositionAuthorityCols {
    pub id: __sdk::__query_builder::Col<CharacterContextDispositionAuthority, String>,
    pub context_id: __sdk::__query_builder::Col<CharacterContextDispositionAuthority, String>,
    pub character_id: __sdk::__query_builder::Col<CharacterContextDispositionAuthority, u64>,
    pub disposition:
        __sdk::__query_builder::Col<CharacterContextDispositionAuthority, DispositionKind>,
    pub revision: __sdk::__query_builder::Col<CharacterContextDispositionAuthority, u32>,
    pub obligations:
        __sdk::__query_builder::Col<CharacterContextDispositionAuthority, Vec<SurrenderObligation>>,
    pub refusal_count: __sdk::__query_builder::Col<CharacterContextDispositionAuthority, u16>,
    pub last_source_id: __sdk::__query_builder::Col<CharacterContextDispositionAuthority, String>,
}

impl __sdk::__query_builder::HasCols for CharacterContextDispositionAuthority {
    type Cols = CharacterContextDispositionAuthorityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterContextDispositionAuthorityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            context_id: __sdk::__query_builder::Col::new(table_name, "context_id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            disposition: __sdk::__query_builder::Col::new(table_name, "disposition"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            obligations: __sdk::__query_builder::Col::new(table_name, "obligations"),
            refusal_count: __sdk::__query_builder::Col::new(table_name, "refusal_count"),
            last_source_id: __sdk::__query_builder::Col::new(table_name, "last_source_id"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterContextDispositionAuthority`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterContextDispositionAuthorityIxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterContextDispositionAuthority, u64>,
    pub context_id: __sdk::__query_builder::IxCol<CharacterContextDispositionAuthority, String>,
    pub id: __sdk::__query_builder::IxCol<CharacterContextDispositionAuthority, String>,
}

impl __sdk::__query_builder::HasIxCols for CharacterContextDispositionAuthority {
    type IxCols = CharacterContextDispositionAuthorityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterContextDispositionAuthorityIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            context_id: __sdk::__query_builder::IxCol::new(table_name, "context_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterContextDispositionAuthority {}
