// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::seed_type::Seed;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimSimulationRunArgs {
    pub bootstrap_token: String,
    pub nonce: String,
    pub policy_seed: Seed,
}

impl From<ClaimSimulationRunArgs> for super::Reducer {
    fn from(args: ClaimSimulationRunArgs) -> Self {
        Self::ClaimSimulationRun {
            bootstrap_token: args.bootstrap_token,
            nonce: args.nonce,
            policy_seed: args.policy_seed,
        }
    }
}

impl __sdk::InModule for ClaimSimulationRunArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_simulation_run`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_simulation_run {
    /// Request that the remote module invoke the reducer `claim_simulation_run` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_simulation_run:claim_simulation_run_then`] to run a callback after the reducer completes.
    fn claim_simulation_run(
        &self,
        bootstrap_token: String,
        nonce: String,
        policy_seed: Seed,
    ) -> __sdk::Result<()> {
        self.claim_simulation_run_then(bootstrap_token, nonce, policy_seed, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_simulation_run` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_simulation_run_then(
        &self,
        bootstrap_token: String,
        nonce: String,
        policy_seed: Seed,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_simulation_run for super::RemoteReducers {
    fn claim_simulation_run_then(
        &self,
        bootstrap_token: String,
        nonce: String,
        policy_seed: Seed,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ClaimSimulationRunArgs {
                bootstrap_token,
                nonce,
                policy_seed,
            },
            callback,
        )
    }
}
