// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::commitment_status_type::CommitmentStatus;
use super::commitment_terminal_reason_type::CommitmentTerminalReason;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CommitmentEvent {
    pub id: String,
    pub commitment_id: String,
    pub status: CommitmentStatus,
    pub reason: Option<CommitmentTerminalReason>,
    pub minute: StrategicMinute,
}

impl __sdk::InModule for CommitmentEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CommitmentEvent`.
///
/// Provides typed access to columns for query building.
pub struct CommitmentEventCols {
    pub id: __sdk::__query_builder::Col<CommitmentEvent, String>,
    pub commitment_id: __sdk::__query_builder::Col<CommitmentEvent, String>,
    pub status: __sdk::__query_builder::Col<CommitmentEvent, CommitmentStatus>,
    pub reason: __sdk::__query_builder::Col<CommitmentEvent, Option<CommitmentTerminalReason>>,
    pub minute: __sdk::__query_builder::Col<CommitmentEvent, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for CommitmentEvent {
    type Cols = CommitmentEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CommitmentEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            commitment_id: __sdk::__query_builder::Col::new(table_name, "commitment_id"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            minute: __sdk::__query_builder::Col::new(table_name, "minute"),
        }
    }
}

/// Indexed column accessor struct for the table `CommitmentEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct CommitmentEventIxCols {
    pub commitment_id: __sdk::__query_builder::IxCol<CommitmentEvent, String>,
    pub id: __sdk::__query_builder::IxCol<CommitmentEvent, String>,
}

impl __sdk::__query_builder::HasIxCols for CommitmentEvent {
    type IxCols = CommitmentEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CommitmentEventIxCols {
            commitment_id: __sdk::__query_builder::IxCol::new(table_name, "commitment_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CommitmentEvent {}
