// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ContainerWaterContribution {
    pub material_lot_id: u64,
    pub container_object_id: u64,
    pub amount_microliters: u64,
    pub contaminant_load_microunits: u64,
    pub collected_at: StrategicMinute,
}

impl __sdk::InModule for ContainerWaterContribution {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ContainerWaterContribution`.
///
/// Provides typed access to columns for query building.
pub struct ContainerWaterContributionCols {
    pub material_lot_id: __sdk::__query_builder::Col<ContainerWaterContribution, u64>,
    pub container_object_id: __sdk::__query_builder::Col<ContainerWaterContribution, u64>,
    pub amount_microliters: __sdk::__query_builder::Col<ContainerWaterContribution, u64>,
    pub contaminant_load_microunits: __sdk::__query_builder::Col<ContainerWaterContribution, u64>,
    pub collected_at: __sdk::__query_builder::Col<ContainerWaterContribution, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for ContainerWaterContribution {
    type Cols = ContainerWaterContributionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContainerWaterContributionCols {
            material_lot_id: __sdk::__query_builder::Col::new(table_name, "material_lot_id"),
            container_object_id: __sdk::__query_builder::Col::new(
                table_name,
                "container_object_id",
            ),
            amount_microliters: __sdk::__query_builder::Col::new(table_name, "amount_microliters"),
            contaminant_load_microunits: __sdk::__query_builder::Col::new(
                table_name,
                "contaminant_load_microunits",
            ),
            collected_at: __sdk::__query_builder::Col::new(table_name, "collected_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ContainerWaterContribution`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContainerWaterContributionIxCols {
    pub container_object_id: __sdk::__query_builder::IxCol<ContainerWaterContribution, u64>,
    pub material_lot_id: __sdk::__query_builder::IxCol<ContainerWaterContribution, u64>,
}

impl __sdk::__query_builder::HasIxCols for ContainerWaterContribution {
    type IxCols = ContainerWaterContributionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContainerWaterContributionIxCols {
            container_object_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "container_object_id",
            ),
            material_lot_id: __sdk::__query_builder::IxCol::new(table_name, "material_lot_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ContainerWaterContribution {}
