// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::contract_interaction_stage_type::ContractInteractionStage;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ContractIssuerInteractionReceipt {
    pub id: String,
    pub contract_id: String,
    pub party_id: String,
    pub stage: ContractInteractionStage,
    pub issuer_resident_character_id: u64,
    pub interacting_character_id: u64,
    pub interacted_at_minute: StrategicMinute,
    pub dialogue_session_id: String,
    pub dialogue_action_id: String,
    pub dialogue_revision: u64,
    pub location_id: String,
    pub consumed: bool,
}

impl __sdk::InModule for ContractIssuerInteractionReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ContractIssuerInteractionReceipt`.
///
/// Provides typed access to columns for query building.
pub struct ContractIssuerInteractionReceiptCols {
    pub id: __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, String>,
    pub contract_id: __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, String>,
    pub party_id: __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, String>,
    pub stage:
        __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, ContractInteractionStage>,
    pub issuer_resident_character_id:
        __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, u64>,
    pub interacting_character_id:
        __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, u64>,
    pub interacted_at_minute:
        __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, StrategicMinute>,
    pub dialogue_session_id: __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, String>,
    pub dialogue_action_id: __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, String>,
    pub dialogue_revision: __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, u64>,
    pub location_id: __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, String>,
    pub consumed: __sdk::__query_builder::Col<ContractIssuerInteractionReceipt, bool>,
}

impl __sdk::__query_builder::HasCols for ContractIssuerInteractionReceipt {
    type Cols = ContractIssuerInteractionReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContractIssuerInteractionReceiptCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            contract_id: __sdk::__query_builder::Col::new(table_name, "contract_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            stage: __sdk::__query_builder::Col::new(table_name, "stage"),
            issuer_resident_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "issuer_resident_character_id",
            ),
            interacting_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "interacting_character_id",
            ),
            interacted_at_minute: __sdk::__query_builder::Col::new(
                table_name,
                "interacted_at_minute",
            ),
            dialogue_session_id: __sdk::__query_builder::Col::new(
                table_name,
                "dialogue_session_id",
            ),
            dialogue_action_id: __sdk::__query_builder::Col::new(table_name, "dialogue_action_id"),
            dialogue_revision: __sdk::__query_builder::Col::new(table_name, "dialogue_revision"),
            location_id: __sdk::__query_builder::Col::new(table_name, "location_id"),
            consumed: __sdk::__query_builder::Col::new(table_name, "consumed"),
        }
    }
}

/// Indexed column accessor struct for the table `ContractIssuerInteractionReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContractIssuerInteractionReceiptIxCols {
    pub id: __sdk::__query_builder::IxCol<ContractIssuerInteractionReceipt, String>,
}

impl __sdk::__query_builder::HasIxCols for ContractIssuerInteractionReceipt {
    type IxCols = ContractIssuerInteractionReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContractIssuerInteractionReceiptIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ContractIssuerInteractionReceipt {}
