// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::corpse_permission_scope_type::CorpsePermissionScope;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CorpsePermissionAttempt {
    pub id: String,
    pub corpse_id: String,
    pub party_id: String,
    pub resident_character_id: u64,
    pub scope: CorpsePermissionScope,
    pub approach: String,
    pub granted: bool,
    pub attempted_minute: StrategicMinute,
}

impl __sdk::InModule for CorpsePermissionAttempt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CorpsePermissionAttempt`.
///
/// Provides typed access to columns for query building.
pub struct CorpsePermissionAttemptCols {
    pub id: __sdk::__query_builder::Col<CorpsePermissionAttempt, String>,
    pub corpse_id: __sdk::__query_builder::Col<CorpsePermissionAttempt, String>,
    pub party_id: __sdk::__query_builder::Col<CorpsePermissionAttempt, String>,
    pub resident_character_id: __sdk::__query_builder::Col<CorpsePermissionAttempt, u64>,
    pub scope: __sdk::__query_builder::Col<CorpsePermissionAttempt, CorpsePermissionScope>,
    pub approach: __sdk::__query_builder::Col<CorpsePermissionAttempt, String>,
    pub granted: __sdk::__query_builder::Col<CorpsePermissionAttempt, bool>,
    pub attempted_minute: __sdk::__query_builder::Col<CorpsePermissionAttempt, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for CorpsePermissionAttempt {
    type Cols = CorpsePermissionAttemptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CorpsePermissionAttemptCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            corpse_id: __sdk::__query_builder::Col::new(table_name, "corpse_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            resident_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "resident_character_id",
            ),
            scope: __sdk::__query_builder::Col::new(table_name, "scope"),
            approach: __sdk::__query_builder::Col::new(table_name, "approach"),
            granted: __sdk::__query_builder::Col::new(table_name, "granted"),
            attempted_minute: __sdk::__query_builder::Col::new(table_name, "attempted_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `CorpsePermissionAttempt`.
///
/// Provides typed access to indexed columns for query building.
pub struct CorpsePermissionAttemptIxCols {
    pub corpse_id: __sdk::__query_builder::IxCol<CorpsePermissionAttempt, String>,
    pub id: __sdk::__query_builder::IxCol<CorpsePermissionAttempt, String>,
    pub party_id: __sdk::__query_builder::IxCol<CorpsePermissionAttempt, String>,
}

impl __sdk::__query_builder::HasIxCols for CorpsePermissionAttempt {
    type IxCols = CorpsePermissionAttemptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CorpsePermissionAttemptIxCols {
            corpse_id: __sdk::__query_builder::IxCol::new(table_name, "corpse_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CorpsePermissionAttempt {}
