// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::witness_claim_resolution_type::WitnessClaimResolution;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DialogueWitnessClaim {
    pub challenge_token: String,
    pub session_id: String,
    pub observer_character_id: u64,
    pub resident_character_id: u64,
    pub event_sequence: u32,
    pub claim_order: u32,
    pub proposition_id: String,
    pub displayed_text: String,
    pub charm_response: Option<String>,
    pub command_response: Option<String>,
    pub bluff_response: Option<String>,
    pub claim_is_factually_accurate: bool,
    pub demeanor_truth_signal: f32,
    pub assessment_direction: String,
    pub assessment_strength: f32,
    pub resolution: Option<WitnessClaimResolution>,
}

impl __sdk::InModule for DialogueWitnessClaim {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DialogueWitnessClaim`.
///
/// Provides typed access to columns for query building.
pub struct DialogueWitnessClaimCols {
    pub challenge_token: __sdk::__query_builder::Col<DialogueWitnessClaim, String>,
    pub session_id: __sdk::__query_builder::Col<DialogueWitnessClaim, String>,
    pub observer_character_id: __sdk::__query_builder::Col<DialogueWitnessClaim, u64>,
    pub resident_character_id: __sdk::__query_builder::Col<DialogueWitnessClaim, u64>,
    pub event_sequence: __sdk::__query_builder::Col<DialogueWitnessClaim, u32>,
    pub claim_order: __sdk::__query_builder::Col<DialogueWitnessClaim, u32>,
    pub proposition_id: __sdk::__query_builder::Col<DialogueWitnessClaim, String>,
    pub displayed_text: __sdk::__query_builder::Col<DialogueWitnessClaim, String>,
    pub charm_response: __sdk::__query_builder::Col<DialogueWitnessClaim, Option<String>>,
    pub command_response: __sdk::__query_builder::Col<DialogueWitnessClaim, Option<String>>,
    pub bluff_response: __sdk::__query_builder::Col<DialogueWitnessClaim, Option<String>>,
    pub claim_is_factually_accurate: __sdk::__query_builder::Col<DialogueWitnessClaim, bool>,
    pub demeanor_truth_signal: __sdk::__query_builder::Col<DialogueWitnessClaim, f32>,
    pub assessment_direction: __sdk::__query_builder::Col<DialogueWitnessClaim, String>,
    pub assessment_strength: __sdk::__query_builder::Col<DialogueWitnessClaim, f32>,
    pub resolution:
        __sdk::__query_builder::Col<DialogueWitnessClaim, Option<WitnessClaimResolution>>,
}

impl __sdk::__query_builder::HasCols for DialogueWitnessClaim {
    type Cols = DialogueWitnessClaimCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DialogueWitnessClaimCols {
            challenge_token: __sdk::__query_builder::Col::new(table_name, "challenge_token"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            observer_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "observer_character_id",
            ),
            resident_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "resident_character_id",
            ),
            event_sequence: __sdk::__query_builder::Col::new(table_name, "event_sequence"),
            claim_order: __sdk::__query_builder::Col::new(table_name, "claim_order"),
            proposition_id: __sdk::__query_builder::Col::new(table_name, "proposition_id"),
            displayed_text: __sdk::__query_builder::Col::new(table_name, "displayed_text"),
            charm_response: __sdk::__query_builder::Col::new(table_name, "charm_response"),
            command_response: __sdk::__query_builder::Col::new(table_name, "command_response"),
            bluff_response: __sdk::__query_builder::Col::new(table_name, "bluff_response"),
            claim_is_factually_accurate: __sdk::__query_builder::Col::new(
                table_name,
                "claim_is_factually_accurate",
            ),
            demeanor_truth_signal: __sdk::__query_builder::Col::new(
                table_name,
                "demeanor_truth_signal",
            ),
            assessment_direction: __sdk::__query_builder::Col::new(
                table_name,
                "assessment_direction",
            ),
            assessment_strength: __sdk::__query_builder::Col::new(
                table_name,
                "assessment_strength",
            ),
            resolution: __sdk::__query_builder::Col::new(table_name, "resolution"),
        }
    }
}

/// Indexed column accessor struct for the table `DialogueWitnessClaim`.
///
/// Provides typed access to indexed columns for query building.
pub struct DialogueWitnessClaimIxCols {
    pub challenge_token: __sdk::__query_builder::IxCol<DialogueWitnessClaim, String>,
    pub observer_character_id: __sdk::__query_builder::IxCol<DialogueWitnessClaim, u64>,
    pub session_id: __sdk::__query_builder::IxCol<DialogueWitnessClaim, String>,
}

impl __sdk::__query_builder::HasIxCols for DialogueWitnessClaim {
    type IxCols = DialogueWitnessClaimIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DialogueWitnessClaimIxCols {
            challenge_token: __sdk::__query_builder::IxCol::new(table_name, "challenge_token"),
            observer_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "observer_character_id",
            ),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DialogueWitnessClaim {}
