// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DiscoveredOffense {
    pub id: String,
    pub character_id: u64,
    pub settlement_id: String,
    pub kind: String,
    pub severity: u8,
    pub execution_eligible: bool,
    pub occurred_at_minute: StrategicMinute,
    pub settled: bool,
}

impl __sdk::InModule for DiscoveredOffense {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DiscoveredOffense`.
///
/// Provides typed access to columns for query building.
pub struct DiscoveredOffenseCols {
    pub id: __sdk::__query_builder::Col<DiscoveredOffense, String>,
    pub character_id: __sdk::__query_builder::Col<DiscoveredOffense, u64>,
    pub settlement_id: __sdk::__query_builder::Col<DiscoveredOffense, String>,
    pub kind: __sdk::__query_builder::Col<DiscoveredOffense, String>,
    pub severity: __sdk::__query_builder::Col<DiscoveredOffense, u8>,
    pub execution_eligible: __sdk::__query_builder::Col<DiscoveredOffense, bool>,
    pub occurred_at_minute: __sdk::__query_builder::Col<DiscoveredOffense, StrategicMinute>,
    pub settled: __sdk::__query_builder::Col<DiscoveredOffense, bool>,
}

impl __sdk::__query_builder::HasCols for DiscoveredOffense {
    type Cols = DiscoveredOffenseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DiscoveredOffenseCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            severity: __sdk::__query_builder::Col::new(table_name, "severity"),
            execution_eligible: __sdk::__query_builder::Col::new(table_name, "execution_eligible"),
            occurred_at_minute: __sdk::__query_builder::Col::new(table_name, "occurred_at_minute"),
            settled: __sdk::__query_builder::Col::new(table_name, "settled"),
        }
    }
}

/// Indexed column accessor struct for the table `DiscoveredOffense`.
///
/// Provides typed access to indexed columns for query building.
pub struct DiscoveredOffenseIxCols {
    pub character_id: __sdk::__query_builder::IxCol<DiscoveredOffense, u64>,
    pub id: __sdk::__query_builder::IxCol<DiscoveredOffense, String>,
    pub settlement_id: __sdk::__query_builder::IxCol<DiscoveredOffense, String>,
}

impl __sdk::__query_builder::HasIxCols for DiscoveredOffense {
    type IxCols = DiscoveredOffenseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DiscoveredOffenseIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            settlement_id: __sdk::__query_builder::IxCol::new(table_name, "settlement_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DiscoveredOffense {}
