// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EscapeCharacterCustodyArgs {
    pub actor_id: u64,
    pub character_id: u64,
    pub expected_version: u32,
    pub source_id: String,
}

impl From<EscapeCharacterCustodyArgs> for super::Reducer {
    fn from(args: EscapeCharacterCustodyArgs) -> Self {
        Self::EscapeCharacterCustody {
            actor_id: args.actor_id,
            character_id: args.character_id,
            expected_version: args.expected_version,
            source_id: args.source_id,
        }
    }
}

impl __sdk::InModule for EscapeCharacterCustodyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `escape_character_custody`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait escape_character_custody {
    /// Request that the remote module invoke the reducer `escape_character_custody` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`escape_character_custody:escape_character_custody_then`] to run a callback after the reducer completes.
    fn escape_character_custody(
        &self,
        actor_id: u64,
        character_id: u64,
        expected_version: u32,
        source_id: String,
    ) -> __sdk::Result<()> {
        self.escape_character_custody_then(
            actor_id,
            character_id,
            expected_version,
            source_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `escape_character_custody` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn escape_character_custody_then(
        &self,
        actor_id: u64,
        character_id: u64,
        expected_version: u32,
        source_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl escape_character_custody for super::RemoteReducers {
    fn escape_character_custody_then(
        &self,
        actor_id: u64,
        character_id: u64,
        expected_version: u32,
        source_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EscapeCharacterCustodyArgs {
                actor_id,
                character_id,
                expected_version,
                source_id,
            },
            callback,
        )
    }
}
