// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::food_lot_type::FoodLot;
use super::food_preparation_type::FoodPreparation;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `food_lot`.
///
/// Obtain a handle from the [`FoodLotTableAccess::food_lot`] method on [`super::RemoteTables`],
/// like `ctx.db.food_lot()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.food_lot().on_insert(...)`.
pub struct FoodLotTableHandle<'ctx> {
    imp: __sdk::TableHandle<FoodLot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `food_lot`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FoodLotTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FoodLotTableHandle`], which mediates access to the table `food_lot`.
    fn food_lot(&self) -> FoodLotTableHandle<'_>;
}

impl FoodLotTableAccess for super::RemoteTables {
    fn food_lot(&self) -> FoodLotTableHandle<'_> {
        FoodLotTableHandle {
            imp: self.imp.get_table::<FoodLot>("food_lot"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FoodLotInsertCallbackId(__sdk::CallbackId);
pub struct FoodLotDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FoodLotTableHandle<'ctx> {
    type Row = FoodLot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FoodLot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FoodLotInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FoodLotInsertCallbackId {
        FoodLotInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FoodLotInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FoodLotDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FoodLotDeleteCallbackId {
        FoodLotDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FoodLotDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FoodLotUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FoodLotTableHandle<'ctx> {
    type UpdateCallbackId = FoodLotUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FoodLotUpdateCallbackId {
        FoodLotUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FoodLotUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `food_lot`,
/// which allows point queries on the field of the same name
/// via the [`FoodLotIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.food_lot().id().find(...)`.
pub struct FoodLotIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FoodLot, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FoodLotTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `food_lot`.
    pub fn id(&self) -> FoodLotIdUnique<'ctx> {
        FoodLotIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FoodLotIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<FoodLot> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FoodLot>("food_lot");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FoodLot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FoodLot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FoodLot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait food_lotQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FoodLot`.
    fn food_lot(&self) -> __sdk::__query_builder::Table<FoodLot>;
}

impl food_lotQueryTableAccess for __sdk::QueryTableAccessor {
    fn food_lot(&self) -> __sdk::__query_builder::Table<FoodLot> {
        __sdk::__query_builder::Table::new("food_lot")
    }
}
