// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GeneratedProblemIncident {
    pub id: String,
    pub case_id: String,
    pub problem_id: String,
    pub ordinal: u16,
    pub occurred_at: StrategicMinute,
    pub event_id: String,
    pub proposition_id: String,
    pub witness_resident_character_id: u64,
    pub victim_resident_character_id: u64,
    pub circumstance: String,
    pub site_id: String,
    pub evidence_id: String,
    pub evidence_kind: String,
    pub public_summary: String,
    pub witness_account: String,
}

impl __sdk::InModule for GeneratedProblemIncident {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GeneratedProblemIncident`.
///
/// Provides typed access to columns for query building.
pub struct GeneratedProblemIncidentCols {
    pub id: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
    pub case_id: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
    pub problem_id: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
    pub ordinal: __sdk::__query_builder::Col<GeneratedProblemIncident, u16>,
    pub occurred_at: __sdk::__query_builder::Col<GeneratedProblemIncident, StrategicMinute>,
    pub event_id: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
    pub proposition_id: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
    pub witness_resident_character_id: __sdk::__query_builder::Col<GeneratedProblemIncident, u64>,
    pub victim_resident_character_id: __sdk::__query_builder::Col<GeneratedProblemIncident, u64>,
    pub circumstance: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
    pub site_id: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
    pub evidence_id: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
    pub evidence_kind: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
    pub public_summary: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
    pub witness_account: __sdk::__query_builder::Col<GeneratedProblemIncident, String>,
}

impl __sdk::__query_builder::HasCols for GeneratedProblemIncident {
    type Cols = GeneratedProblemIncidentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GeneratedProblemIncidentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            problem_id: __sdk::__query_builder::Col::new(table_name, "problem_id"),
            ordinal: __sdk::__query_builder::Col::new(table_name, "ordinal"),
            occurred_at: __sdk::__query_builder::Col::new(table_name, "occurred_at"),
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            proposition_id: __sdk::__query_builder::Col::new(table_name, "proposition_id"),
            witness_resident_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "witness_resident_character_id",
            ),
            victim_resident_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "victim_resident_character_id",
            ),
            circumstance: __sdk::__query_builder::Col::new(table_name, "circumstance"),
            site_id: __sdk::__query_builder::Col::new(table_name, "site_id"),
            evidence_id: __sdk::__query_builder::Col::new(table_name, "evidence_id"),
            evidence_kind: __sdk::__query_builder::Col::new(table_name, "evidence_kind"),
            public_summary: __sdk::__query_builder::Col::new(table_name, "public_summary"),
            witness_account: __sdk::__query_builder::Col::new(table_name, "witness_account"),
        }
    }
}

/// Indexed column accessor struct for the table `GeneratedProblemIncident`.
///
/// Provides typed access to indexed columns for query building.
pub struct GeneratedProblemIncidentIxCols {
    pub case_id: __sdk::__query_builder::IxCol<GeneratedProblemIncident, String>,
    pub id: __sdk::__query_builder::IxCol<GeneratedProblemIncident, String>,
    pub problem_id: __sdk::__query_builder::IxCol<GeneratedProblemIncident, String>,
}

impl __sdk::__query_builder::HasIxCols for GeneratedProblemIncident {
    type IxCols = GeneratedProblemIncidentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GeneratedProblemIncidentIxCols {
            case_id: __sdk::__query_builder::IxCol::new(table_name, "case_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            problem_id: __sdk::__query_builder::IxCol::new(table_name, "problem_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GeneratedProblemIncident {}
