// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GeneratedResidentHome {
    pub character_id: u64,
    pub property_id: String,
}

impl __sdk::InModule for GeneratedResidentHome {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GeneratedResidentHome`.
///
/// Provides typed access to columns for query building.
pub struct GeneratedResidentHomeCols {
    pub character_id: __sdk::__query_builder::Col<GeneratedResidentHome, u64>,
    pub property_id: __sdk::__query_builder::Col<GeneratedResidentHome, String>,
}

impl __sdk::__query_builder::HasCols for GeneratedResidentHome {
    type Cols = GeneratedResidentHomeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GeneratedResidentHomeCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            property_id: __sdk::__query_builder::Col::new(table_name, "property_id"),
        }
    }
}

/// Indexed column accessor struct for the table `GeneratedResidentHome`.
///
/// Provides typed access to indexed columns for query building.
pub struct GeneratedResidentHomeIxCols {
    pub character_id: __sdk::__query_builder::IxCol<GeneratedResidentHome, u64>,
}

impl __sdk::__query_builder::HasIxCols for GeneratedResidentHome {
    type IxCols = GeneratedResidentHomeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GeneratedResidentHomeIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GeneratedResidentHome {}
