// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InvestigationReceivedTestimony {
    pub id: String,
    pub owner_character_id: u64,
    pub public_case_id: String,
    pub claim_id: String,
    pub witness_ref: String,
    pub source_receipt_id: String,
    pub received_at: StrategicMinute,
}

impl __sdk::InModule for InvestigationReceivedTestimony {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InvestigationReceivedTestimony`.
///
/// Provides typed access to columns for query building.
pub struct InvestigationReceivedTestimonyCols {
    pub id: __sdk::__query_builder::Col<InvestigationReceivedTestimony, String>,
    pub owner_character_id: __sdk::__query_builder::Col<InvestigationReceivedTestimony, u64>,
    pub public_case_id: __sdk::__query_builder::Col<InvestigationReceivedTestimony, String>,
    pub claim_id: __sdk::__query_builder::Col<InvestigationReceivedTestimony, String>,
    pub witness_ref: __sdk::__query_builder::Col<InvestigationReceivedTestimony, String>,
    pub source_receipt_id: __sdk::__query_builder::Col<InvestigationReceivedTestimony, String>,
    pub received_at: __sdk::__query_builder::Col<InvestigationReceivedTestimony, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for InvestigationReceivedTestimony {
    type Cols = InvestigationReceivedTestimonyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InvestigationReceivedTestimonyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            public_case_id: __sdk::__query_builder::Col::new(table_name, "public_case_id"),
            claim_id: __sdk::__query_builder::Col::new(table_name, "claim_id"),
            witness_ref: __sdk::__query_builder::Col::new(table_name, "witness_ref"),
            source_receipt_id: __sdk::__query_builder::Col::new(table_name, "source_receipt_id"),
            received_at: __sdk::__query_builder::Col::new(table_name, "received_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InvestigationReceivedTestimony`.
///
/// Provides typed access to indexed columns for query building.
pub struct InvestigationReceivedTestimonyIxCols {
    pub id: __sdk::__query_builder::IxCol<InvestigationReceivedTestimony, String>,
    pub owner_character_id: __sdk::__query_builder::IxCol<InvestigationReceivedTestimony, u64>,
    pub public_case_id: __sdk::__query_builder::IxCol<InvestigationReceivedTestimony, String>,
}

impl __sdk::__query_builder::HasIxCols for InvestigationReceivedTestimony {
    type IxCols = InvestigationReceivedTestimonyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InvestigationReceivedTestimonyIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "owner_character_id",
            ),
            public_case_id: __sdk::__query_builder::IxCol::new(table_name, "public_case_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InvestigationReceivedTestimony {}
