// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InvestigationBestiaryDiagnosticReceipt {
    pub id: String,
    pub owner_character_id: u64,
    pub public_case_id: String,
    pub diagnostic_kind: String,
    pub interpretation: String,
    pub learned_at: StrategicMinute,
}

impl __sdk::InModule for InvestigationBestiaryDiagnosticReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InvestigationBestiaryDiagnosticReceipt`.
///
/// Provides typed access to columns for query building.
pub struct InvestigationBestiaryDiagnosticReceiptCols {
    pub id: __sdk::__query_builder::Col<InvestigationBestiaryDiagnosticReceipt, String>,
    pub owner_character_id:
        __sdk::__query_builder::Col<InvestigationBestiaryDiagnosticReceipt, u64>,
    pub public_case_id: __sdk::__query_builder::Col<InvestigationBestiaryDiagnosticReceipt, String>,
    pub diagnostic_kind:
        __sdk::__query_builder::Col<InvestigationBestiaryDiagnosticReceipt, String>,
    pub interpretation: __sdk::__query_builder::Col<InvestigationBestiaryDiagnosticReceipt, String>,
    pub learned_at:
        __sdk::__query_builder::Col<InvestigationBestiaryDiagnosticReceipt, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for InvestigationBestiaryDiagnosticReceipt {
    type Cols = InvestigationBestiaryDiagnosticReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InvestigationBestiaryDiagnosticReceiptCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            public_case_id: __sdk::__query_builder::Col::new(table_name, "public_case_id"),
            diagnostic_kind: __sdk::__query_builder::Col::new(table_name, "diagnostic_kind"),
            interpretation: __sdk::__query_builder::Col::new(table_name, "interpretation"),
            learned_at: __sdk::__query_builder::Col::new(table_name, "learned_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InvestigationBestiaryDiagnosticReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct InvestigationBestiaryDiagnosticReceiptIxCols {
    pub id: __sdk::__query_builder::IxCol<InvestigationBestiaryDiagnosticReceipt, String>,
    pub owner_character_id:
        __sdk::__query_builder::IxCol<InvestigationBestiaryDiagnosticReceipt, u64>,
    pub public_case_id:
        __sdk::__query_builder::IxCol<InvestigationBestiaryDiagnosticReceipt, String>,
}

impl __sdk::__query_builder::HasIxCols for InvestigationBestiaryDiagnosticReceipt {
    type IxCols = InvestigationBestiaryDiagnosticReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InvestigationBestiaryDiagnosticReceiptIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "owner_character_id",
            ),
            public_case_id: __sdk::__query_builder::IxCol::new(table_name, "public_case_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InvestigationBestiaryDiagnosticReceipt {}
