// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::investigation_provenance_kind_type::InvestigationProvenanceKind;
use super::investigation_target_kind_type::InvestigationTargetKind;
use super::seed_type::Seed;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InvestigationActionCapability {
    pub id: String,
    pub owner_character_id: u64,
    pub case_id: String,
    pub provenance_kind: InvestigationProvenanceKind,
    pub generated_case_id: String,
    pub method: String,
    pub version: u32,
    pub target_kind: InvestigationTargetKind,
    pub target_id: String,
    pub target_terrain: String,
    pub seed: Seed,
    pub evidence_age_origin_minute: StrategicMinute,
    pub uncertainty_bps: u16,
    pub safe_summary: String,
    pub known_prerequisites: String,
    pub safe_result_on_success: String,
    pub consequence_json: String,
    pub required_action_id: String,
    pub alternate_route_action_id: String,
    pub active: bool,
}

impl __sdk::InModule for InvestigationActionCapability {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InvestigationActionCapability`.
///
/// Provides typed access to columns for query building.
pub struct InvestigationActionCapabilityCols {
    pub id: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub owner_character_id: __sdk::__query_builder::Col<InvestigationActionCapability, u64>,
    pub case_id: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub provenance_kind:
        __sdk::__query_builder::Col<InvestigationActionCapability, InvestigationProvenanceKind>,
    pub generated_case_id: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub method: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub version: __sdk::__query_builder::Col<InvestigationActionCapability, u32>,
    pub target_kind:
        __sdk::__query_builder::Col<InvestigationActionCapability, InvestigationTargetKind>,
    pub target_id: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub target_terrain: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub seed: __sdk::__query_builder::Col<InvestigationActionCapability, Seed>,
    pub evidence_age_origin_minute:
        __sdk::__query_builder::Col<InvestigationActionCapability, StrategicMinute>,
    pub uncertainty_bps: __sdk::__query_builder::Col<InvestigationActionCapability, u16>,
    pub safe_summary: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub known_prerequisites: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub safe_result_on_success: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub consequence_json: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub required_action_id: __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub alternate_route_action_id:
        __sdk::__query_builder::Col<InvestigationActionCapability, String>,
    pub active: __sdk::__query_builder::Col<InvestigationActionCapability, bool>,
}

impl __sdk::__query_builder::HasCols for InvestigationActionCapability {
    type Cols = InvestigationActionCapabilityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InvestigationActionCapabilityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            provenance_kind: __sdk::__query_builder::Col::new(table_name, "provenance_kind"),
            generated_case_id: __sdk::__query_builder::Col::new(table_name, "generated_case_id"),
            method: __sdk::__query_builder::Col::new(table_name, "method"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            target_kind: __sdk::__query_builder::Col::new(table_name, "target_kind"),
            target_id: __sdk::__query_builder::Col::new(table_name, "target_id"),
            target_terrain: __sdk::__query_builder::Col::new(table_name, "target_terrain"),
            seed: __sdk::__query_builder::Col::new(table_name, "seed"),
            evidence_age_origin_minute: __sdk::__query_builder::Col::new(
                table_name,
                "evidence_age_origin_minute",
            ),
            uncertainty_bps: __sdk::__query_builder::Col::new(table_name, "uncertainty_bps"),
            safe_summary: __sdk::__query_builder::Col::new(table_name, "safe_summary"),
            known_prerequisites: __sdk::__query_builder::Col::new(
                table_name,
                "known_prerequisites",
            ),
            safe_result_on_success: __sdk::__query_builder::Col::new(
                table_name,
                "safe_result_on_success",
            ),
            consequence_json: __sdk::__query_builder::Col::new(table_name, "consequence_json"),
            required_action_id: __sdk::__query_builder::Col::new(table_name, "required_action_id"),
            alternate_route_action_id: __sdk::__query_builder::Col::new(
                table_name,
                "alternate_route_action_id",
            ),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
        }
    }
}

/// Indexed column accessor struct for the table `InvestigationActionCapability`.
///
/// Provides typed access to indexed columns for query building.
pub struct InvestigationActionCapabilityIxCols {
    pub case_id: __sdk::__query_builder::IxCol<InvestigationActionCapability, String>,
    pub id: __sdk::__query_builder::IxCol<InvestigationActionCapability, String>,
    pub owner_character_id: __sdk::__query_builder::IxCol<InvestigationActionCapability, u64>,
}

impl __sdk::__query_builder::HasIxCols for InvestigationActionCapability {
    type IxCols = InvestigationActionCapabilityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InvestigationActionCapabilityIxCols {
            case_id: __sdk::__query_builder::IxCol::new(table_name, "case_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "owner_character_id",
            ),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InvestigationActionCapability {}
