// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InvestigationClaim {
    pub id: String,
    pub case_id: String,
    pub proposition_id: String,
    pub hidden_speaker_ref: String,
    pub statement: String,
    pub confidence_bps: u16,
    pub disclosure_stage: String,
    pub transmission_stage: String,
    pub received_at: StrategicMinute,
    pub public_case_id: String,
    pub safe_source_label: String,
    pub conflict_group: String,
}

impl __sdk::InModule for InvestigationClaim {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InvestigationClaim`.
///
/// Provides typed access to columns for query building.
pub struct InvestigationClaimCols {
    pub id: __sdk::__query_builder::Col<InvestigationClaim, String>,
    pub case_id: __sdk::__query_builder::Col<InvestigationClaim, String>,
    pub proposition_id: __sdk::__query_builder::Col<InvestigationClaim, String>,
    pub hidden_speaker_ref: __sdk::__query_builder::Col<InvestigationClaim, String>,
    pub statement: __sdk::__query_builder::Col<InvestigationClaim, String>,
    pub confidence_bps: __sdk::__query_builder::Col<InvestigationClaim, u16>,
    pub disclosure_stage: __sdk::__query_builder::Col<InvestigationClaim, String>,
    pub transmission_stage: __sdk::__query_builder::Col<InvestigationClaim, String>,
    pub received_at: __sdk::__query_builder::Col<InvestigationClaim, StrategicMinute>,
    pub public_case_id: __sdk::__query_builder::Col<InvestigationClaim, String>,
    pub safe_source_label: __sdk::__query_builder::Col<InvestigationClaim, String>,
    pub conflict_group: __sdk::__query_builder::Col<InvestigationClaim, String>,
}

impl __sdk::__query_builder::HasCols for InvestigationClaim {
    type Cols = InvestigationClaimCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InvestigationClaimCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            proposition_id: __sdk::__query_builder::Col::new(table_name, "proposition_id"),
            hidden_speaker_ref: __sdk::__query_builder::Col::new(table_name, "hidden_speaker_ref"),
            statement: __sdk::__query_builder::Col::new(table_name, "statement"),
            confidence_bps: __sdk::__query_builder::Col::new(table_name, "confidence_bps"),
            disclosure_stage: __sdk::__query_builder::Col::new(table_name, "disclosure_stage"),
            transmission_stage: __sdk::__query_builder::Col::new(table_name, "transmission_stage"),
            received_at: __sdk::__query_builder::Col::new(table_name, "received_at"),
            public_case_id: __sdk::__query_builder::Col::new(table_name, "public_case_id"),
            safe_source_label: __sdk::__query_builder::Col::new(table_name, "safe_source_label"),
            conflict_group: __sdk::__query_builder::Col::new(table_name, "conflict_group"),
        }
    }
}

/// Indexed column accessor struct for the table `InvestigationClaim`.
///
/// Provides typed access to indexed columns for query building.
pub struct InvestigationClaimIxCols {
    pub case_id: __sdk::__query_builder::IxCol<InvestigationClaim, String>,
    pub id: __sdk::__query_builder::IxCol<InvestigationClaim, String>,
}

impl __sdk::__query_builder::HasIxCols for InvestigationClaim {
    type IxCols = InvestigationClaimIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InvestigationClaimIxCols {
            case_id: __sdk::__query_builder::IxCol::new(table_name, "case_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InvestigationClaim {}
