// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InvestigationBestiaryDeduction {
    pub id: String,
    pub owner_character_id: u64,
    pub public_case_id: String,
    pub threat_id: String,
    pub support_band: String,
    pub provenance_json: String,
    pub updated_at: StrategicMinute,
}

impl __sdk::InModule for InvestigationBestiaryDeduction {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InvestigationBestiaryDeduction`.
///
/// Provides typed access to columns for query building.
pub struct InvestigationBestiaryDeductionCols {
    pub id: __sdk::__query_builder::Col<InvestigationBestiaryDeduction, String>,
    pub owner_character_id: __sdk::__query_builder::Col<InvestigationBestiaryDeduction, u64>,
    pub public_case_id: __sdk::__query_builder::Col<InvestigationBestiaryDeduction, String>,
    pub threat_id: __sdk::__query_builder::Col<InvestigationBestiaryDeduction, String>,
    pub support_band: __sdk::__query_builder::Col<InvestigationBestiaryDeduction, String>,
    pub provenance_json: __sdk::__query_builder::Col<InvestigationBestiaryDeduction, String>,
    pub updated_at: __sdk::__query_builder::Col<InvestigationBestiaryDeduction, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for InvestigationBestiaryDeduction {
    type Cols = InvestigationBestiaryDeductionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InvestigationBestiaryDeductionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            public_case_id: __sdk::__query_builder::Col::new(table_name, "public_case_id"),
            threat_id: __sdk::__query_builder::Col::new(table_name, "threat_id"),
            support_band: __sdk::__query_builder::Col::new(table_name, "support_band"),
            provenance_json: __sdk::__query_builder::Col::new(table_name, "provenance_json"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InvestigationBestiaryDeduction`.
///
/// Provides typed access to indexed columns for query building.
pub struct InvestigationBestiaryDeductionIxCols {
    pub id: __sdk::__query_builder::IxCol<InvestigationBestiaryDeduction, String>,
    pub owner_character_id: __sdk::__query_builder::IxCol<InvestigationBestiaryDeduction, u64>,
    pub public_case_id: __sdk::__query_builder::IxCol<InvestigationBestiaryDeduction, String>,
}

impl __sdk::__query_builder::HasIxCols for InvestigationBestiaryDeduction {
    type IxCols = InvestigationBestiaryDeductionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InvestigationBestiaryDeductionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "owner_character_id",
            ),
            public_case_id: __sdk::__query_builder::IxCol::new(table_name, "public_case_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InvestigationBestiaryDeduction {}
