// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::lifecycle_event_kind_type::LifecycleEventKind;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LifecycleEventFailure {
    pub id: String,
    pub event_kind: LifecycleEventKind,
    pub event_id: String,
    pub effective_minute: StrategicMinute,
    pub recorded_minute: StrategicMinute,
    pub error: String,
}

impl __sdk::InModule for LifecycleEventFailure {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LifecycleEventFailure`.
///
/// Provides typed access to columns for query building.
pub struct LifecycleEventFailureCols {
    pub id: __sdk::__query_builder::Col<LifecycleEventFailure, String>,
    pub event_kind: __sdk::__query_builder::Col<LifecycleEventFailure, LifecycleEventKind>,
    pub event_id: __sdk::__query_builder::Col<LifecycleEventFailure, String>,
    pub effective_minute: __sdk::__query_builder::Col<LifecycleEventFailure, StrategicMinute>,
    pub recorded_minute: __sdk::__query_builder::Col<LifecycleEventFailure, StrategicMinute>,
    pub error: __sdk::__query_builder::Col<LifecycleEventFailure, String>,
}

impl __sdk::__query_builder::HasCols for LifecycleEventFailure {
    type Cols = LifecycleEventFailureCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LifecycleEventFailureCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            event_kind: __sdk::__query_builder::Col::new(table_name, "event_kind"),
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            effective_minute: __sdk::__query_builder::Col::new(table_name, "effective_minute"),
            recorded_minute: __sdk::__query_builder::Col::new(table_name, "recorded_minute"),
            error: __sdk::__query_builder::Col::new(table_name, "error"),
        }
    }
}

/// Indexed column accessor struct for the table `LifecycleEventFailure`.
///
/// Provides typed access to indexed columns for query building.
pub struct LifecycleEventFailureIxCols {
    pub id: __sdk::__query_builder::IxCol<LifecycleEventFailure, String>,
}

impl __sdk::__query_builder::HasIxCols for LifecycleEventFailure {
    type IxCols = LifecycleEventFailureIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LifecycleEventFailureIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LifecycleEventFailure {}
