// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::body_region_type::BodyRegion;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LimbInjury {
    pub id: String,
    pub character_id: u64,
    pub limb: BodyRegion,
    pub cut_damage: f32,
    pub bruise_damage: f32,
    pub frostbite_damage: f32,
    pub fracture_damage: f32,
    pub bandaged: bool,
    pub stitched: bool,
    pub stitch_quality: f32,
    pub splint_owner_id: Option<u64>,
    pub splint_inventory_item_id: Option<u64>,
    pub infection_exposure: f32,
    pub infection_checks: u32,
    pub infection_origin_minute: Option<StrategicMinute>,
}

impl __sdk::InModule for LimbInjury {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LimbInjury`.
///
/// Provides typed access to columns for query building.
pub struct LimbInjuryCols {
    pub id: __sdk::__query_builder::Col<LimbInjury, String>,
    pub character_id: __sdk::__query_builder::Col<LimbInjury, u64>,
    pub limb: __sdk::__query_builder::Col<LimbInjury, BodyRegion>,
    pub cut_damage: __sdk::__query_builder::Col<LimbInjury, f32>,
    pub bruise_damage: __sdk::__query_builder::Col<LimbInjury, f32>,
    pub frostbite_damage: __sdk::__query_builder::Col<LimbInjury, f32>,
    pub fracture_damage: __sdk::__query_builder::Col<LimbInjury, f32>,
    pub bandaged: __sdk::__query_builder::Col<LimbInjury, bool>,
    pub stitched: __sdk::__query_builder::Col<LimbInjury, bool>,
    pub stitch_quality: __sdk::__query_builder::Col<LimbInjury, f32>,
    pub splint_owner_id: __sdk::__query_builder::Col<LimbInjury, Option<u64>>,
    pub splint_inventory_item_id: __sdk::__query_builder::Col<LimbInjury, Option<u64>>,
    pub infection_exposure: __sdk::__query_builder::Col<LimbInjury, f32>,
    pub infection_checks: __sdk::__query_builder::Col<LimbInjury, u32>,
    pub infection_origin_minute: __sdk::__query_builder::Col<LimbInjury, Option<StrategicMinute>>,
}

impl __sdk::__query_builder::HasCols for LimbInjury {
    type Cols = LimbInjuryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LimbInjuryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            limb: __sdk::__query_builder::Col::new(table_name, "limb"),
            cut_damage: __sdk::__query_builder::Col::new(table_name, "cut_damage"),
            bruise_damage: __sdk::__query_builder::Col::new(table_name, "bruise_damage"),
            frostbite_damage: __sdk::__query_builder::Col::new(table_name, "frostbite_damage"),
            fracture_damage: __sdk::__query_builder::Col::new(table_name, "fracture_damage"),
            bandaged: __sdk::__query_builder::Col::new(table_name, "bandaged"),
            stitched: __sdk::__query_builder::Col::new(table_name, "stitched"),
            stitch_quality: __sdk::__query_builder::Col::new(table_name, "stitch_quality"),
            splint_owner_id: __sdk::__query_builder::Col::new(table_name, "splint_owner_id"),
            splint_inventory_item_id: __sdk::__query_builder::Col::new(
                table_name,
                "splint_inventory_item_id",
            ),
            infection_exposure: __sdk::__query_builder::Col::new(table_name, "infection_exposure"),
            infection_checks: __sdk::__query_builder::Col::new(table_name, "infection_checks"),
            infection_origin_minute: __sdk::__query_builder::Col::new(
                table_name,
                "infection_origin_minute",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `LimbInjury`.
///
/// Provides typed access to indexed columns for query building.
pub struct LimbInjuryIxCols {
    pub character_id: __sdk::__query_builder::IxCol<LimbInjury, u64>,
    pub id: __sdk::__query_builder::IxCol<LimbInjury, String>,
}

impl __sdk::__query_builder::HasIxCols for LimbInjury {
    type IxCols = LimbInjuryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LimbInjuryIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LimbInjury {}
