// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::marriage_status_type::MarriageStatus;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Marriage {
    pub id: String,
    pub first_character_id: u64,
    pub second_character_id: u64,
    pub commitment_id: String,
    pub household_id: String,
    pub ceremony_settlement_id: String,
    pub married_minute: StrategicMinute,
    pub status: MarriageStatus,
    pub resolved_minute: Option<StrategicMinute>,
}

impl __sdk::InModule for Marriage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Marriage`.
///
/// Provides typed access to columns for query building.
pub struct MarriageCols {
    pub id: __sdk::__query_builder::Col<Marriage, String>,
    pub first_character_id: __sdk::__query_builder::Col<Marriage, u64>,
    pub second_character_id: __sdk::__query_builder::Col<Marriage, u64>,
    pub commitment_id: __sdk::__query_builder::Col<Marriage, String>,
    pub household_id: __sdk::__query_builder::Col<Marriage, String>,
    pub ceremony_settlement_id: __sdk::__query_builder::Col<Marriage, String>,
    pub married_minute: __sdk::__query_builder::Col<Marriage, StrategicMinute>,
    pub status: __sdk::__query_builder::Col<Marriage, MarriageStatus>,
    pub resolved_minute: __sdk::__query_builder::Col<Marriage, Option<StrategicMinute>>,
}

impl __sdk::__query_builder::HasCols for Marriage {
    type Cols = MarriageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MarriageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            first_character_id: __sdk::__query_builder::Col::new(table_name, "first_character_id"),
            second_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "second_character_id",
            ),
            commitment_id: __sdk::__query_builder::Col::new(table_name, "commitment_id"),
            household_id: __sdk::__query_builder::Col::new(table_name, "household_id"),
            ceremony_settlement_id: __sdk::__query_builder::Col::new(
                table_name,
                "ceremony_settlement_id",
            ),
            married_minute: __sdk::__query_builder::Col::new(table_name, "married_minute"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            resolved_minute: __sdk::__query_builder::Col::new(table_name, "resolved_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `Marriage`.
///
/// Provides typed access to indexed columns for query building.
pub struct MarriageIxCols {
    pub first_character_id: __sdk::__query_builder::IxCol<Marriage, u64>,
    pub id: __sdk::__query_builder::IxCol<Marriage, String>,
    pub second_character_id: __sdk::__query_builder::IxCol<Marriage, u64>,
}

impl __sdk::__query_builder::HasIxCols for Marriage {
    type IxCols = MarriageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MarriageIxCols {
            first_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "first_character_id",
            ),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            second_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "second_character_id",
            ),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Marriage {}
