// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::case_site_id_type::CaseSiteId;
use super::hostile_resolution_kind_type::HostileResolutionKind;
use super::mission_attempt_status_type::MissionAttemptStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MissionAuthority {
    pub id: String,
    pub party_id: String,
    pub case_site_id: Option<CaseSiteId>,
    pub hostile_group_id: Option<String>,
    pub observer_character_id: u64,
    pub case_id: String,
    pub outcome_entropy: u64,
    pub status: MissionAttemptStatus,
    pub committed_resolution: Option<HostileResolutionKind>,
    pub committed_capture_subject_id: Option<String>,
    pub committed_capture_custody_version: Option<u32>,
    pub scene_key: String,
    pub hostile_version: u16,
    pub enemy_character_ids: Vec<u64>,
    pub contacted_before_combat: bool,
    pub enemy_difficulty: i32,
    pub enemy_combat_scale_bps: u32,
    pub normalized_combat_power: u32,
    pub drop_item_id: Option<String>,
    pub drop_quantity: u32,
}

impl __sdk::InModule for MissionAuthority {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MissionAuthority`.
///
/// Provides typed access to columns for query building.
pub struct MissionAuthorityCols {
    pub id: __sdk::__query_builder::Col<MissionAuthority, String>,
    pub party_id: __sdk::__query_builder::Col<MissionAuthority, String>,
    pub case_site_id: __sdk::__query_builder::Col<MissionAuthority, Option<CaseSiteId>>,
    pub hostile_group_id: __sdk::__query_builder::Col<MissionAuthority, Option<String>>,
    pub observer_character_id: __sdk::__query_builder::Col<MissionAuthority, u64>,
    pub case_id: __sdk::__query_builder::Col<MissionAuthority, String>,
    pub outcome_entropy: __sdk::__query_builder::Col<MissionAuthority, u64>,
    pub status: __sdk::__query_builder::Col<MissionAuthority, MissionAttemptStatus>,
    pub committed_resolution:
        __sdk::__query_builder::Col<MissionAuthority, Option<HostileResolutionKind>>,
    pub committed_capture_subject_id: __sdk::__query_builder::Col<MissionAuthority, Option<String>>,
    pub committed_capture_custody_version:
        __sdk::__query_builder::Col<MissionAuthority, Option<u32>>,
    pub scene_key: __sdk::__query_builder::Col<MissionAuthority, String>,
    pub hostile_version: __sdk::__query_builder::Col<MissionAuthority, u16>,
    pub enemy_character_ids: __sdk::__query_builder::Col<MissionAuthority, Vec<u64>>,
    pub contacted_before_combat: __sdk::__query_builder::Col<MissionAuthority, bool>,
    pub enemy_difficulty: __sdk::__query_builder::Col<MissionAuthority, i32>,
    pub enemy_combat_scale_bps: __sdk::__query_builder::Col<MissionAuthority, u32>,
    pub normalized_combat_power: __sdk::__query_builder::Col<MissionAuthority, u32>,
    pub drop_item_id: __sdk::__query_builder::Col<MissionAuthority, Option<String>>,
    pub drop_quantity: __sdk::__query_builder::Col<MissionAuthority, u32>,
}

impl __sdk::__query_builder::HasCols for MissionAuthority {
    type Cols = MissionAuthorityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MissionAuthorityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            case_site_id: __sdk::__query_builder::Col::new(table_name, "case_site_id"),
            hostile_group_id: __sdk::__query_builder::Col::new(table_name, "hostile_group_id"),
            observer_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "observer_character_id",
            ),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            outcome_entropy: __sdk::__query_builder::Col::new(table_name, "outcome_entropy"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            committed_resolution: __sdk::__query_builder::Col::new(
                table_name,
                "committed_resolution",
            ),
            committed_capture_subject_id: __sdk::__query_builder::Col::new(
                table_name,
                "committed_capture_subject_id",
            ),
            committed_capture_custody_version: __sdk::__query_builder::Col::new(
                table_name,
                "committed_capture_custody_version",
            ),
            scene_key: __sdk::__query_builder::Col::new(table_name, "scene_key"),
            hostile_version: __sdk::__query_builder::Col::new(table_name, "hostile_version"),
            enemy_character_ids: __sdk::__query_builder::Col::new(
                table_name,
                "enemy_character_ids",
            ),
            contacted_before_combat: __sdk::__query_builder::Col::new(
                table_name,
                "contacted_before_combat",
            ),
            enemy_difficulty: __sdk::__query_builder::Col::new(table_name, "enemy_difficulty"),
            enemy_combat_scale_bps: __sdk::__query_builder::Col::new(
                table_name,
                "enemy_combat_scale_bps",
            ),
            normalized_combat_power: __sdk::__query_builder::Col::new(
                table_name,
                "normalized_combat_power",
            ),
            drop_item_id: __sdk::__query_builder::Col::new(table_name, "drop_item_id"),
            drop_quantity: __sdk::__query_builder::Col::new(table_name, "drop_quantity"),
        }
    }
}

/// Indexed column accessor struct for the table `MissionAuthority`.
///
/// Provides typed access to indexed columns for query building.
pub struct MissionAuthorityIxCols {
    pub id: __sdk::__query_builder::IxCol<MissionAuthority, String>,
    pub party_id: __sdk::__query_builder::IxCol<MissionAuthority, String>,
}

impl __sdk::__query_builder::HasIxCols for MissionAuthority {
    type IxCols = MissionAuthorityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MissionAuthorityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MissionAuthority {}
