// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcAdventuringPartyAuthority {
    pub id: String,
    pub settlement_id: String,
    pub name: String,
    pub member_resident_character_ids_json: String,
    pub capability: u16,
    pub available_at: StrategicMinute,
}

impl __sdk::InModule for NpcAdventuringPartyAuthority {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcAdventuringPartyAuthority`.
///
/// Provides typed access to columns for query building.
pub struct NpcAdventuringPartyAuthorityCols {
    pub id: __sdk::__query_builder::Col<NpcAdventuringPartyAuthority, String>,
    pub settlement_id: __sdk::__query_builder::Col<NpcAdventuringPartyAuthority, String>,
    pub name: __sdk::__query_builder::Col<NpcAdventuringPartyAuthority, String>,
    pub member_resident_character_ids_json:
        __sdk::__query_builder::Col<NpcAdventuringPartyAuthority, String>,
    pub capability: __sdk::__query_builder::Col<NpcAdventuringPartyAuthority, u16>,
    pub available_at: __sdk::__query_builder::Col<NpcAdventuringPartyAuthority, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for NpcAdventuringPartyAuthority {
    type Cols = NpcAdventuringPartyAuthorityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcAdventuringPartyAuthorityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            member_resident_character_ids_json: __sdk::__query_builder::Col::new(
                table_name,
                "member_resident_character_ids_json",
            ),
            capability: __sdk::__query_builder::Col::new(table_name, "capability"),
            available_at: __sdk::__query_builder::Col::new(table_name, "available_at"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcAdventuringPartyAuthority`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcAdventuringPartyAuthorityIxCols {
    pub id: __sdk::__query_builder::IxCol<NpcAdventuringPartyAuthority, String>,
    pub settlement_id: __sdk::__query_builder::IxCol<NpcAdventuringPartyAuthority, String>,
}

impl __sdk::__query_builder::HasIxCols for NpcAdventuringPartyAuthority {
    type IxCols = NpcAdventuringPartyAuthorityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcAdventuringPartyAuthorityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            settlement_id: __sdk::__query_builder::IxCol::new(table_name, "settlement_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcAdventuringPartyAuthority {}
