// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::organization_membership_status_type::OrganizationMembershipStatus;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OrganizationMembership {
    pub id: u64,
    pub character_id: u64,
    pub organization_id: String,
    pub joined_minute: StrategicMinute,
    pub dues_paid_through_minute: StrategicMinute,
    pub status: OrganizationMembershipStatus,
    pub apprenticeship_minutes_accrued: u64,
    pub practice_minutes_accrued: u64,
}

impl __sdk::InModule for OrganizationMembership {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OrganizationMembership`.
///
/// Provides typed access to columns for query building.
pub struct OrganizationMembershipCols {
    pub id: __sdk::__query_builder::Col<OrganizationMembership, u64>,
    pub character_id: __sdk::__query_builder::Col<OrganizationMembership, u64>,
    pub organization_id: __sdk::__query_builder::Col<OrganizationMembership, String>,
    pub joined_minute: __sdk::__query_builder::Col<OrganizationMembership, StrategicMinute>,
    pub dues_paid_through_minute:
        __sdk::__query_builder::Col<OrganizationMembership, StrategicMinute>,
    pub status: __sdk::__query_builder::Col<OrganizationMembership, OrganizationMembershipStatus>,
    pub apprenticeship_minutes_accrued: __sdk::__query_builder::Col<OrganizationMembership, u64>,
    pub practice_minutes_accrued: __sdk::__query_builder::Col<OrganizationMembership, u64>,
}

impl __sdk::__query_builder::HasCols for OrganizationMembership {
    type Cols = OrganizationMembershipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OrganizationMembershipCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            joined_minute: __sdk::__query_builder::Col::new(table_name, "joined_minute"),
            dues_paid_through_minute: __sdk::__query_builder::Col::new(
                table_name,
                "dues_paid_through_minute",
            ),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            apprenticeship_minutes_accrued: __sdk::__query_builder::Col::new(
                table_name,
                "apprenticeship_minutes_accrued",
            ),
            practice_minutes_accrued: __sdk::__query_builder::Col::new(
                table_name,
                "practice_minutes_accrued",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `OrganizationMembership`.
///
/// Provides typed access to indexed columns for query building.
pub struct OrganizationMembershipIxCols {
    pub character_id: __sdk::__query_builder::IxCol<OrganizationMembership, u64>,
    pub id: __sdk::__query_builder::IxCol<OrganizationMembership, u64>,
}

impl __sdk::__query_builder::HasIxCols for OrganizationMembership {
    type IxCols = OrganizationMembershipIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OrganizationMembershipIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OrganizationMembership {}
