// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OutbreakSourcePresenceSpan {
    pub id: String,
    pub character_id: u64,
    pub source_place_id: String,
    pub started_at: StrategicMinute,
    pub ended_at: Option<StrategicMinute>,
}

impl __sdk::InModule for OutbreakSourcePresenceSpan {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OutbreakSourcePresenceSpan`.
///
/// Provides typed access to columns for query building.
pub struct OutbreakSourcePresenceSpanCols {
    pub id: __sdk::__query_builder::Col<OutbreakSourcePresenceSpan, String>,
    pub character_id: __sdk::__query_builder::Col<OutbreakSourcePresenceSpan, u64>,
    pub source_place_id: __sdk::__query_builder::Col<OutbreakSourcePresenceSpan, String>,
    pub started_at: __sdk::__query_builder::Col<OutbreakSourcePresenceSpan, StrategicMinute>,
    pub ended_at: __sdk::__query_builder::Col<OutbreakSourcePresenceSpan, Option<StrategicMinute>>,
}

impl __sdk::__query_builder::HasCols for OutbreakSourcePresenceSpan {
    type Cols = OutbreakSourcePresenceSpanCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OutbreakSourcePresenceSpanCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            source_place_id: __sdk::__query_builder::Col::new(table_name, "source_place_id"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            ended_at: __sdk::__query_builder::Col::new(table_name, "ended_at"),
        }
    }
}

/// Indexed column accessor struct for the table `OutbreakSourcePresenceSpan`.
///
/// Provides typed access to indexed columns for query building.
pub struct OutbreakSourcePresenceSpanIxCols {
    pub character_id: __sdk::__query_builder::IxCol<OutbreakSourcePresenceSpan, u64>,
    pub id: __sdk::__query_builder::IxCol<OutbreakSourcePresenceSpan, String>,
    pub source_place_id: __sdk::__query_builder::IxCol<OutbreakSourcePresenceSpan, String>,
}

impl __sdk::__query_builder::HasIxCols for OutbreakSourcePresenceSpan {
    type IxCols = OutbreakSourcePresenceSpanIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OutbreakSourcePresenceSpanIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            source_place_id: __sdk::__query_builder::IxCol::new(table_name, "source_place_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OutbreakSourcePresenceSpan {}
