// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OutbreakWaterSource {
    pub fixture_id: String,
    pub material_lot_id: u64,
    pub available_ml: u64,
    pub revision: u64,
    pub disabled_at: Option<StrategicMinute>,
}

impl __sdk::InModule for OutbreakWaterSource {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OutbreakWaterSource`.
///
/// Provides typed access to columns for query building.
pub struct OutbreakWaterSourceCols {
    pub fixture_id: __sdk::__query_builder::Col<OutbreakWaterSource, String>,
    pub material_lot_id: __sdk::__query_builder::Col<OutbreakWaterSource, u64>,
    pub available_ml: __sdk::__query_builder::Col<OutbreakWaterSource, u64>,
    pub revision: __sdk::__query_builder::Col<OutbreakWaterSource, u64>,
    pub disabled_at: __sdk::__query_builder::Col<OutbreakWaterSource, Option<StrategicMinute>>,
}

impl __sdk::__query_builder::HasCols for OutbreakWaterSource {
    type Cols = OutbreakWaterSourceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OutbreakWaterSourceCols {
            fixture_id: __sdk::__query_builder::Col::new(table_name, "fixture_id"),
            material_lot_id: __sdk::__query_builder::Col::new(table_name, "material_lot_id"),
            available_ml: __sdk::__query_builder::Col::new(table_name, "available_ml"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            disabled_at: __sdk::__query_builder::Col::new(table_name, "disabled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `OutbreakWaterSource`.
///
/// Provides typed access to indexed columns for query building.
pub struct OutbreakWaterSourceIxCols {
    pub fixture_id: __sdk::__query_builder::IxCol<OutbreakWaterSource, String>,
    pub material_lot_id: __sdk::__query_builder::IxCol<OutbreakWaterSource, u64>,
}

impl __sdk::__query_builder::HasIxCols for OutbreakWaterSource {
    type IxCols = OutbreakWaterSourceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OutbreakWaterSourceIxCols {
            fixture_id: __sdk::__query_builder::IxCol::new(table_name, "fixture_id"),
            material_lot_id: __sdk::__query_builder::IxCol::new(table_name, "material_lot_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OutbreakWaterSource {}
