// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::journey_precipitation_type::JourneyPrecipitation;
use super::journey_route_leg_type::JourneyRouteLeg;
use super::journey_route_point_type::JourneyRoutePoint;
use super::journey_terrain_span_type::JourneyTerrainSpan;
use super::party_journey_route_type::PartyJourneyRoute;
use super::strategic_minute_type::StrategicMinute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `party_journey_route`.
///
/// Obtain a handle from the [`PartyJourneyRouteTableAccess::party_journey_route`] method on [`super::RemoteTables`],
/// like `ctx.db.party_journey_route()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_journey_route().on_insert(...)`.
pub struct PartyJourneyRouteTableHandle<'ctx> {
    imp: __sdk::TableHandle<PartyJourneyRoute>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `party_journey_route`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PartyJourneyRouteTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PartyJourneyRouteTableHandle`], which mediates access to the table `party_journey_route`.
    fn party_journey_route(&self) -> PartyJourneyRouteTableHandle<'_>;
}

impl PartyJourneyRouteTableAccess for super::RemoteTables {
    fn party_journey_route(&self) -> PartyJourneyRouteTableHandle<'_> {
        PartyJourneyRouteTableHandle {
            imp: self
                .imp
                .get_table::<PartyJourneyRoute>("party_journey_route"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PartyJourneyRouteInsertCallbackId(__sdk::CallbackId);
pub struct PartyJourneyRouteDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PartyJourneyRouteTableHandle<'ctx> {
    type Row = PartyJourneyRoute;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PartyJourneyRoute> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PartyJourneyRouteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyJourneyRouteInsertCallbackId {
        PartyJourneyRouteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PartyJourneyRouteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PartyJourneyRouteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyJourneyRouteDeleteCallbackId {
        PartyJourneyRouteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PartyJourneyRouteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PartyJourneyRoute>("party_journey_route");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PartyJourneyRoute>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PartyJourneyRoute>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PartyJourneyRoute`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait party_journey_routeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PartyJourneyRoute`.
    fn party_journey_route(&self) -> __sdk::__query_builder::Table<PartyJourneyRoute>;
}

impl party_journey_routeQueryTableAccess for __sdk::QueryTableAccessor {
    fn party_journey_route(&self) -> __sdk::__query_builder::Table<PartyJourneyRoute> {
        __sdk::__query_builder::Table::new("party_journey_route")
    }
}
