// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::seed_type::Seed;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PartyJourneyEncounterAuthority {
    pub party_id: String,
    pub seed: Seed,
    pub next_roll: u64,
    pub narrative_rest_elapsed_minutes: u64,
}

impl __sdk::InModule for PartyJourneyEncounterAuthority {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PartyJourneyEncounterAuthority`.
///
/// Provides typed access to columns for query building.
pub struct PartyJourneyEncounterAuthorityCols {
    pub party_id: __sdk::__query_builder::Col<PartyJourneyEncounterAuthority, String>,
    pub seed: __sdk::__query_builder::Col<PartyJourneyEncounterAuthority, Seed>,
    pub next_roll: __sdk::__query_builder::Col<PartyJourneyEncounterAuthority, u64>,
    pub narrative_rest_elapsed_minutes:
        __sdk::__query_builder::Col<PartyJourneyEncounterAuthority, u64>,
}

impl __sdk::__query_builder::HasCols for PartyJourneyEncounterAuthority {
    type Cols = PartyJourneyEncounterAuthorityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyJourneyEncounterAuthorityCols {
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            seed: __sdk::__query_builder::Col::new(table_name, "seed"),
            next_roll: __sdk::__query_builder::Col::new(table_name, "next_roll"),
            narrative_rest_elapsed_minutes: __sdk::__query_builder::Col::new(
                table_name,
                "narrative_rest_elapsed_minutes",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `PartyJourneyEncounterAuthority`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyJourneyEncounterAuthorityIxCols {
    pub party_id: __sdk::__query_builder::IxCol<PartyJourneyEncounterAuthority, String>,
}

impl __sdk::__query_builder::HasIxCols for PartyJourneyEncounterAuthority {
    type IxCols = PartyJourneyEncounterAuthorityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyJourneyEncounterAuthorityIxCols {
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PartyJourneyEncounterAuthority {}
