// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PartyContextContactAuthority {
    pub id: String,
    pub scan_id: u8,
    pub party_id: String,
    pub context_id: String,
    pub location_id: String,
    pub revision: u32,
    pub contacted: bool,
    pub mutual_awareness: bool,
}

impl __sdk::InModule for PartyContextContactAuthority {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PartyContextContactAuthority`.
///
/// Provides typed access to columns for query building.
pub struct PartyContextContactAuthorityCols {
    pub id: __sdk::__query_builder::Col<PartyContextContactAuthority, String>,
    pub scan_id: __sdk::__query_builder::Col<PartyContextContactAuthority, u8>,
    pub party_id: __sdk::__query_builder::Col<PartyContextContactAuthority, String>,
    pub context_id: __sdk::__query_builder::Col<PartyContextContactAuthority, String>,
    pub location_id: __sdk::__query_builder::Col<PartyContextContactAuthority, String>,
    pub revision: __sdk::__query_builder::Col<PartyContextContactAuthority, u32>,
    pub contacted: __sdk::__query_builder::Col<PartyContextContactAuthority, bool>,
    pub mutual_awareness: __sdk::__query_builder::Col<PartyContextContactAuthority, bool>,
}

impl __sdk::__query_builder::HasCols for PartyContextContactAuthority {
    type Cols = PartyContextContactAuthorityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyContextContactAuthorityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            scan_id: __sdk::__query_builder::Col::new(table_name, "scan_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            context_id: __sdk::__query_builder::Col::new(table_name, "context_id"),
            location_id: __sdk::__query_builder::Col::new(table_name, "location_id"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            contacted: __sdk::__query_builder::Col::new(table_name, "contacted"),
            mutual_awareness: __sdk::__query_builder::Col::new(table_name, "mutual_awareness"),
        }
    }
}

/// Indexed column accessor struct for the table `PartyContextContactAuthority`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyContextContactAuthorityIxCols {
    pub id: __sdk::__query_builder::IxCol<PartyContextContactAuthority, String>,
    pub party_id: __sdk::__query_builder::IxCol<PartyContextContactAuthority, String>,
    pub scan_id: __sdk::__query_builder::IxCol<PartyContextContactAuthority, u8>,
}

impl __sdk::__query_builder::HasIxCols for PartyContextContactAuthority {
    type IxCols = PartyContextContactAuthorityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyContextContactAuthorityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
            scan_id: __sdk::__query_builder::IxCol::new(table_name, "scan_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PartyContextContactAuthority {}
