// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::journey_camp_interval_type::JourneyCampInterval;
use super::journey_endpoint_type::JourneyEndpoint;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PartyJourney {
    pub party_id: String,
    pub gateway_bucket: u8,
    pub origin: JourneyEndpoint,
    pub destination: JourneyEndpoint,
    pub total_movement_minutes: u64,
    pub completed_movement_minutes: u64,
    pub reached_camp_movement_minutes: Vec<u64>,
    pub actual_camp_intervals: Vec<JourneyCampInterval>,
    pub forecast_camp_intervals: Vec<JourneyCampInterval>,
    pub fatigue_percent: u8,
    pub departure_minute: StrategicMinute,
    pub total_elapsed_minutes: u64,
    pub completed_elapsed_minutes: u64,
    pub walking_minutes_per_day: u16,
    pub travel_at_night: bool,
}

impl __sdk::InModule for PartyJourney {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PartyJourney`.
///
/// Provides typed access to columns for query building.
pub struct PartyJourneyCols {
    pub party_id: __sdk::__query_builder::Col<PartyJourney, String>,
    pub gateway_bucket: __sdk::__query_builder::Col<PartyJourney, u8>,
    pub origin: __sdk::__query_builder::Col<PartyJourney, JourneyEndpoint>,
    pub destination: __sdk::__query_builder::Col<PartyJourney, JourneyEndpoint>,
    pub total_movement_minutes: __sdk::__query_builder::Col<PartyJourney, u64>,
    pub completed_movement_minutes: __sdk::__query_builder::Col<PartyJourney, u64>,
    pub reached_camp_movement_minutes: __sdk::__query_builder::Col<PartyJourney, Vec<u64>>,
    pub actual_camp_intervals: __sdk::__query_builder::Col<PartyJourney, Vec<JourneyCampInterval>>,
    pub forecast_camp_intervals:
        __sdk::__query_builder::Col<PartyJourney, Vec<JourneyCampInterval>>,
    pub fatigue_percent: __sdk::__query_builder::Col<PartyJourney, u8>,
    pub departure_minute: __sdk::__query_builder::Col<PartyJourney, StrategicMinute>,
    pub total_elapsed_minutes: __sdk::__query_builder::Col<PartyJourney, u64>,
    pub completed_elapsed_minutes: __sdk::__query_builder::Col<PartyJourney, u64>,
    pub walking_minutes_per_day: __sdk::__query_builder::Col<PartyJourney, u16>,
    pub travel_at_night: __sdk::__query_builder::Col<PartyJourney, bool>,
}

impl __sdk::__query_builder::HasCols for PartyJourney {
    type Cols = PartyJourneyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyJourneyCols {
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            gateway_bucket: __sdk::__query_builder::Col::new(table_name, "gateway_bucket"),
            origin: __sdk::__query_builder::Col::new(table_name, "origin"),
            destination: __sdk::__query_builder::Col::new(table_name, "destination"),
            total_movement_minutes: __sdk::__query_builder::Col::new(
                table_name,
                "total_movement_minutes",
            ),
            completed_movement_minutes: __sdk::__query_builder::Col::new(
                table_name,
                "completed_movement_minutes",
            ),
            reached_camp_movement_minutes: __sdk::__query_builder::Col::new(
                table_name,
                "reached_camp_movement_minutes",
            ),
            actual_camp_intervals: __sdk::__query_builder::Col::new(
                table_name,
                "actual_camp_intervals",
            ),
            forecast_camp_intervals: __sdk::__query_builder::Col::new(
                table_name,
                "forecast_camp_intervals",
            ),
            fatigue_percent: __sdk::__query_builder::Col::new(table_name, "fatigue_percent"),
            departure_minute: __sdk::__query_builder::Col::new(table_name, "departure_minute"),
            total_elapsed_minutes: __sdk::__query_builder::Col::new(
                table_name,
                "total_elapsed_minutes",
            ),
            completed_elapsed_minutes: __sdk::__query_builder::Col::new(
                table_name,
                "completed_elapsed_minutes",
            ),
            walking_minutes_per_day: __sdk::__query_builder::Col::new(
                table_name,
                "walking_minutes_per_day",
            ),
            travel_at_night: __sdk::__query_builder::Col::new(table_name, "travel_at_night"),
        }
    }
}

/// Indexed column accessor struct for the table `PartyJourney`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyJourneyIxCols {
    pub gateway_bucket: __sdk::__query_builder::IxCol<PartyJourney, u8>,
    pub party_id: __sdk::__query_builder::IxCol<PartyJourney, String>,
}

impl __sdk::__query_builder::HasIxCols for PartyJourney {
    type IxCols = PartyJourneyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyJourneyIxCols {
            gateway_bucket: __sdk::__query_builder::IxCol::new(table_name, "gateway_bucket"),
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PartyJourney {}
