// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::case_site_id_type::CaseSiteId;
use super::journey_endpoint_type::JourneyEndpoint;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Party {
    pub id: String,
    pub gateway_bucket: u8,
    pub name: String,
    pub leader_id: u64,
    pub current_settlement_id: Option<String>,
    pub current_case_site_id: Option<CaseSiteId>,
    pub active_contract_id: Option<String>,
    pub is_solo: bool,
    pub camp_fatigue_percent: u8,
    pub walking_minutes_per_day: u16,
    pub travel_at_night: bool,
    pub journey_start_minute_of_day: u16,
    pub wilderness_canonical_anchor_minute: Option<StrategicMinute>,
    pub wilderness_elapsed_minutes: u64,
    pub camp_destination: Option<JourneyEndpoint>,
    pub camp_remaining_minutes: u64,
    pub physiology_target: f32,
    pub command_target: f32,
    pub religion_target: f32,
}

impl __sdk::InModule for Party {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Party`.
///
/// Provides typed access to columns for query building.
pub struct PartyCols {
    pub id: __sdk::__query_builder::Col<Party, String>,
    pub gateway_bucket: __sdk::__query_builder::Col<Party, u8>,
    pub name: __sdk::__query_builder::Col<Party, String>,
    pub leader_id: __sdk::__query_builder::Col<Party, u64>,
    pub current_settlement_id: __sdk::__query_builder::Col<Party, Option<String>>,
    pub current_case_site_id: __sdk::__query_builder::Col<Party, Option<CaseSiteId>>,
    pub active_contract_id: __sdk::__query_builder::Col<Party, Option<String>>,
    pub is_solo: __sdk::__query_builder::Col<Party, bool>,
    pub camp_fatigue_percent: __sdk::__query_builder::Col<Party, u8>,
    pub walking_minutes_per_day: __sdk::__query_builder::Col<Party, u16>,
    pub travel_at_night: __sdk::__query_builder::Col<Party, bool>,
    pub journey_start_minute_of_day: __sdk::__query_builder::Col<Party, u16>,
    pub wilderness_canonical_anchor_minute:
        __sdk::__query_builder::Col<Party, Option<StrategicMinute>>,
    pub wilderness_elapsed_minutes: __sdk::__query_builder::Col<Party, u64>,
    pub camp_destination: __sdk::__query_builder::Col<Party, Option<JourneyEndpoint>>,
    pub camp_remaining_minutes: __sdk::__query_builder::Col<Party, u64>,
    pub physiology_target: __sdk::__query_builder::Col<Party, f32>,
    pub command_target: __sdk::__query_builder::Col<Party, f32>,
    pub religion_target: __sdk::__query_builder::Col<Party, f32>,
}

impl __sdk::__query_builder::HasCols for Party {
    type Cols = PartyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            gateway_bucket: __sdk::__query_builder::Col::new(table_name, "gateway_bucket"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            leader_id: __sdk::__query_builder::Col::new(table_name, "leader_id"),
            current_settlement_id: __sdk::__query_builder::Col::new(
                table_name,
                "current_settlement_id",
            ),
            current_case_site_id: __sdk::__query_builder::Col::new(
                table_name,
                "current_case_site_id",
            ),
            active_contract_id: __sdk::__query_builder::Col::new(table_name, "active_contract_id"),
            is_solo: __sdk::__query_builder::Col::new(table_name, "is_solo"),
            camp_fatigue_percent: __sdk::__query_builder::Col::new(
                table_name,
                "camp_fatigue_percent",
            ),
            walking_minutes_per_day: __sdk::__query_builder::Col::new(
                table_name,
                "walking_minutes_per_day",
            ),
            travel_at_night: __sdk::__query_builder::Col::new(table_name, "travel_at_night"),
            journey_start_minute_of_day: __sdk::__query_builder::Col::new(
                table_name,
                "journey_start_minute_of_day",
            ),
            wilderness_canonical_anchor_minute: __sdk::__query_builder::Col::new(
                table_name,
                "wilderness_canonical_anchor_minute",
            ),
            wilderness_elapsed_minutes: __sdk::__query_builder::Col::new(
                table_name,
                "wilderness_elapsed_minutes",
            ),
            camp_destination: __sdk::__query_builder::Col::new(table_name, "camp_destination"),
            camp_remaining_minutes: __sdk::__query_builder::Col::new(
                table_name,
                "camp_remaining_minutes",
            ),
            physiology_target: __sdk::__query_builder::Col::new(table_name, "physiology_target"),
            command_target: __sdk::__query_builder::Col::new(table_name, "command_target"),
            religion_target: __sdk::__query_builder::Col::new(table_name, "religion_target"),
        }
    }
}

/// Indexed column accessor struct for the table `Party`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyIxCols {
    pub gateway_bucket: __sdk::__query_builder::IxCol<Party, u8>,
    pub id: __sdk::__query_builder::IxCol<Party, String>,
}

impl __sdk::__query_builder::HasIxCols for Party {
    type IxCols = PartyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyIxCols {
            gateway_bucket: __sdk::__query_builder::IxCol::new(table_name, "gateway_bucket"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Party {}
