// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::persisted_world_event_actor_type::PersistedWorldEventActor;
use super::persisted_world_event_payload_ref_type::PersistedWorldEventPayloadRef;
use super::persisted_world_event_place_type::PersistedWorldEventPlace;
use super::persisted_world_event_source_type::PersistedWorldEventSource;
use super::persisted_world_event_subject_type::PersistedWorldEventSubject;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PersistedWorldEventEnvelope {
    pub schema_revision: u16,
    pub source: PersistedWorldEventSource,
    pub actor: PersistedWorldEventActor,
    pub subjects: Vec<PersistedWorldEventSubject>,
    pub place: PersistedWorldEventPlace,
    pub occurred_at_minute: StrategicMinute,
    pub payload: PersistedWorldEventPayloadRef,
}

impl __sdk::InModule for PersistedWorldEventEnvelope {
    type Module = super::RemoteModule;
}
