// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PhysiologyPresenceSpan {
    pub id: u64,
    pub low_id: u64,
    pub high_id: u64,
    pub started_at: StrategicMinute,
    pub ended_at: Option<StrategicMinute>,
    pub low_observer_band: u8,
    pub high_observer_band: u8,
}

impl __sdk::InModule for PhysiologyPresenceSpan {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PhysiologyPresenceSpan`.
///
/// Provides typed access to columns for query building.
pub struct PhysiologyPresenceSpanCols {
    pub id: __sdk::__query_builder::Col<PhysiologyPresenceSpan, u64>,
    pub low_id: __sdk::__query_builder::Col<PhysiologyPresenceSpan, u64>,
    pub high_id: __sdk::__query_builder::Col<PhysiologyPresenceSpan, u64>,
    pub started_at: __sdk::__query_builder::Col<PhysiologyPresenceSpan, StrategicMinute>,
    pub ended_at: __sdk::__query_builder::Col<PhysiologyPresenceSpan, Option<StrategicMinute>>,
    pub low_observer_band: __sdk::__query_builder::Col<PhysiologyPresenceSpan, u8>,
    pub high_observer_band: __sdk::__query_builder::Col<PhysiologyPresenceSpan, u8>,
}

impl __sdk::__query_builder::HasCols for PhysiologyPresenceSpan {
    type Cols = PhysiologyPresenceSpanCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PhysiologyPresenceSpanCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            low_id: __sdk::__query_builder::Col::new(table_name, "low_id"),
            high_id: __sdk::__query_builder::Col::new(table_name, "high_id"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            ended_at: __sdk::__query_builder::Col::new(table_name, "ended_at"),
            low_observer_band: __sdk::__query_builder::Col::new(table_name, "low_observer_band"),
            high_observer_band: __sdk::__query_builder::Col::new(table_name, "high_observer_band"),
        }
    }
}

/// Indexed column accessor struct for the table `PhysiologyPresenceSpan`.
///
/// Provides typed access to indexed columns for query building.
pub struct PhysiologyPresenceSpanIxCols {
    pub high_id: __sdk::__query_builder::IxCol<PhysiologyPresenceSpan, u64>,
    pub id: __sdk::__query_builder::IxCol<PhysiologyPresenceSpan, u64>,
    pub low_id: __sdk::__query_builder::IxCol<PhysiologyPresenceSpan, u64>,
}

impl __sdk::__query_builder::HasIxCols for PhysiologyPresenceSpan {
    type IxCols = PhysiologyPresenceSpanIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PhysiologyPresenceSpanIxCols {
            high_id: __sdk::__query_builder::IxCol::new(table_name, "high_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            low_id: __sdk::__query_builder::IxCol::new(table_name, "low_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PhysiologyPresenceSpan {}
