// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PrimaryResidence {
    pub character_id: u64,
    pub holding_id: String,
    pub designated_minute: StrategicMinute,
}

impl __sdk::InModule for PrimaryResidence {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PrimaryResidence`.
///
/// Provides typed access to columns for query building.
pub struct PrimaryResidenceCols {
    pub character_id: __sdk::__query_builder::Col<PrimaryResidence, u64>,
    pub holding_id: __sdk::__query_builder::Col<PrimaryResidence, String>,
    pub designated_minute: __sdk::__query_builder::Col<PrimaryResidence, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for PrimaryResidence {
    type Cols = PrimaryResidenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PrimaryResidenceCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            holding_id: __sdk::__query_builder::Col::new(table_name, "holding_id"),
            designated_minute: __sdk::__query_builder::Col::new(table_name, "designated_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `PrimaryResidence`.
///
/// Provides typed access to indexed columns for query building.
pub struct PrimaryResidenceIxCols {
    pub character_id: __sdk::__query_builder::IxCol<PrimaryResidence, u64>,
    pub holding_id: __sdk::__query_builder::IxCol<PrimaryResidence, String>,
}

impl __sdk::__query_builder::HasIxCols for PrimaryResidence {
    type IxCols = PrimaryResidenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PrimaryResidenceIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            holding_id: __sdk::__query_builder::IxCol::new(table_name, "holding_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PrimaryResidence {}
