// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::legal_owner_kind_type::LegalOwnerKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PropertyTransferReceipt {
    pub source_id: String,
    pub property_id: String,
    pub physical_binding_id: String,
    pub quantity: u64,
    pub expected_version: u32,
    pub from_owner_kind: LegalOwnerKind,
    pub from_owner_id: String,
    pub to_owner_kind: LegalOwnerKind,
    pub to_owner_id: String,
    pub resulting_version: u32,
}

impl __sdk::InModule for PropertyTransferReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PropertyTransferReceipt`.
///
/// Provides typed access to columns for query building.
pub struct PropertyTransferReceiptCols {
    pub source_id: __sdk::__query_builder::Col<PropertyTransferReceipt, String>,
    pub property_id: __sdk::__query_builder::Col<PropertyTransferReceipt, String>,
    pub physical_binding_id: __sdk::__query_builder::Col<PropertyTransferReceipt, String>,
    pub quantity: __sdk::__query_builder::Col<PropertyTransferReceipt, u64>,
    pub expected_version: __sdk::__query_builder::Col<PropertyTransferReceipt, u32>,
    pub from_owner_kind: __sdk::__query_builder::Col<PropertyTransferReceipt, LegalOwnerKind>,
    pub from_owner_id: __sdk::__query_builder::Col<PropertyTransferReceipt, String>,
    pub to_owner_kind: __sdk::__query_builder::Col<PropertyTransferReceipt, LegalOwnerKind>,
    pub to_owner_id: __sdk::__query_builder::Col<PropertyTransferReceipt, String>,
    pub resulting_version: __sdk::__query_builder::Col<PropertyTransferReceipt, u32>,
}

impl __sdk::__query_builder::HasCols for PropertyTransferReceipt {
    type Cols = PropertyTransferReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PropertyTransferReceiptCols {
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            property_id: __sdk::__query_builder::Col::new(table_name, "property_id"),
            physical_binding_id: __sdk::__query_builder::Col::new(
                table_name,
                "physical_binding_id",
            ),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            expected_version: __sdk::__query_builder::Col::new(table_name, "expected_version"),
            from_owner_kind: __sdk::__query_builder::Col::new(table_name, "from_owner_kind"),
            from_owner_id: __sdk::__query_builder::Col::new(table_name, "from_owner_id"),
            to_owner_kind: __sdk::__query_builder::Col::new(table_name, "to_owner_kind"),
            to_owner_id: __sdk::__query_builder::Col::new(table_name, "to_owner_id"),
            resulting_version: __sdk::__query_builder::Col::new(table_name, "resulting_version"),
        }
    }
}

/// Indexed column accessor struct for the table `PropertyTransferReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct PropertyTransferReceiptIxCols {
    pub source_id: __sdk::__query_builder::IxCol<PropertyTransferReceipt, String>,
}

impl __sdk::__query_builder::HasIxCols for PropertyTransferReceipt {
    type IxCols = PropertyTransferReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PropertyTransferReceiptIxCols {
            source_id: __sdk::__query_builder::IxCol::new(table_name, "source_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PropertyTransferReceipt {}
