// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::property_occupancy_kind_type::PropertyOccupancyKind;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PropertyOccupancyTransition {
    pub id: String,
    pub character_id: u64,
    pub property_id: String,
    pub holding_id: Option<String>,
    pub kind: PropertyOccupancyKind,
    pub minute: StrategicMinute,
    pub ordinal: u64,
}

impl __sdk::InModule for PropertyOccupancyTransition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PropertyOccupancyTransition`.
///
/// Provides typed access to columns for query building.
pub struct PropertyOccupancyTransitionCols {
    pub id: __sdk::__query_builder::Col<PropertyOccupancyTransition, String>,
    pub character_id: __sdk::__query_builder::Col<PropertyOccupancyTransition, u64>,
    pub property_id: __sdk::__query_builder::Col<PropertyOccupancyTransition, String>,
    pub holding_id: __sdk::__query_builder::Col<PropertyOccupancyTransition, Option<String>>,
    pub kind: __sdk::__query_builder::Col<PropertyOccupancyTransition, PropertyOccupancyKind>,
    pub minute: __sdk::__query_builder::Col<PropertyOccupancyTransition, StrategicMinute>,
    pub ordinal: __sdk::__query_builder::Col<PropertyOccupancyTransition, u64>,
}

impl __sdk::__query_builder::HasCols for PropertyOccupancyTransition {
    type Cols = PropertyOccupancyTransitionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PropertyOccupancyTransitionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            property_id: __sdk::__query_builder::Col::new(table_name, "property_id"),
            holding_id: __sdk::__query_builder::Col::new(table_name, "holding_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            minute: __sdk::__query_builder::Col::new(table_name, "minute"),
            ordinal: __sdk::__query_builder::Col::new(table_name, "ordinal"),
        }
    }
}

/// Indexed column accessor struct for the table `PropertyOccupancyTransition`.
///
/// Provides typed access to indexed columns for query building.
pub struct PropertyOccupancyTransitionIxCols {
    pub character_id: __sdk::__query_builder::IxCol<PropertyOccupancyTransition, u64>,
    pub id: __sdk::__query_builder::IxCol<PropertyOccupancyTransition, String>,
    pub property_id: __sdk::__query_builder::IxCol<PropertyOccupancyTransition, String>,
}

impl __sdk::__query_builder::HasIxCols for PropertyOccupancyTransition {
    type IxCols = PropertyOccupancyTransitionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PropertyOccupancyTransitionIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            property_id: __sdk::__query_builder::IxCol::new(table_name, "property_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PropertyOccupancyTransition {}
