// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RecruitmentTransferReceipt {
    pub source_id: String,
    pub character_id: u64,
    pub from_party_id: Option<String>,
    pub to_party_id: String,
    pub context_id: String,
    pub contact_ref: String,
    pub expected_disposition_revision: u32,
}

impl __sdk::InModule for RecruitmentTransferReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RecruitmentTransferReceipt`.
///
/// Provides typed access to columns for query building.
pub struct RecruitmentTransferReceiptCols {
    pub source_id: __sdk::__query_builder::Col<RecruitmentTransferReceipt, String>,
    pub character_id: __sdk::__query_builder::Col<RecruitmentTransferReceipt, u64>,
    pub from_party_id: __sdk::__query_builder::Col<RecruitmentTransferReceipt, Option<String>>,
    pub to_party_id: __sdk::__query_builder::Col<RecruitmentTransferReceipt, String>,
    pub context_id: __sdk::__query_builder::Col<RecruitmentTransferReceipt, String>,
    pub contact_ref: __sdk::__query_builder::Col<RecruitmentTransferReceipt, String>,
    pub expected_disposition_revision: __sdk::__query_builder::Col<RecruitmentTransferReceipt, u32>,
}

impl __sdk::__query_builder::HasCols for RecruitmentTransferReceipt {
    type Cols = RecruitmentTransferReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RecruitmentTransferReceiptCols {
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            from_party_id: __sdk::__query_builder::Col::new(table_name, "from_party_id"),
            to_party_id: __sdk::__query_builder::Col::new(table_name, "to_party_id"),
            context_id: __sdk::__query_builder::Col::new(table_name, "context_id"),
            contact_ref: __sdk::__query_builder::Col::new(table_name, "contact_ref"),
            expected_disposition_revision: __sdk::__query_builder::Col::new(
                table_name,
                "expected_disposition_revision",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `RecruitmentTransferReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct RecruitmentTransferReceiptIxCols {
    pub source_id: __sdk::__query_builder::IxCol<RecruitmentTransferReceipt, String>,
}

impl __sdk::__query_builder::HasIxCols for RecruitmentTransferReceipt {
    type IxCols = RecruitmentTransferReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RecruitmentTransferReceiptIxCols {
            source_id: __sdk::__query_builder::IxCol::new(table_name, "source_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RecruitmentTransferReceipt {}
