// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterSettlementPropertiesArgs {
    pub catalog_json: String,
}

impl From<RegisterSettlementPropertiesArgs> for super::Reducer {
    fn from(args: RegisterSettlementPropertiesArgs) -> Self {
        Self::RegisterSettlementProperties {
            catalog_json: args.catalog_json,
        }
    }
}

impl __sdk::InModule for RegisterSettlementPropertiesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_settlement_properties`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_settlement_properties {
    /// Request that the remote module invoke the reducer `register_settlement_properties` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_settlement_properties:register_settlement_properties_then`] to run a callback after the reducer completes.
    fn register_settlement_properties(&self, catalog_json: String) -> __sdk::Result<()> {
        self.register_settlement_properties_then(catalog_json, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_settlement_properties` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_settlement_properties_then(
        &self,
        catalog_json: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl register_settlement_properties for super::RemoteReducers {
    fn register_settlement_properties_then(
        &self,
        catalog_json: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterSettlementPropertiesArgs { catalog_json },
            callback,
        )
    }
}
