// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveHouseholdOccupantArgs {
    pub holder_character_id: u64,
    pub holding_id: String,
    pub occupant_id: u64,
}

impl From<RemoveHouseholdOccupantArgs> for super::Reducer {
    fn from(args: RemoveHouseholdOccupantArgs) -> Self {
        Self::RemoveHouseholdOccupant {
            holder_character_id: args.holder_character_id,
            holding_id: args.holding_id,
            occupant_id: args.occupant_id,
        }
    }
}

impl __sdk::InModule for RemoveHouseholdOccupantArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_household_occupant`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_household_occupant {
    /// Request that the remote module invoke the reducer `remove_household_occupant` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`remove_household_occupant:remove_household_occupant_then`] to run a callback after the reducer completes.
    fn remove_household_occupant(
        &self,
        holder_character_id: u64,
        holding_id: String,
        occupant_id: u64,
    ) -> __sdk::Result<()> {
        self.remove_household_occupant_then(holder_character_id, holding_id, occupant_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `remove_household_occupant` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn remove_household_occupant_then(
        &self,
        holder_character_id: u64,
        holding_id: String,
        occupant_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl remove_household_occupant for super::RemoteReducers {
    fn remove_household_occupant_then(
        &self,
        holder_character_id: u64,
        holding_id: String,
        occupant_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RemoveHouseholdOccupantArgs {
                holder_character_id,
                holding_id,
                occupant_id,
            },
            callback,
        )
    }
}
