// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ReputationEvent {
    pub id: String,
    pub character_id: u64,
    pub origin_settlement_id: String,
    pub source_kind: String,
    pub source_id: String,
    pub raw_fame: i32,
    pub raw_infamy: i32,
    pub occurred_at_minute: StrategicMinute,
}

impl __sdk::InModule for ReputationEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ReputationEvent`.
///
/// Provides typed access to columns for query building.
pub struct ReputationEventCols {
    pub id: __sdk::__query_builder::Col<ReputationEvent, String>,
    pub character_id: __sdk::__query_builder::Col<ReputationEvent, u64>,
    pub origin_settlement_id: __sdk::__query_builder::Col<ReputationEvent, String>,
    pub source_kind: __sdk::__query_builder::Col<ReputationEvent, String>,
    pub source_id: __sdk::__query_builder::Col<ReputationEvent, String>,
    pub raw_fame: __sdk::__query_builder::Col<ReputationEvent, i32>,
    pub raw_infamy: __sdk::__query_builder::Col<ReputationEvent, i32>,
    pub occurred_at_minute: __sdk::__query_builder::Col<ReputationEvent, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for ReputationEvent {
    type Cols = ReputationEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ReputationEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            origin_settlement_id: __sdk::__query_builder::Col::new(
                table_name,
                "origin_settlement_id",
            ),
            source_kind: __sdk::__query_builder::Col::new(table_name, "source_kind"),
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            raw_fame: __sdk::__query_builder::Col::new(table_name, "raw_fame"),
            raw_infamy: __sdk::__query_builder::Col::new(table_name, "raw_infamy"),
            occurred_at_minute: __sdk::__query_builder::Col::new(table_name, "occurred_at_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `ReputationEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct ReputationEventIxCols {
    pub character_id: __sdk::__query_builder::IxCol<ReputationEvent, u64>,
    pub id: __sdk::__query_builder::IxCol<ReputationEvent, String>,
}

impl __sdk::__query_builder::HasIxCols for ReputationEvent {
    type IxCols = ReputationEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ReputationEventIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ReputationEvent {}
