// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::housing_tier_type::HousingTier;
use super::residence_holding_status_type::ResidenceHoldingStatus;
use super::residence_tenure_type::ResidenceTenure;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ResidenceHolding {
    pub property_id: String,
    pub id: String,
    pub holder_character_id: u64,
    pub settlement_id: String,
    pub tier: HousingTier,
    pub tenure: ResidenceTenure,
    pub status: ResidenceHoldingStatus,
    pub acquired_ordinal: u64,
    pub acquired_minute: StrategicMinute,
    pub last_billed_minute: StrategicMinute,
    pub next_due_minute: StrategicMinute,
    pub resolved_minute: Option<StrategicMinute>,
}

impl __sdk::InModule for ResidenceHolding {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ResidenceHolding`.
///
/// Provides typed access to columns for query building.
pub struct ResidenceHoldingCols {
    pub property_id: __sdk::__query_builder::Col<ResidenceHolding, String>,
    pub id: __sdk::__query_builder::Col<ResidenceHolding, String>,
    pub holder_character_id: __sdk::__query_builder::Col<ResidenceHolding, u64>,
    pub settlement_id: __sdk::__query_builder::Col<ResidenceHolding, String>,
    pub tier: __sdk::__query_builder::Col<ResidenceHolding, HousingTier>,
    pub tenure: __sdk::__query_builder::Col<ResidenceHolding, ResidenceTenure>,
    pub status: __sdk::__query_builder::Col<ResidenceHolding, ResidenceHoldingStatus>,
    pub acquired_ordinal: __sdk::__query_builder::Col<ResidenceHolding, u64>,
    pub acquired_minute: __sdk::__query_builder::Col<ResidenceHolding, StrategicMinute>,
    pub last_billed_minute: __sdk::__query_builder::Col<ResidenceHolding, StrategicMinute>,
    pub next_due_minute: __sdk::__query_builder::Col<ResidenceHolding, StrategicMinute>,
    pub resolved_minute: __sdk::__query_builder::Col<ResidenceHolding, Option<StrategicMinute>>,
}

impl __sdk::__query_builder::HasCols for ResidenceHolding {
    type Cols = ResidenceHoldingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ResidenceHoldingCols {
            property_id: __sdk::__query_builder::Col::new(table_name, "property_id"),
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            holder_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "holder_character_id",
            ),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            tier: __sdk::__query_builder::Col::new(table_name, "tier"),
            tenure: __sdk::__query_builder::Col::new(table_name, "tenure"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            acquired_ordinal: __sdk::__query_builder::Col::new(table_name, "acquired_ordinal"),
            acquired_minute: __sdk::__query_builder::Col::new(table_name, "acquired_minute"),
            last_billed_minute: __sdk::__query_builder::Col::new(table_name, "last_billed_minute"),
            next_due_minute: __sdk::__query_builder::Col::new(table_name, "next_due_minute"),
            resolved_minute: __sdk::__query_builder::Col::new(table_name, "resolved_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `ResidenceHolding`.
///
/// Provides typed access to indexed columns for query building.
pub struct ResidenceHoldingIxCols {
    pub holder_character_id: __sdk::__query_builder::IxCol<ResidenceHolding, u64>,
    pub id: __sdk::__query_builder::IxCol<ResidenceHolding, String>,
    pub property_id: __sdk::__query_builder::IxCol<ResidenceHolding, String>,
    pub settlement_id: __sdk::__query_builder::IxCol<ResidenceHolding, String>,
}

impl __sdk::__query_builder::HasIxCols for ResidenceHolding {
    type IxCols = ResidenceHoldingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ResidenceHoldingIxCols {
            holder_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "holder_character_id",
            ),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            property_id: __sdk::__query_builder::IxCol::new(table_name, "property_id"),
            settlement_id: __sdk::__query_builder::IxCol::new(table_name, "settlement_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ResidenceHolding {}
