// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::residence_charge_outcome_type::ResidenceChargeOutcome;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ResidenceCharge {
    pub id: String,
    pub holding_id: String,
    pub holder_character_id: u64,
    pub due_minute: StrategicMinute,
    pub base_housing_amount: u64,
    pub adult_necessities_amount: u64,
    pub dependent_necessities_amount: u64,
    pub amount: u64,
    pub supported_adults: u32,
    pub supported_dependents: u32,
    pub outcome: ResidenceChargeOutcome,
    pub recorded_minute: StrategicMinute,
}

impl __sdk::InModule for ResidenceCharge {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ResidenceCharge`.
///
/// Provides typed access to columns for query building.
pub struct ResidenceChargeCols {
    pub id: __sdk::__query_builder::Col<ResidenceCharge, String>,
    pub holding_id: __sdk::__query_builder::Col<ResidenceCharge, String>,
    pub holder_character_id: __sdk::__query_builder::Col<ResidenceCharge, u64>,
    pub due_minute: __sdk::__query_builder::Col<ResidenceCharge, StrategicMinute>,
    pub base_housing_amount: __sdk::__query_builder::Col<ResidenceCharge, u64>,
    pub adult_necessities_amount: __sdk::__query_builder::Col<ResidenceCharge, u64>,
    pub dependent_necessities_amount: __sdk::__query_builder::Col<ResidenceCharge, u64>,
    pub amount: __sdk::__query_builder::Col<ResidenceCharge, u64>,
    pub supported_adults: __sdk::__query_builder::Col<ResidenceCharge, u32>,
    pub supported_dependents: __sdk::__query_builder::Col<ResidenceCharge, u32>,
    pub outcome: __sdk::__query_builder::Col<ResidenceCharge, ResidenceChargeOutcome>,
    pub recorded_minute: __sdk::__query_builder::Col<ResidenceCharge, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for ResidenceCharge {
    type Cols = ResidenceChargeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ResidenceChargeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            holding_id: __sdk::__query_builder::Col::new(table_name, "holding_id"),
            holder_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "holder_character_id",
            ),
            due_minute: __sdk::__query_builder::Col::new(table_name, "due_minute"),
            base_housing_amount: __sdk::__query_builder::Col::new(
                table_name,
                "base_housing_amount",
            ),
            adult_necessities_amount: __sdk::__query_builder::Col::new(
                table_name,
                "adult_necessities_amount",
            ),
            dependent_necessities_amount: __sdk::__query_builder::Col::new(
                table_name,
                "dependent_necessities_amount",
            ),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            supported_adults: __sdk::__query_builder::Col::new(table_name, "supported_adults"),
            supported_dependents: __sdk::__query_builder::Col::new(
                table_name,
                "supported_dependents",
            ),
            outcome: __sdk::__query_builder::Col::new(table_name, "outcome"),
            recorded_minute: __sdk::__query_builder::Col::new(table_name, "recorded_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `ResidenceCharge`.
///
/// Provides typed access to indexed columns for query building.
pub struct ResidenceChargeIxCols {
    pub holder_character_id: __sdk::__query_builder::IxCol<ResidenceCharge, u64>,
    pub holding_id: __sdk::__query_builder::IxCol<ResidenceCharge, String>,
    pub id: __sdk::__query_builder::IxCol<ResidenceCharge, String>,
}

impl __sdk::__query_builder::HasIxCols for ResidenceCharge {
    type IxCols = ResidenceChargeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ResidenceChargeIxCols {
            holder_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "holder_character_id",
            ),
            holding_id: __sdk::__query_builder::IxCol::new(table_name, "holding_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ResidenceCharge {}
