// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ResidenceOccupant {
    pub character_id: u64,
    pub holding_id: Option<String>,
    pub property_id: String,
    pub admitted_minute: StrategicMinute,
}

impl __sdk::InModule for ResidenceOccupant {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ResidenceOccupant`.
///
/// Provides typed access to columns for query building.
pub struct ResidenceOccupantCols {
    pub character_id: __sdk::__query_builder::Col<ResidenceOccupant, u64>,
    pub holding_id: __sdk::__query_builder::Col<ResidenceOccupant, Option<String>>,
    pub property_id: __sdk::__query_builder::Col<ResidenceOccupant, String>,
    pub admitted_minute: __sdk::__query_builder::Col<ResidenceOccupant, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for ResidenceOccupant {
    type Cols = ResidenceOccupantCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ResidenceOccupantCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            holding_id: __sdk::__query_builder::Col::new(table_name, "holding_id"),
            property_id: __sdk::__query_builder::Col::new(table_name, "property_id"),
            admitted_minute: __sdk::__query_builder::Col::new(table_name, "admitted_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `ResidenceOccupant`.
///
/// Provides typed access to indexed columns for query building.
pub struct ResidenceOccupantIxCols {
    pub character_id: __sdk::__query_builder::IxCol<ResidenceOccupant, u64>,
    pub property_id: __sdk::__query_builder::IxCol<ResidenceOccupant, String>,
}

impl __sdk::__query_builder::HasIxCols for ResidenceOccupant {
    type IxCols = ResidenceOccupantIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ResidenceOccupantIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            property_id: __sdk::__query_builder::IxCol::new(table_name, "property_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ResidenceOccupant {}
