// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::case_site_id_type::CaseSiteId;
use super::chivalric_virtue_type::ChivalricVirtue;
use super::narrative_encounter_trigger_type::NarrativeEncounterTrigger;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RoadChallengeAuthority {
    pub id: String,
    pub gateway_bucket: u8,
    pub party_id: String,
    pub case_id: String,
    pub finale_case_site_id: Option<CaseSiteId>,
    pub finale_hostile_group_id: String,
    pub journey_departure_minute: StrategicMinute,
    pub camp_movement_minute: u64,
    pub available_at_elapsed_minute: u64,
    pub catalog_id: String,
    pub catalog_revision: u32,
    pub catalog_digest: String,
    pub absolute_minute: StrategicMinute,
    pub longitude_e_7: i32,
    pub latitude_e_7: i32,
    pub trigger: NarrativeEncounterTrigger,
    pub revision: u32,
    pub open: bool,
    pub resolved_choice: Option<String>,
    pub resolved_deed: Option<String>,
    pub virtue_exemplified: Option<ChivalricVirtue>,
    pub result_transcript: Option<String>,
}

impl __sdk::InModule for RoadChallengeAuthority {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RoadChallengeAuthority`.
///
/// Provides typed access to columns for query building.
pub struct RoadChallengeAuthorityCols {
    pub id: __sdk::__query_builder::Col<RoadChallengeAuthority, String>,
    pub gateway_bucket: __sdk::__query_builder::Col<RoadChallengeAuthority, u8>,
    pub party_id: __sdk::__query_builder::Col<RoadChallengeAuthority, String>,
    pub case_id: __sdk::__query_builder::Col<RoadChallengeAuthority, String>,
    pub finale_case_site_id:
        __sdk::__query_builder::Col<RoadChallengeAuthority, Option<CaseSiteId>>,
    pub finale_hostile_group_id: __sdk::__query_builder::Col<RoadChallengeAuthority, String>,
    pub journey_departure_minute:
        __sdk::__query_builder::Col<RoadChallengeAuthority, StrategicMinute>,
    pub camp_movement_minute: __sdk::__query_builder::Col<RoadChallengeAuthority, u64>,
    pub available_at_elapsed_minute: __sdk::__query_builder::Col<RoadChallengeAuthority, u64>,
    pub catalog_id: __sdk::__query_builder::Col<RoadChallengeAuthority, String>,
    pub catalog_revision: __sdk::__query_builder::Col<RoadChallengeAuthority, u32>,
    pub catalog_digest: __sdk::__query_builder::Col<RoadChallengeAuthority, String>,
    pub absolute_minute: __sdk::__query_builder::Col<RoadChallengeAuthority, StrategicMinute>,
    pub longitude_e_7: __sdk::__query_builder::Col<RoadChallengeAuthority, i32>,
    pub latitude_e_7: __sdk::__query_builder::Col<RoadChallengeAuthority, i32>,
    pub trigger: __sdk::__query_builder::Col<RoadChallengeAuthority, NarrativeEncounterTrigger>,
    pub revision: __sdk::__query_builder::Col<RoadChallengeAuthority, u32>,
    pub open: __sdk::__query_builder::Col<RoadChallengeAuthority, bool>,
    pub resolved_choice: __sdk::__query_builder::Col<RoadChallengeAuthority, Option<String>>,
    pub resolved_deed: __sdk::__query_builder::Col<RoadChallengeAuthority, Option<String>>,
    pub virtue_exemplified:
        __sdk::__query_builder::Col<RoadChallengeAuthority, Option<ChivalricVirtue>>,
    pub result_transcript: __sdk::__query_builder::Col<RoadChallengeAuthority, Option<String>>,
}

impl __sdk::__query_builder::HasCols for RoadChallengeAuthority {
    type Cols = RoadChallengeAuthorityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RoadChallengeAuthorityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            gateway_bucket: __sdk::__query_builder::Col::new(table_name, "gateway_bucket"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            finale_case_site_id: __sdk::__query_builder::Col::new(
                table_name,
                "finale_case_site_id",
            ),
            finale_hostile_group_id: __sdk::__query_builder::Col::new(
                table_name,
                "finale_hostile_group_id",
            ),
            journey_departure_minute: __sdk::__query_builder::Col::new(
                table_name,
                "journey_departure_minute",
            ),
            camp_movement_minute: __sdk::__query_builder::Col::new(
                table_name,
                "camp_movement_minute",
            ),
            available_at_elapsed_minute: __sdk::__query_builder::Col::new(
                table_name,
                "available_at_elapsed_minute",
            ),
            catalog_id: __sdk::__query_builder::Col::new(table_name, "catalog_id"),
            catalog_revision: __sdk::__query_builder::Col::new(table_name, "catalog_revision"),
            catalog_digest: __sdk::__query_builder::Col::new(table_name, "catalog_digest"),
            absolute_minute: __sdk::__query_builder::Col::new(table_name, "absolute_minute"),
            longitude_e_7: __sdk::__query_builder::Col::new(table_name, "longitude_e_7"),
            latitude_e_7: __sdk::__query_builder::Col::new(table_name, "latitude_e_7"),
            trigger: __sdk::__query_builder::Col::new(table_name, "trigger"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            open: __sdk::__query_builder::Col::new(table_name, "open"),
            resolved_choice: __sdk::__query_builder::Col::new(table_name, "resolved_choice"),
            resolved_deed: __sdk::__query_builder::Col::new(table_name, "resolved_deed"),
            virtue_exemplified: __sdk::__query_builder::Col::new(table_name, "virtue_exemplified"),
            result_transcript: __sdk::__query_builder::Col::new(table_name, "result_transcript"),
        }
    }
}

/// Indexed column accessor struct for the table `RoadChallengeAuthority`.
///
/// Provides typed access to indexed columns for query building.
pub struct RoadChallengeAuthorityIxCols {
    pub gateway_bucket: __sdk::__query_builder::IxCol<RoadChallengeAuthority, u8>,
    pub id: __sdk::__query_builder::IxCol<RoadChallengeAuthority, String>,
    pub party_id: __sdk::__query_builder::IxCol<RoadChallengeAuthority, String>,
}

impl __sdk::__query_builder::HasIxCols for RoadChallengeAuthority {
    type IxCols = RoadChallengeAuthorityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RoadChallengeAuthorityIxCols {
            gateway_bucket: __sdk::__query_builder::IxCol::new(table_name, "gateway_bucket"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RoadChallengeAuthority {}
