// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SettlementResidentSeedExplanation {
    pub character_id: u64,
    pub relations_json: String,
}

impl __sdk::InModule for SettlementResidentSeedExplanation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SettlementResidentSeedExplanation`.
///
/// Provides typed access to columns for query building.
pub struct SettlementResidentSeedExplanationCols {
    pub character_id: __sdk::__query_builder::Col<SettlementResidentSeedExplanation, u64>,
    pub relations_json: __sdk::__query_builder::Col<SettlementResidentSeedExplanation, String>,
}

impl __sdk::__query_builder::HasCols for SettlementResidentSeedExplanation {
    type Cols = SettlementResidentSeedExplanationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SettlementResidentSeedExplanationCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            relations_json: __sdk::__query_builder::Col::new(table_name, "relations_json"),
        }
    }
}

/// Indexed column accessor struct for the table `SettlementResidentSeedExplanation`.
///
/// Provides typed access to indexed columns for query building.
pub struct SettlementResidentSeedExplanationIxCols {
    pub character_id: __sdk::__query_builder::IxCol<SettlementResidentSeedExplanation, u64>,
}

impl __sdk::__query_builder::HasIxCols for SettlementResidentSeedExplanation {
    type IxCols = SettlementResidentSeedExplanationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SettlementResidentSeedExplanationIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SettlementResidentSeedExplanation {}
