// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::housing_tier_type::HousingTier;
use super::settlement_property_type::SettlementProperty;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `settlement_property`.
///
/// Obtain a handle from the [`SettlementPropertyTableAccess::settlement_property`] method on [`super::RemoteTables`],
/// like `ctx.db.settlement_property()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.settlement_property().on_insert(...)`.
pub struct SettlementPropertyTableHandle<'ctx> {
    imp: __sdk::TableHandle<SettlementProperty>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `settlement_property`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SettlementPropertyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SettlementPropertyTableHandle`], which mediates access to the table `settlement_property`.
    fn settlement_property(&self) -> SettlementPropertyTableHandle<'_>;
}

impl SettlementPropertyTableAccess for super::RemoteTables {
    fn settlement_property(&self) -> SettlementPropertyTableHandle<'_> {
        SettlementPropertyTableHandle {
            imp: self
                .imp
                .get_table::<SettlementProperty>("settlement_property"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SettlementPropertyInsertCallbackId(__sdk::CallbackId);
pub struct SettlementPropertyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SettlementPropertyTableHandle<'ctx> {
    type Row = SettlementProperty;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SettlementProperty> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SettlementPropertyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SettlementPropertyInsertCallbackId {
        SettlementPropertyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SettlementPropertyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SettlementPropertyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SettlementPropertyDeleteCallbackId {
        SettlementPropertyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SettlementPropertyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SettlementPropertyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SettlementPropertyTableHandle<'ctx> {
    type UpdateCallbackId = SettlementPropertyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SettlementPropertyUpdateCallbackId {
        SettlementPropertyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SettlementPropertyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `settlement_property`,
/// which allows point queries on the field of the same name
/// via the [`SettlementPropertyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.settlement_property().id().find(...)`.
pub struct SettlementPropertyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SettlementProperty, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SettlementPropertyTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `settlement_property`.
    pub fn id(&self) -> SettlementPropertyIdUnique<'ctx> {
        SettlementPropertyIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SettlementPropertyIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SettlementProperty> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SettlementProperty>("settlement_property");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SettlementProperty>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SettlementProperty>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SettlementProperty`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait settlement_propertyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SettlementProperty`.
    fn settlement_property(&self) -> __sdk::__query_builder::Table<SettlementProperty>;
}

impl settlement_propertyQueryTableAccess for __sdk::QueryTableAccessor {
    fn settlement_property(&self) -> __sdk::__query_builder::Table<SettlementProperty> {
        __sdk::__query_builder::Table::new("settlement_property")
    }
}
