// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::housing_tier_type::HousingTier;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SettlementProperty {
    pub id: String,
    pub settlement_id: String,
    pub building_id: u64,
    pub tier: HousingTier,
    pub resident_capacity: u32,
    pub east_metres: f32,
    pub north_metres: f32,
    pub yaw_radians: f32,
    pub width_metres: f32,
    pub depth_metres: f32,
}

impl __sdk::InModule for SettlementProperty {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SettlementProperty`.
///
/// Provides typed access to columns for query building.
pub struct SettlementPropertyCols {
    pub id: __sdk::__query_builder::Col<SettlementProperty, String>,
    pub settlement_id: __sdk::__query_builder::Col<SettlementProperty, String>,
    pub building_id: __sdk::__query_builder::Col<SettlementProperty, u64>,
    pub tier: __sdk::__query_builder::Col<SettlementProperty, HousingTier>,
    pub resident_capacity: __sdk::__query_builder::Col<SettlementProperty, u32>,
    pub east_metres: __sdk::__query_builder::Col<SettlementProperty, f32>,
    pub north_metres: __sdk::__query_builder::Col<SettlementProperty, f32>,
    pub yaw_radians: __sdk::__query_builder::Col<SettlementProperty, f32>,
    pub width_metres: __sdk::__query_builder::Col<SettlementProperty, f32>,
    pub depth_metres: __sdk::__query_builder::Col<SettlementProperty, f32>,
}

impl __sdk::__query_builder::HasCols for SettlementProperty {
    type Cols = SettlementPropertyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SettlementPropertyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            building_id: __sdk::__query_builder::Col::new(table_name, "building_id"),
            tier: __sdk::__query_builder::Col::new(table_name, "tier"),
            resident_capacity: __sdk::__query_builder::Col::new(table_name, "resident_capacity"),
            east_metres: __sdk::__query_builder::Col::new(table_name, "east_metres"),
            north_metres: __sdk::__query_builder::Col::new(table_name, "north_metres"),
            yaw_radians: __sdk::__query_builder::Col::new(table_name, "yaw_radians"),
            width_metres: __sdk::__query_builder::Col::new(table_name, "width_metres"),
            depth_metres: __sdk::__query_builder::Col::new(table_name, "depth_metres"),
        }
    }
}

/// Indexed column accessor struct for the table `SettlementProperty`.
///
/// Provides typed access to indexed columns for query building.
pub struct SettlementPropertyIxCols {
    pub id: __sdk::__query_builder::IxCol<SettlementProperty, String>,
    pub settlement_id: __sdk::__query_builder::IxCol<SettlementProperty, String>,
}

impl __sdk::__query_builder::HasIxCols for SettlementProperty {
    type IxCols = SettlementPropertyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SettlementPropertyIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            settlement_id: __sdk::__query_builder::IxCol::new(table_name, "settlement_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SettlementProperty {}
