// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::business_id_type::BusinessId;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SettlementBusinessOperator {
    pub id: String,
    pub settlement_id: String,
    pub business_id: BusinessId,
    pub operator_character_id: u64,
}

impl __sdk::InModule for SettlementBusinessOperator {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SettlementBusinessOperator`.
///
/// Provides typed access to columns for query building.
pub struct SettlementBusinessOperatorCols {
    pub id: __sdk::__query_builder::Col<SettlementBusinessOperator, String>,
    pub settlement_id: __sdk::__query_builder::Col<SettlementBusinessOperator, String>,
    pub business_id: __sdk::__query_builder::Col<SettlementBusinessOperator, BusinessId>,
    pub operator_character_id: __sdk::__query_builder::Col<SettlementBusinessOperator, u64>,
}

impl __sdk::__query_builder::HasCols for SettlementBusinessOperator {
    type Cols = SettlementBusinessOperatorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SettlementBusinessOperatorCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            business_id: __sdk::__query_builder::Col::new(table_name, "business_id"),
            operator_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "operator_character_id",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `SettlementBusinessOperator`.
///
/// Provides typed access to indexed columns for query building.
pub struct SettlementBusinessOperatorIxCols {
    pub id: __sdk::__query_builder::IxCol<SettlementBusinessOperator, String>,
    pub operator_character_id: __sdk::__query_builder::IxCol<SettlementBusinessOperator, u64>,
    pub settlement_id: __sdk::__query_builder::IxCol<SettlementBusinessOperator, String>,
}

impl __sdk::__query_builder::HasIxCols for SettlementBusinessOperator {
    type IxCols = SettlementBusinessOperatorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SettlementBusinessOperatorIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            operator_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "operator_character_id",
            ),
            settlement_id: __sdk::__query_builder::IxCol::new(table_name, "settlement_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SettlementBusinessOperator {}
