// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::seed_type::Seed;
use super::simulation_run_type::SimulationRun;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `simulation_run`.
///
/// Obtain a handle from the [`SimulationRunTableAccess::simulation_run`] method on [`super::RemoteTables`],
/// like `ctx.db.simulation_run()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.simulation_run().on_insert(...)`.
pub struct SimulationRunTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimulationRun>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `simulation_run`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimulationRunTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimulationRunTableHandle`], which mediates access to the table `simulation_run`.
    fn simulation_run(&self) -> SimulationRunTableHandle<'_>;
}

impl SimulationRunTableAccess for super::RemoteTables {
    fn simulation_run(&self) -> SimulationRunTableHandle<'_> {
        SimulationRunTableHandle {
            imp: self.imp.get_table::<SimulationRun>("simulation_run"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimulationRunInsertCallbackId(__sdk::CallbackId);
pub struct SimulationRunDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimulationRunTableHandle<'ctx> {
    type Row = SimulationRun;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimulationRun> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimulationRunInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimulationRunInsertCallbackId {
        SimulationRunInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimulationRunInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimulationRunDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimulationRunDeleteCallbackId {
        SimulationRunDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimulationRunDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SimulationRunUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SimulationRunTableHandle<'ctx> {
    type UpdateCallbackId = SimulationRunUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SimulationRunUpdateCallbackId {
        SimulationRunUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SimulationRunUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `simulation_run`,
/// which allows point queries on the field of the same name
/// via the [`SimulationRunIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.simulation_run().id().find(...)`.
pub struct SimulationRunIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SimulationRun, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SimulationRunTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `simulation_run`.
    pub fn id(&self) -> SimulationRunIdUnique<'ctx> {
        SimulationRunIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SimulationRunIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SimulationRun> {
        self.imp.find(col_val)
    }
}

/// Access to the `nonce` unique index on the table `simulation_run`,
/// which allows point queries on the field of the same name
/// via the [`SimulationRunNonceUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.simulation_run().nonce().find(...)`.
pub struct SimulationRunNonceUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SimulationRun, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SimulationRunTableHandle<'ctx> {
    /// Get a handle on the `nonce` unique index on the table `simulation_run`.
    pub fn nonce(&self) -> SimulationRunNonceUnique<'ctx> {
        SimulationRunNonceUnique {
            imp: self.imp.get_unique_constraint::<String>("nonce"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SimulationRunNonceUnique<'ctx> {
    /// Find the subscribed row whose `nonce` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SimulationRun> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimulationRun>("simulation_run");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("nonce", |row| &row.nonce);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimulationRun>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimulationRun>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimulationRun`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait simulation_runQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimulationRun`.
    fn simulation_run(&self) -> __sdk::__query_builder::Table<SimulationRun>;
}

impl simulation_runQueryTableAccess for __sdk::QueryTableAccessor {
    fn simulation_run(&self) -> __sdk::__query_builder::Table<SimulationRun> {
        __sdk::__query_builder::Table::new("simulation_run")
    }
}
