// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::social_chat_outcome_type::SocialChatOutcome;
use super::social_chat_target_kind_type::SocialChatTargetKind;
use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SocialChatReceipt {
    pub id: String,
    pub actor_id: u64,
    pub action_id: String,
    pub target_kind: SocialChatTargetKind,
    pub target_id: String,
    pub requested_minutes: u64,
    pub outcome: SocialChatOutcome,
    pub occurred_at_minute: StrategicMinute,
}

impl __sdk::InModule for SocialChatReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SocialChatReceipt`.
///
/// Provides typed access to columns for query building.
pub struct SocialChatReceiptCols {
    pub id: __sdk::__query_builder::Col<SocialChatReceipt, String>,
    pub actor_id: __sdk::__query_builder::Col<SocialChatReceipt, u64>,
    pub action_id: __sdk::__query_builder::Col<SocialChatReceipt, String>,
    pub target_kind: __sdk::__query_builder::Col<SocialChatReceipt, SocialChatTargetKind>,
    pub target_id: __sdk::__query_builder::Col<SocialChatReceipt, String>,
    pub requested_minutes: __sdk::__query_builder::Col<SocialChatReceipt, u64>,
    pub outcome: __sdk::__query_builder::Col<SocialChatReceipt, SocialChatOutcome>,
    pub occurred_at_minute: __sdk::__query_builder::Col<SocialChatReceipt, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for SocialChatReceipt {
    type Cols = SocialChatReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SocialChatReceiptCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            actor_id: __sdk::__query_builder::Col::new(table_name, "actor_id"),
            action_id: __sdk::__query_builder::Col::new(table_name, "action_id"),
            target_kind: __sdk::__query_builder::Col::new(table_name, "target_kind"),
            target_id: __sdk::__query_builder::Col::new(table_name, "target_id"),
            requested_minutes: __sdk::__query_builder::Col::new(table_name, "requested_minutes"),
            outcome: __sdk::__query_builder::Col::new(table_name, "outcome"),
            occurred_at_minute: __sdk::__query_builder::Col::new(table_name, "occurred_at_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `SocialChatReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct SocialChatReceiptIxCols {
    pub actor_id: __sdk::__query_builder::IxCol<SocialChatReceipt, u64>,
    pub id: __sdk::__query_builder::IxCol<SocialChatReceipt, String>,
}

impl __sdk::__query_builder::HasIxCols for SocialChatReceipt {
    type IxCols = SocialChatReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SocialChatReceiptIxCols {
            actor_id: __sdk::__query_builder::IxCol::new(table_name, "actor_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SocialChatReceipt {}
