// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SocialAddress {
    pub id: String,
    pub actor_id: u64,
    pub target_id: u64,
    pub source_id: String,
    pub addressed_at_minute: StrategicMinute,
}

impl __sdk::InModule for SocialAddress {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SocialAddress`.
///
/// Provides typed access to columns for query building.
pub struct SocialAddressCols {
    pub id: __sdk::__query_builder::Col<SocialAddress, String>,
    pub actor_id: __sdk::__query_builder::Col<SocialAddress, u64>,
    pub target_id: __sdk::__query_builder::Col<SocialAddress, u64>,
    pub source_id: __sdk::__query_builder::Col<SocialAddress, String>,
    pub addressed_at_minute: __sdk::__query_builder::Col<SocialAddress, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for SocialAddress {
    type Cols = SocialAddressCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SocialAddressCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            actor_id: __sdk::__query_builder::Col::new(table_name, "actor_id"),
            target_id: __sdk::__query_builder::Col::new(table_name, "target_id"),
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            addressed_at_minute: __sdk::__query_builder::Col::new(
                table_name,
                "addressed_at_minute",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `SocialAddress`.
///
/// Provides typed access to indexed columns for query building.
pub struct SocialAddressIxCols {
    pub actor_id: __sdk::__query_builder::IxCol<SocialAddress, u64>,
    pub id: __sdk::__query_builder::IxCol<SocialAddress, String>,
    pub target_id: __sdk::__query_builder::IxCol<SocialAddress, u64>,
}

impl __sdk::__query_builder::HasIxCols for SocialAddress {
    type IxCols = SocialAddressIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SocialAddressIxCols {
            actor_id: __sdk::__query_builder::IxCol::new(table_name, "actor_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            target_id: __sdk::__query_builder::IxCol::new(table_name, "target_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SocialAddress {}
