// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SocialInteraction {
    pub id: u64,
    pub actor_id: u64,
    pub target_id: u64,
    pub source_id: String,
    pub topic: String,
    pub action_kind: String,
    pub succeeded: bool,
    pub morale_delta: f32,
    pub occurred_at_minute: StrategicMinute,
}

impl __sdk::InModule for SocialInteraction {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SocialInteraction`.
///
/// Provides typed access to columns for query building.
pub struct SocialInteractionCols {
    pub id: __sdk::__query_builder::Col<SocialInteraction, u64>,
    pub actor_id: __sdk::__query_builder::Col<SocialInteraction, u64>,
    pub target_id: __sdk::__query_builder::Col<SocialInteraction, u64>,
    pub source_id: __sdk::__query_builder::Col<SocialInteraction, String>,
    pub topic: __sdk::__query_builder::Col<SocialInteraction, String>,
    pub action_kind: __sdk::__query_builder::Col<SocialInteraction, String>,
    pub succeeded: __sdk::__query_builder::Col<SocialInteraction, bool>,
    pub morale_delta: __sdk::__query_builder::Col<SocialInteraction, f32>,
    pub occurred_at_minute: __sdk::__query_builder::Col<SocialInteraction, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for SocialInteraction {
    type Cols = SocialInteractionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SocialInteractionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            actor_id: __sdk::__query_builder::Col::new(table_name, "actor_id"),
            target_id: __sdk::__query_builder::Col::new(table_name, "target_id"),
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            topic: __sdk::__query_builder::Col::new(table_name, "topic"),
            action_kind: __sdk::__query_builder::Col::new(table_name, "action_kind"),
            succeeded: __sdk::__query_builder::Col::new(table_name, "succeeded"),
            morale_delta: __sdk::__query_builder::Col::new(table_name, "morale_delta"),
            occurred_at_minute: __sdk::__query_builder::Col::new(table_name, "occurred_at_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `SocialInteraction`.
///
/// Provides typed access to indexed columns for query building.
pub struct SocialInteractionIxCols {
    pub actor_id: __sdk::__query_builder::IxCol<SocialInteraction, u64>,
    pub id: __sdk::__query_builder::IxCol<SocialInteraction, u64>,
    pub target_id: __sdk::__query_builder::IxCol<SocialInteraction, u64>,
}

impl __sdk::__query_builder::HasIxCols for SocialInteraction {
    type IxCols = SocialInteractionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SocialInteractionIxCols {
            actor_id: __sdk::__query_builder::IxCol::new(table_name, "actor_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            target_id: __sdk::__query_builder::IxCol::new(table_name, "target_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SocialInteraction {}
