// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpouseLeisureAccrual {
    pub pair_id: String,
    pub first_character_id: u64,
    pub second_character_id: u64,
    pub conserved_joint_minutes: u8,
    pub next_trial_ordinal: u64,
}

impl __sdk::InModule for SpouseLeisureAccrual {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpouseLeisureAccrual`.
///
/// Provides typed access to columns for query building.
pub struct SpouseLeisureAccrualCols {
    pub pair_id: __sdk::__query_builder::Col<SpouseLeisureAccrual, String>,
    pub first_character_id: __sdk::__query_builder::Col<SpouseLeisureAccrual, u64>,
    pub second_character_id: __sdk::__query_builder::Col<SpouseLeisureAccrual, u64>,
    pub conserved_joint_minutes: __sdk::__query_builder::Col<SpouseLeisureAccrual, u8>,
    pub next_trial_ordinal: __sdk::__query_builder::Col<SpouseLeisureAccrual, u64>,
}

impl __sdk::__query_builder::HasCols for SpouseLeisureAccrual {
    type Cols = SpouseLeisureAccrualCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpouseLeisureAccrualCols {
            pair_id: __sdk::__query_builder::Col::new(table_name, "pair_id"),
            first_character_id: __sdk::__query_builder::Col::new(table_name, "first_character_id"),
            second_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "second_character_id",
            ),
            conserved_joint_minutes: __sdk::__query_builder::Col::new(
                table_name,
                "conserved_joint_minutes",
            ),
            next_trial_ordinal: __sdk::__query_builder::Col::new(table_name, "next_trial_ordinal"),
        }
    }
}

/// Indexed column accessor struct for the table `SpouseLeisureAccrual`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpouseLeisureAccrualIxCols {
    pub pair_id: __sdk::__query_builder::IxCol<SpouseLeisureAccrual, String>,
}

impl __sdk::__query_builder::HasIxCols for SpouseLeisureAccrual {
    type IxCols = SpouseLeisureAccrualIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpouseLeisureAccrualIxCols {
            pair_id: __sdk::__query_builder::IxCol::new(table_name, "pair_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpouseLeisureAccrual {}
