// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StartingCharacterClaim {
    pub request_key: String,
    pub character_id: u64,
    pub owner_key: String,
}

impl __sdk::InModule for StartingCharacterClaim {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StartingCharacterClaim`.
///
/// Provides typed access to columns for query building.
pub struct StartingCharacterClaimCols {
    pub request_key: __sdk::__query_builder::Col<StartingCharacterClaim, String>,
    pub character_id: __sdk::__query_builder::Col<StartingCharacterClaim, u64>,
    pub owner_key: __sdk::__query_builder::Col<StartingCharacterClaim, String>,
}

impl __sdk::__query_builder::HasCols for StartingCharacterClaim {
    type Cols = StartingCharacterClaimCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StartingCharacterClaimCols {
            request_key: __sdk::__query_builder::Col::new(table_name, "request_key"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            owner_key: __sdk::__query_builder::Col::new(table_name, "owner_key"),
        }
    }
}

/// Indexed column accessor struct for the table `StartingCharacterClaim`.
///
/// Provides typed access to indexed columns for query building.
pub struct StartingCharacterClaimIxCols {
    pub character_id: __sdk::__query_builder::IxCol<StartingCharacterClaim, u64>,
    pub owner_key: __sdk::__query_builder::IxCol<StartingCharacterClaim, String>,
    pub request_key: __sdk::__query_builder::IxCol<StartingCharacterClaim, String>,
}

impl __sdk::__query_builder::HasIxCols for StartingCharacterClaim {
    type IxCols = StartingCharacterClaimIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StartingCharacterClaimIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            owner_key: __sdk::__query_builder::IxCol::new(table_name, "owner_key"),
            request_key: __sdk::__query_builder::IxCol::new(table_name, "request_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StartingCharacterClaim {}
