// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::surrender_obligation_kind_type::SurrenderObligationKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SurrenderObligation {
    pub kind: SurrenderObligationKind,
    pub beneficiary_id: String,
    pub amount_minor: u64,
}

impl __sdk::InModule for SurrenderObligation {
    type Module = super::RemoteModule;
}
