// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tactical_participant_exclusion_type::TacticalParticipantExclusion;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tactical_participant_exclusions`.
///
/// Obtain a handle from the [`TacticalParticipantExclusionsTableAccess::tactical_participant_exclusions`] method on [`super::RemoteTables`],
/// like `ctx.db.tactical_participant_exclusions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tactical_participant_exclusions().on_insert(...)`.
pub struct TacticalParticipantExclusionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<TacticalParticipantExclusion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tactical_participant_exclusions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TacticalParticipantExclusionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TacticalParticipantExclusionsTableHandle`], which mediates access to the table `tactical_participant_exclusions`.
    fn tactical_participant_exclusions(&self) -> TacticalParticipantExclusionsTableHandle<'_>;
}

impl TacticalParticipantExclusionsTableAccess for super::RemoteTables {
    fn tactical_participant_exclusions(&self) -> TacticalParticipantExclusionsTableHandle<'_> {
        TacticalParticipantExclusionsTableHandle {
            imp: self
                .imp
                .get_table::<TacticalParticipantExclusion>("tactical_participant_exclusions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TacticalParticipantExclusionsInsertCallbackId(__sdk::CallbackId);
pub struct TacticalParticipantExclusionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TacticalParticipantExclusionsTableHandle<'ctx> {
    type Row = TacticalParticipantExclusion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TacticalParticipantExclusion> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TacticalParticipantExclusionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TacticalParticipantExclusionsInsertCallbackId {
        TacticalParticipantExclusionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TacticalParticipantExclusionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TacticalParticipantExclusionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TacticalParticipantExclusionsDeleteCallbackId {
        TacticalParticipantExclusionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TacticalParticipantExclusionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TacticalParticipantExclusion>("tactical_participant_exclusions");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TacticalParticipantExclusion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TacticalParticipantExclusion>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TacticalParticipantExclusion`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait tactical_participant_exclusionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TacticalParticipantExclusion`.
    fn tactical_participant_exclusions(
        &self,
    ) -> __sdk::__query_builder::Table<TacticalParticipantExclusion>;
}

impl tactical_participant_exclusionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn tactical_participant_exclusions(
        &self,
    ) -> __sdk::__query_builder::Table<TacticalParticipantExclusion> {
        __sdk::__query_builder::Table::new("tactical_participant_exclusions")
    }
}
