// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::strategic_minute_type::StrategicMinute;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WaterCollectionReceipt {
    pub request_id: String,
    pub character_id: u64,
    pub capability_id: String,
    pub capability_version: u32,
    pub source_fixture_id: String,
    pub container_object_id: u64,
    pub material_lot_id: u64,
    pub source_material_lot_id: u64,
    pub source_revision_before: u64,
    pub source_amount_before_ml: u64,
    pub source_amount_after_ml: u64,
    pub contaminant_load_microunits: u64,
    pub amount_ml: u64,
    pub collected_at: StrategicMinute,
}

impl __sdk::InModule for WaterCollectionReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WaterCollectionReceipt`.
///
/// Provides typed access to columns for query building.
pub struct WaterCollectionReceiptCols {
    pub request_id: __sdk::__query_builder::Col<WaterCollectionReceipt, String>,
    pub character_id: __sdk::__query_builder::Col<WaterCollectionReceipt, u64>,
    pub capability_id: __sdk::__query_builder::Col<WaterCollectionReceipt, String>,
    pub capability_version: __sdk::__query_builder::Col<WaterCollectionReceipt, u32>,
    pub source_fixture_id: __sdk::__query_builder::Col<WaterCollectionReceipt, String>,
    pub container_object_id: __sdk::__query_builder::Col<WaterCollectionReceipt, u64>,
    pub material_lot_id: __sdk::__query_builder::Col<WaterCollectionReceipt, u64>,
    pub source_material_lot_id: __sdk::__query_builder::Col<WaterCollectionReceipt, u64>,
    pub source_revision_before: __sdk::__query_builder::Col<WaterCollectionReceipt, u64>,
    pub source_amount_before_ml: __sdk::__query_builder::Col<WaterCollectionReceipt, u64>,
    pub source_amount_after_ml: __sdk::__query_builder::Col<WaterCollectionReceipt, u64>,
    pub contaminant_load_microunits: __sdk::__query_builder::Col<WaterCollectionReceipt, u64>,
    pub amount_ml: __sdk::__query_builder::Col<WaterCollectionReceipt, u64>,
    pub collected_at: __sdk::__query_builder::Col<WaterCollectionReceipt, StrategicMinute>,
}

impl __sdk::__query_builder::HasCols for WaterCollectionReceipt {
    type Cols = WaterCollectionReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WaterCollectionReceiptCols {
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            capability_id: __sdk::__query_builder::Col::new(table_name, "capability_id"),
            capability_version: __sdk::__query_builder::Col::new(table_name, "capability_version"),
            source_fixture_id: __sdk::__query_builder::Col::new(table_name, "source_fixture_id"),
            container_object_id: __sdk::__query_builder::Col::new(
                table_name,
                "container_object_id",
            ),
            material_lot_id: __sdk::__query_builder::Col::new(table_name, "material_lot_id"),
            source_material_lot_id: __sdk::__query_builder::Col::new(
                table_name,
                "source_material_lot_id",
            ),
            source_revision_before: __sdk::__query_builder::Col::new(
                table_name,
                "source_revision_before",
            ),
            source_amount_before_ml: __sdk::__query_builder::Col::new(
                table_name,
                "source_amount_before_ml",
            ),
            source_amount_after_ml: __sdk::__query_builder::Col::new(
                table_name,
                "source_amount_after_ml",
            ),
            contaminant_load_microunits: __sdk::__query_builder::Col::new(
                table_name,
                "contaminant_load_microunits",
            ),
            amount_ml: __sdk::__query_builder::Col::new(table_name, "amount_ml"),
            collected_at: __sdk::__query_builder::Col::new(table_name, "collected_at"),
        }
    }
}

/// Indexed column accessor struct for the table `WaterCollectionReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct WaterCollectionReceiptIxCols {
    pub request_id: __sdk::__query_builder::IxCol<WaterCollectionReceipt, String>,
}

impl __sdk::__query_builder::HasIxCols for WaterCollectionReceipt {
    type IxCols = WaterCollectionReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WaterCollectionReceiptIxCols {
            request_id: __sdk::__query_builder::IxCol::new(table_name, "request_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WaterCollectionReceipt {}
