// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::strategic_minute_type::StrategicMinute;
use super::world_clock_type::WorldClock;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_clock`.
///
/// Obtain a handle from the [`WorldClockTableAccess::world_clock`] method on [`super::RemoteTables`],
/// like `ctx.db.world_clock()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_clock().on_insert(...)`.
pub struct WorldClockTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldClock>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_clock`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldClockTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldClockTableHandle`], which mediates access to the table `world_clock`.
    fn world_clock(&self) -> WorldClockTableHandle<'_>;
}

impl WorldClockTableAccess for super::RemoteTables {
    fn world_clock(&self) -> WorldClockTableHandle<'_> {
        WorldClockTableHandle {
            imp: self.imp.get_table::<WorldClock>("world_clock"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldClockInsertCallbackId(__sdk::CallbackId);
pub struct WorldClockDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorldClockTableHandle<'ctx> {
    type Row = WorldClock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldClock> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldClockInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldClockInsertCallbackId {
        WorldClockInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldClockInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldClockDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldClockDeleteCallbackId {
        WorldClockDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldClockDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldClockUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldClockTableHandle<'ctx> {
    type UpdateCallbackId = WorldClockUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldClockUpdateCallbackId {
        WorldClockUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldClockUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `world_clock`,
/// which allows point queries on the field of the same name
/// via the [`WorldClockIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_clock().id().find(...)`.
pub struct WorldClockIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldClock, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldClockTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_clock`.
    pub fn id(&self) -> WorldClockIdUnique<'ctx> {
        WorldClockIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldClockIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorldClock> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldClock>("world_clock");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldClock>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldClock>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldClock`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_clockQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldClock`.
    fn world_clock(&self) -> __sdk::__query_builder::Table<WorldClock>;
}

impl world_clockQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_clock(&self) -> __sdk::__query_builder::Table<WorldClock> {
        __sdk::__query_builder::Table::new("world_clock")
    }
}
