//! Anatomical fragments used by authored rig naming and skin selection.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RigJointPart {
    Hand,
    Loleg,
    Loarm,
    Thumb3,
    ThumbNull,
    Pinky3,
    Pinky2,
    Pinky1,
    Pinky0,
    RingNull,
    Ring3,
    Ring2,
    Middle3,
    Middle2,
    IndexNull,
    Index3,
    Ball,
    Camera,
    Clavicle,
    Eye,
    Foot,
    Head,
    Index,
    Index1,
    Index2,
    Jaw,
    JawNull,
    Lowarm,
    LowarmTwist,
    Lowleg,
    LowlegTwist,
    Middle,
    Middle1,
    MiddleNull,
    Neck,
    NeckTwist,
    Pinky,
    PinkyNull,
    Ring,
    Ring1,
    Spine,
    Spine0,
    Spine1,
    Spine2,
    Spine3,
    Subtalar,
    Talocrural,
    Thumb,
    Thumb0,
    Thumb1,
    Toe,
    Tongue,
    Transversetarsal,
    Uparm,
    UparmTwist,
    UparmTwist0Proc,
    UparmTwist3Proc,
    Upleg,
    UplegTwist,
    UplegTwist2Proc,
    UplegTwist3Proc,
    Upperarm,
    Weapon,
    Wrist,
}
impl std::fmt::Display for RigJointPart {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Hand => "hand",
            Self::Loleg => "loleg",
            Self::Loarm => "loarm",
            Self::Thumb3 => "thumb3",
            Self::ThumbNull => "thumb_null",
            Self::Pinky3 => "pinky3",
            Self::Pinky2 => "pinky2",
            Self::Pinky1 => "pinky1",
            Self::Pinky0 => "pinky0",
            Self::RingNull => "ring_null",
            Self::Ring3 => "ring3",
            Self::Ring2 => "ring2",
            Self::Middle3 => "middle3",
            Self::Middle2 => "middle2",
            Self::IndexNull => "index_null",
            Self::Index3 => "index3",
            Self::Ball => "ball",
            Self::Camera => "camera",
            Self::Clavicle => "clavicle",
            Self::Eye => "eye",
            Self::Foot => "foot",
            Self::Head => "head",
            Self::Index => "index",
            Self::Index1 => "index1",
            Self::Index2 => "index2",
            Self::Jaw => "jaw",
            Self::JawNull => "jaw_null",
            Self::Lowarm => "lowarm",
            Self::LowarmTwist => "lowarm_twist",
            Self::Lowleg => "lowleg",
            Self::LowlegTwist => "lowleg_twist",
            Self::Middle => "middle",
            Self::Middle1 => "middle1",
            Self::MiddleNull => "middle_null",
            Self::Neck => "neck",
            Self::NeckTwist => "neck_twist",
            Self::Pinky => "pinky",
            Self::PinkyNull => "pinky_null",
            Self::Ring => "ring",
            Self::Ring1 => "ring1",
            Self::Spine => "spine",
            Self::Spine0 => "spine0",
            Self::Spine1 => "spine1",
            Self::Spine2 => "spine2",
            Self::Spine3 => "spine3",
            Self::Subtalar => "subtalar",
            Self::Talocrural => "talocrural",
            Self::Thumb => "thumb",
            Self::Thumb0 => "thumb0",
            Self::Thumb1 => "thumb1",
            Self::Toe => "toe",
            Self::Tongue => "tongue",
            Self::Transversetarsal => "transversetarsal",
            Self::Uparm => "uparm",
            Self::UparmTwist => "uparm_twist",
            Self::UparmTwist0Proc => "uparm_twist0_proc",
            Self::UparmTwist3Proc => "uparm_twist3_proc",
            Self::Upleg => "upleg",
            Self::UplegTwist => "upleg_twist",
            Self::UplegTwist2Proc => "upleg_twist2_proc",
            Self::UplegTwist3Proc => "upleg_twist3_proc",
            Self::Upperarm => "upperarm",
            Self::Weapon => "weapon",
            Self::Wrist => "wrist",
        })
    }
}
