//! Shared leaf morphology adapted from adventure-simulator-group/leaves.
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LeafShape {
    pub half_length: f32,
    pub half_width: f32,
    pub widest_at: f32,
    pub base_exponent: f32,
    pub tip_exponent: f32,
    pub base_width: f32,
    pub tip_width: f32,
    pub asymmetry: f32,
    pub bend: f32,
    pub petiole_length: f32,
    pub petiole_width: f32,
    pub midrib_width: f32,
    pub base_notch_depth: f32,
    pub base_notch_width: f32,
    pub tip_notch_depth: f32,
    pub tip_notch_width: f32,
    pub lobe_frequency: f32,
    pub lobe_depth: f32,
    pub lobe_roundness: f32,
    pub lobe_stagger: f32,
    pub tooth_frequency: f32,
    pub tooth_depth: f32,
    pub tooth_sharpness: f32,
    pub tooth_lean: f32,
    pub secondary_count: f32,
    pub secondary_first: f32,
    pub secondary_last: f32,
    pub secondary_reach: f32,
    pub secondary_sweep: f32,
    pub secondary_curve: f32,
    pub secondary_width: f32,
    pub secondary_tip_width: f32,
    pub lobe_basal_scale: f32,
    pub lobe_middle_scale: f32,
    pub lobe_apical_scale: f32,
    pub lobe_progressive_sweep: f32,
    pub secondary_tooth_ratio: f32,
    pub margin_hierarchy: f32,
    pub margin_asymmetry: f32,
    pub lobe_bristle: f32,
    pub vein_alternation: f32,
    pub vein_gradation: f32,
    pub vein_branching: f32,
    pub vein_loops: f32,
    pub palmate: f32,
    pub compound_separation: f32,
    pub fan: f32,
    pub parallel_venation: f32,
    pub organ_count: f32,
    pub organ_spread: f32,
    pub organ_length: f32,
    pub organ_width: f32,
    pub organ_attachment: f32,
    pub terminal_scale: f32,
    pub organ_alternation: f32,
    pub dichotomy: f32,
    pub bipinnate: f32,
    pub pinna_count: f32,
    pub leaflet_count: f32,
    pub pinna_length: f32,
    pub basal_obliquity: f32,
    pub landmark_lobes: f32,
    pub landmark_side_bias: f32,
    pub apex_truncation: f32,
    pub frond: f32,
    pub fan_segmentation: f32,
    pub peltate_depth: f32,
    pub longitudinal_veins: f32,
}
impl Default for LeafShape {
    fn default() -> Self {
        Self::preset("white-oak").expect("built-in oak preset")
    }
}
impl LeafShape {
    /// Interpolate morphology; exact endpoints preserve authored presets byte for byte.
    pub fn interpolate(&self, target: &Self, amount: f32) -> Self {
        let t = amount.clamp(0.0, 1.0);
        if t == 0.0 {
            return self.clone();
        }
        if t == 1.0 {
            return target.clone();
        }
        let mut result = self.clone();
        macro_rules! blend { ($($field:ident),* $(,)?)=> { $(result.$field=self.$field+(target.$field-self.$field)*t;)* }; }
        blend!(
            half_length,
            half_width,
            widest_at,
            base_exponent,
            tip_exponent,
            base_width,
            tip_width,
            asymmetry,
            bend,
            petiole_length,
            petiole_width,
            midrib_width,
            base_notch_depth,
            base_notch_width,
            tip_notch_depth,
            tip_notch_width,
            lobe_frequency,
            lobe_depth,
            lobe_roundness,
            lobe_stagger,
            tooth_frequency,
            tooth_depth,
            tooth_sharpness,
            tooth_lean,
            secondary_count,
            secondary_first,
            secondary_last,
            secondary_reach,
            secondary_sweep,
            secondary_curve,
            secondary_width,
            secondary_tip_width,
            lobe_basal_scale,
            lobe_middle_scale,
            lobe_apical_scale,
            lobe_progressive_sweep,
            secondary_tooth_ratio,
            margin_hierarchy,
            margin_asymmetry,
            lobe_bristle,
            vein_alternation,
            vein_gradation,
            vein_branching,
            vein_loops,
            palmate,
            compound_separation,
            fan,
            parallel_venation,
            organ_count,
            organ_spread,
            organ_length,
            organ_width,
            organ_attachment,
            terminal_scale,
            organ_alternation,
            dichotomy,
            bipinnate,
            pinna_count,
            leaflet_count,
            pinna_length,
            basal_obliquity,
            landmark_lobes,
            landmark_side_bias,
            apex_truncation,
            frond,
            fan_segmentation,
            peltate_depth,
            longitudinal_veins
        );
        result
    }
}
