[package]
name = "adventuresim-weapon-model"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
postcard.workspace = true
tiny-skia.workspace = true
glam = "0.32.1"

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
