//! Geographic connection classifications retained for map presentation.
//! This adds no travel authority: routing remains owned by its existing data.
use serde::{Deserialize, Serialize};
use std::{fmt, str::FromStr};

/// Viabundus distinguishes roads, shipping routes, ferries and winter routes.
/// Inferred walking links are generated by the canonical world compiler.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RegionalConnectionKind {
    Land,
    River,
    Coast,
    Canal,
    Ferry,
    Winter,
    InferredWalkingLink,
}

#[derive(Clone, Copy, Debug)]
pub struct RegionalConnectionKindError;

impl FromStr for RegionalConnectionKind {
    type Err = RegionalConnectionKindError;

    /// Decode the native source category at the CSV boundary.
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "land" => Ok(Self::Land),
            "river" => Ok(Self::River),
            "coast" => Ok(Self::Coast),
            "canal" => Ok(Self::Canal),
            "ferry" => Ok(Self::Ferry),
            "winter" => Ok(Self::Winter),
            "inferred_walking_link" => Ok(Self::InferredWalkingLink),
            _ => Err(RegionalConnectionKindError),
        }
    }
}

impl fmt::Display for RegionalConnectionKindError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("unknown regional connection classification")
    }
}

impl std::error::Error for RegionalConnectionKindError {}
